Repository gap-system/gap, pull requests merged in 2018-06, with the labels that each got.

#2498 Allow a help expression to return a value
  src/intrprtr.c
Labels: backport-to-4.9, not for release notes

#2494 GASMAN: make some vars static; cleanup InitBags interface & docs
  src/boehm_gc.c
  src/gap.c
  src/gasman.c
  src/gasman.h
Labels: kernel, not for release notes

#2514 kernel: add missing IntrReturning check to IntrNot
  src/intrprtr.c
Labels: bug, kernel, not for release notes

#2519 Change Test() to reject unexpected or invalid inputs
  lib/test.gi
Labels: enhancement, tests

#2517 Add ffgen to .gitignore
  .gitignore
Labels: not for release notes

#2518 kernel: update comments in scanner.{c,h}
  src/scanner.c
  src/scanner.h
Labels: documentation, kernel, not for release notes

#2383 Speed improvements for automorphism groups
  doc/tut/group.xml
  lib/autsr.gi
  lib/ctbl.gd
  lib/grpperm.gi
  lib/morpheus.gi
  lib/teaching.g
Labels: enhancement, library

#2535 Add tests for ReadCSV and PrintCSV
  tst/testinstall/files/example.csv
  tst/testinstall/strings.tst
Labels: gapdays2018, tests

#2541 kernel: make StructInitInfo const
  src/modules.h
  src/system.h
Labels: kernel, not for release notes

#2486 Add test for `IsInternallyConsistent`
  tst/testinstall/ctblfuns.tst
Labels: tests

#2539 kernel: remove redundant SET_LEN_PLIST(l,0) calls
  src/calls.c
  src/code.c
  src/compiler.c
  src/dt.c
  src/dteval.c
  src/exprs.c
  src/gap.c
  src/gvars.c
  src/intrprtr.c
  src/listfunc.c
  src/listoper.c
  src/objfgelm.c
  src/opers.c
  src/permutat.c
  src/plist.c
  src/pperm.c
  src/range.c
  src/read.c
  src/records.c
  src/scanner.c
  src/stringobj.c
  src/tietze.c
  src/trans.c
  src/vec8bit.c
  src/vecgf2.c
Labels: kernel, not for release notes

#2528 Added IsLIBGAP constant
  lib/init.g
  tst/testinstall/IsLIBGAP.tst
Labels: gapdays2018

#2544 kernel: filter/attribute/property handlers must have 2 args
  src/modules.h
Labels: kernel, not for release notes

#2533 Don't use fast method for composing with identity mapping if source & range don't match
  lib/mapprep.gi
  tst/testbugfix/2018-06-11-mapping.tst
Labels: bug, gapdays2018, library

#2537 Further improve test coverage for ReadCSV
  tst/testinstall/strings.tst
Labels: tests

#2552 Fix typo in checking if a filename is *stderr*
  src/streams.c
  tst/testinstall/streams.tst
Labels: kernel, not for release notes

#2548 kernel: add new helper function Panic()
  src/calls.c
  src/error.c
  src/gap.c
  src/gasman.c
  src/gvars.c
  src/integer.c
  src/modules.c
  src/saveload.c
  src/sysmem.c
  src/sysmem.h
  src/system.c
  src/system.h
  src/vec8bit.c
Labels: kernel, not for release notes

#2556 Add missing header
  src/profile.c
Labels: not for release notes

#2557 Make CALL_WITH_CATCH work with Kernel functions
  src/error.c
Labels: kernel, not for release notes

#2529 Make error output use the same stream consistently
  lib/error.g
  src/error.c
  tst/testinstall/kernel/gap.tst
Labels: gapdays2018, kernel, library

#2562 Fix crash when using OnTuples or OnSets on empty lists
  src/listfunc.c
  tst/testbugfix/2018-06-18-empty-OnTuples.tst
Labels: bug: crash, not for release notes, regression

#2560 kernel: fix crash in GASMAN("global")
  src/gap.c
Labels: bug: crash, kernel, not for release notes

#2583 hpcgap: remove automata patch
  hpcgap/pkg-diffs/automata-2015-11-18.diff
Labels: not for release notes

#2580 kernel: don't include gmp.h from integer.h
  src/gap.c
  src/integer.c
  src/integer.h
  src/vecgf2.c
Labels: kernel, not for release notes

#2581 kernel: simplify 32bit C_MAKE_MED_INT
  src/compiled.h
Labels: kernel, not for release notes

#2577 Add forms for Omega(e,d,q), except when d odd, q even; some cleanup
  grp/classic.gi
  tst/testinstall/grp/classic-forms.tst
Labels: enhancement, library

#2588 hpcgap: sync lib/error.g
  hpcgap/lib/error.g
  lib/error.g
  lib/init.g
Labels: HPC-GAP, HPC-GAP unification, regression

#2563 kernel: get rid of FN_IS_EMPTY
  dev/lists.txt
  src/blister.c
  src/listfunc.c
  src/listoper.c
  src/lists.c
  src/lists.h
  src/plist.c
  src/range.c
  src/set.c
  src/stringobj.c
Labels: kernel, not for release notes

#2572 kernel: unify statement reading code
  src/read.c
Labels: kernel, not for release notes
