Repository gap-system/gap, pull requests merged in 2018-12, with the labels that each got.

#3079 Fix NumberFFVector documentation, add an example
  lib/listcoef.gd
  lib/vecmat.gd
Labels: backport-to-4.10, kind: bug, topic: documentation, topic: library

#3081 Remove IS_NSORT / IsNSortedList
  lib/list.gd
  src/lists.c
  src/lists.h
Labels: release notes: to be added

#3088 Travis: disable -Werror for Julia builds
  .travis.yml
  etc/ci-prepare.sh
Labels: release notes: not needed, topic: infrastructure, topic: tests

#3083 kernel: convert pperm.c and trans.c to C++
  Makefile.rules
  src/collectors.cc
  src/compiled.h
  src/objfgelm.cc
  src/objpcgel.cc
  src/permutat.cc
  src/pperm.cc
  src/trans.cc
Labels: release notes: not needed, topic: kernel

#3084 kernel: add RequireMutableSet helper in set.c
  src/set.c
  tst/testinstall/kernel/set.tst
Labels: release notes: not needed, topic: kernel

#3093 `IsMatrixObj` objects as elements of GAP's matrix groups
  lib/grpmat.gi
  lib/matobj.gi
  lib/matobj2.gd
  lib/matrix.gi
  lib/zmodnz.gi
Labels: topic: library

#3095 Change GroupWithGenerators to accept collections again
  lib/grp.gi
  tst/testbugfix/2018-12-06-GroupWithGenerators.tst
Labels: backport-to-4.10, kind: bug, kind: bug: unexpected error, regression

#3090 kernel: some comment reformatting
  src/code.c
  src/intrprtr.c
Labels: release notes: not needed, topic: kernel

#3082 kernel: convert tabs to spaces
  src/blister.c
  src/calls.h
  src/code.c
  src/code.h
  src/gasman.h
  src/gvars.c
  src/gvars.h
  src/hpc/aobjects.h
  src/hpc/thread.h
  src/hpc/tls.h
  src/integer.c
  src/intfuncs.c
  src/intrprtr.h
  src/io.h
  src/macfloat.c
  src/objpcgel.cc
  src/permutat.cc
  src/plist.c
  src/saveload.c
  src/set.c
  src/stats.h
  src/stringobj.c
  src/sysfiles.c
  src/system.c
  src/vars.c
  src/vec8bit.c
  src/vecffe.c
  src/vecgf2.c
Labels: release notes: not needed, topic: kernel

#3085 kernel: cleanup src/integer.{c,h}
  src/error.h
  src/integer.c
  src/integer.h
  src/libgap-api.c
  tst/testinstall/intarith.tst
Labels: release notes: not needed, topic: kernel

#3103 Two fixes for fp group homomorphisms and Improvement for Fitting free matrix group setup
  lib/fitfree.gi
  lib/ghomfp.gi
  lib/morpheus.gi
  tst/testbugfix/2018-12-11-fphomgenmix.tst
  tst/testbugfix/2018-12-11-fphomord.tst
Labels: kind: bug: unexpected error, kind: bug: wrong result

#3077 Allow appending to the command line history
  lib/cmdledit.g
Labels: kind: new feature, release notes: to be added, topic: library

#3087 Remove MinimalNormalSubgroups method using conj. classes
  lib/grp.gi
  tst/testinstall/opers/MinimalNormalSubgroups.tst
Labels: kind: enhancement, topic: performance

#3110 Workaround for error #3055 and fix for GQuotient
  lib/clashom.gi
  lib/grpfp.gi
  tst/testbugfix/2018-12-17-gquotient.tst
Labels: kind: bug: unexpected error, topic: library

#3122 Double escape backslash in make_doc.in
  doc/make_doc.in
Labels: backport-to-4.10, release notes: not needed, topic: documentation

#3131 CI: hardcode a specific Julia nightly build
  etc/ci-prepare.sh
Labels: backport-to-4.10, release notes: not needed, topic: tests

#3130 Remove compiler.g
  lib/compiler.g
  lib/read8.g
Labels: release notes: not needed, topic: gac

#3129 extend the default `BrauerTableOp` method
  lib/ctbl.gd
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3133 Enable Coveralls submissions
  README.md
  etc/ci-gather-coverage.sh
Labels: release notes: not needed, topic: tests

#3142 Fix Int() and Rat() for float nan, inf, -inf
  lib/float.gi
  src/macfloat.c
  tst/testinstall/float.tst
Labels: kind: bug

#3144 ci: enable parallel build webhook for Coveralls
  .travis.yml
Labels: release notes: not needed, topic: tests

#3149 Fix IsMonomialMatrix for compressed matrices
  lib/matrix.gi
  tst/testbugfix/2018-12-28-IsMonomialMatrix.tst
Labels: backport-to-4.10, kind: bug, topic: library
