Repository gap-system/gap, pull requests merged in 2018-04, with the labels that each got.

#2335 Update status of obsoletes, and disable some of them
  lib/obsolete.gd
  lib/obsolete.gi
Labels: library

#2340 Tweak ShowImpliedFilters some more
  lib/methwhy.g
Labels: enhancement

#2343 Fix some comparison of different types of integer compiler warnings
  src/precord.h
  src/stringobj.h
Labels: kernel, not for release notes

#2342 Move unused code from grp/classic.gi to dev/deleted-code/
  dev/deleted-code/grp-classic.g
  grp/classic.gi
Labels: library, not for release notes

#2215 Move line continuation handling to io.c
  src/io.c
  src/io.h
  src/scanner.c
  tst/testinstall/linecontinuation.tst
Labels: kernel, not for release notes

#2351 ci: print environment vars and info about HEAD commit
  etc/ci-prepare.sh
Labels: not for release notes, tests

#2352 Fix tests when 'ToolsForHomalg' is loaded
  tst/testinstall/opers/LocationFunc.tst
  tst/testinstall/varargs.tst
Labels: not for release notes, tests

#2350 io: change prompt after line continuation
  src/io.c
  tst/testinstall/linecontinuation.tst
Labels: bug, kernel

#2357 Add back WreathProductOfMatrixGroup
  dev/deleted-code/grp-classic.g
  grp/classic.gi
Labels: not for release notes, regression

#2356 Refactor parts of the scanner
  src/scanner.c
Labels: kernel, not for release notes

#2366 doc: don't recommend avoiding X
  lib/ringpoly.gd
Labels: documentation

#2359 kernel: change GetNumber to call GetIdent if needed; cleanup GetIdent a bit
  src/scanner.c
Labels: kernel, not for release notes

#2162 Move AlgExtSquareHensel to dev/deleted-code/
  dev/deleted-code/algfld.gd
  dev/deleted-code/algfld.gi
  lib/algfld.gd
  lib/algfld.gi
Labels: library, not for release notes

#2373 kernel: some cleanup in blist code
  src/blister.c
Labels: kernel, not for release notes

#2379 Add test for last2 and last3 in break loop
  tst/test-error/last-access.g
  tst/test-error/last-access.g.out
Labels: not for release notes, tests

#2382 kernel: update SyntaxError/SyntaxWarning comments
  src/scanner.c
  src/scanner.h
Labels: kernel, not for release notes

#2381 kernel: simplify scanning of large string literals
  src/gapstate.h
  src/read.c
  src/scanner.c
  src/scanner.h
Labels: kernel, not for release notes

#2396 kernel: set ref.level only if ref.type indicates it is used
  src/read.c
Labels: kernel, not for release notes

#2385 kernel: de-duplicate code reading `local` statements; make reader functions static
  src/read.c
  src/read.h
Labels: kernel, not for release notes

#2407 Remove from grpauto.tst a test which exceeds memory limits
  tst/testextra/grpauto.tst
Labels: tests

#2406 kernel: remove FuncHandlerCookieOfFunction
  src/calls.c
Labels: kernel, not for release notes

#2404 kernel: remove SET_OUTPUT, SET_PREVIOUS_OUTPUT
  lib/test.gi
  src/streams.c
Labels: kernel, not for release notes

#2403 lib: define POS_{FAMILY,FLAGS}_TYPE constants
  hpcgap/src/c_type1.c
  lib/type.g
  lib/type.gi
  lib/type1.g
  src/c_type1.c
  src/objects.c
  src/objects.h
Labels: library, not for release notes

#2405 kernel: test 'return obj' in break loop
  tst/test-error/error-return.g
  tst/test-error/error-return.g.out
Labels: not for release notes, tests

#2414 Add some more tests for src/calls.c
  tst/testinstall/kernel/calls.tst
Labels: not for release notes, tests
