Repository gap-system/gap, pull requests merged in 2018-05, with the labels that each got.

#2417 kernel: use C99 init for streams' StructInitInfo
  src/streams.c
Labels: kernel, not for release notes

#2424 Remove etc/dbgmacro.py
  etc/dbgmacro.py
Labels: not for release notes

#2423 kernel: use memcmp to compare string objects
  src/stringobj.c
Labels: kernel, not for release notes

#2428 Mark perm cycles as executed
  src/exprs.c
Labels: not for release notes

#2427 Improve and test support for custom functions
  lib/function.g
  lib/function.gi
  tst/testinstall/callfunc.tst
Labels: enhancement

#2422 Improve tracking of InstallMethod and DeclareOperation
  hpcgap/src/c_oper1.c
  lib/oper.g
  lib/oper1.g
  src/c_oper1.c
  src/read.c
Labels: enhancement

#2413 kernel: track LoopNesting in the reader, not coder
  src/code.c
  src/gapstate.h
  src/read.c
  tst/testinstall/break.tst
Labels: kernel, not for release notes

#2421 Fix iterating over an empty cartesian product
  lib/combinat.gi
  tst/testbugfix/2018-04-30-IteratorOfCartesianProduct.tst
Labels: backport-to-4.9, bug, bug: unexpected error

#2435 kernel: speed up IS_SUBSET_FLAGS
  lib/profile.g
  src/opers.c
  tst/testinstall/kernel/opers.tst
Labels: kernel, performance

#2430 kernel: move FilenameCache to io.c, use for INPUT_FILENAME
  src/code.c
  src/code.h
  src/io.c
  src/io.h
  src/profile.c
Labels: kernel, not for release notes

#2436 Update example for TraceImmediateMethods
  lib/oper.g
Labels: documentation

#2416 kernel: remove S_PARTIALFLOAT1, mark float parsing hack
  src/read.c
  src/scanner.c
  src/scanner.h
Labels: kernel, not for release notes

#2418 Overview of changes in GAP 4.9.1 release
  doc/changes/changes49.xml
  doc/changes/main.xml
Labels: backport-to-4.9, documentation

#2426 Improve InverseMatMod with integer modulus
  lib/zlattice.gi
  tst/testinstall/opers/InverseMatMod.tst
Labels: enhancement, performance

#2449 Fix crash when returning from "method not found" break loop
  src/opers.c
  tst/test-error/method-not-found.g
  tst/test-error/method-not-found.g.out
Labels: backport-to-4.9, bug: crash, regression

#2450 Change HANDLE_METHOD_NOT_FOUND to never return
  doc/ref/debug.xml
  lib/methsel2.g
  src/opers.c
  tst/test-error/bad-add.g.out
  tst/test-error/bad-array-double-1.g.out
  tst/test-error/bad-array-int-0.g.out
  tst/test-error/bad-array-string.g.out
  tst/test-error/bad-minus.g.out
  tst/test-error/func-and-proc-call-trace.g.out
  tst/test-error/method-not-found.g.out
Labels: error handling, kernel, library

#2454 Fix tests
  tst/testinstall/kernel/read.tst
Labels: not for release notes, tests

#2459 Fix regenerate_error_tests.sh to work with POSIX sed
  tst/test-error/run_gap.sh
Labels: build system, not for release notes, tests

#2458 Get rid of OBJ_LVAR_%dUP / ASS_LVAR_%dUP macros
  hpcgap/src/c_oper1.c
  hpcgap/src/c_type1.c
  src/c_oper1.c
  src/c_type1.c
  src/compiled.h
  src/compiler.c
Labels: gac, kernel, not for release notes

#1545 Change definition of IsPGroup to *not* require finiteness
  lib/grp.gd
Labels: documentation, enhancement

#2470 kernel: don't show garbage if EOF aborts string parsing
  src/scanner.c
  tst/testinstall/kernel/scanner.tst
Labels: bug, kernel

#2473 io: only increment line number for LF, not for CR
  src/io.c
  tst/test-error/line-continuation.g
  tst/test-error/line-continuation.g.out
Labels: bug, kernel, not for release notes

#2475 Teach BuildPackages.sh how to build simpcomp
  bin/BuildPackages.sh
Labels: backport-to-4.9, build system, packages

#2465 gap.sh should respect the GAP_DIR environment var
  cnf/compat/gap.sh.in
Labels: backport-to-4.9, build system

#2476 Reduce code duplication in kernel handlers for loops and sequence statements
  src/stats.c
Labels: kernel, not for release notes

#2452 Fix two bugs related to empty magmas
  lib/addmagma.gi
  lib/magma.gd
  tst/testbugfix/2018-05-09-submagma.tst
Labels: bug

#2489 Fix HPC-GAP version of TYPE_FIELDINFO_8BIT
  hpcgap/lib/vec8bit.gi
  lib/vec8bit.gi
Labels: HPC-GAP, not for release notes

#2477 Handle lists being modified by use of ~
  src/exprs.c
  tst/testinstall/tilde.tst
Labels: added to release notes, kernel

#2490 Make buildsystem regenerate libtool script
  Makefile.rules
Labels: build system, not for release notes

#2495 kernel: access TmpPPerm via ADDR_PPERM4
  src/pperm.c
Labels: kernel, not for release notes

#2500 Sync recent change to HPC-GAP
  hpcgap/lib/coll.gd
Labels: HPC-GAP, HPC-GAP unification, not for release notes
