Repository gap-system/gap, pull requests merged in 2018-11, with the labels that each got.

#2945 GAP 4.10 release notes
  doc/changes/changes-4.10.xml
  doc/changes/main.xml
Labels: release notes: not needed

#2959 clang-format: set AlwaysBreakTemplateDeclarations: true
  .clang-format
  src/collectors.cc
  src/objfgelm.cc
  src/objpcgel.cc
  src/permutat.cc
Labels: release notes: not needed, topic: kernel

#2960 Implement List(iter,func)
  lib/coll.gi
  tst/testinstall/coll.tst
Labels: kind: enhancement, topic: library

#2967 buildsys: add libgap.la to all: target
  Makefile.rules
Labels: release notes: not needed, topic: build system

#2966 Remove option to return values from break loop in many places
  src/blister.c
  src/calls.c
  src/cyclotom.c
  src/exprs.c
  src/gap.c
  src/gvars.c
  src/integer.c
  src/intfuncs.c
  src/listfunc.c
  src/macfloat.c
  src/modules.c
  src/permutat.cc
  src/plist.c
  src/set.c
  src/stats.c
  src/streams.c
  src/stringobj.c
  src/sysfiles.c
  src/vars.c
Labels: release notes: to be added, topic: kernel

#2968 kernel: add MakeObjInt helper
  src/integer.c
  src/integer.h
Labels: release notes: not needed, topic: kernel

#2978 kernel: reformat src/vec{8bit,gf2}.{c,h}
  src/vec8bit.c
  src/vec8bit.h
  src/vecgf2.c
  src/vecgf2.h
Labels: release notes: not needed, topic: kernel

#2983 Speed up 2018-05-24-IntermediateSubgroups.tst
  tst/testbugfix/2018-05-24-IntermediateSubgroups.tst
Labels: release notes: not needed, topic: tests

#2962 kernel: unify FORCE_SWITCH_OBJ and SWITCH_OBJ
  src/objects.c
  tst/testinstall/switch.tst
  tst/testinstall/switch_obj.tst
Labels: release notes: not needed, topic: kernel

#2969 Fix task scanning for the Julia GC
  src/julia_gc.c
Labels: backport-to-4.10, release notes: to be added, topic: kernel

#2988 Add some functions to libgap API
  .gitignore
  src/libgap-api.c
  src/libgap-api.h
  tst/testlibgap/basic.c
  tst/testlibgap/common.c
  tst/testlibgap/common.h
  tst/testlibgap/wscreate.c
Labels: topic: kernel

#3005 buildsys: disable 'make install', as people keep ignoring the warning
  Makefile.rules
Labels: backport-to-4.10, release notes: to be added, topic: build system

#2998 Add some integer related functions to libgap API
  src/libgap-api.c
  src/libgap-api.h
Labels: libgap, topic: kernel

#2989 Add new IsSimpleSemigroup method in lib/reesmat.gi
  lib/reesmat.gi
  tst/testinstall/reesmat.tst
Labels: release notes: not needed

#3002 kernel: some ErrorReturn{Obj,Void} calls by ErrorMayQuit
  src/gvars.c
  src/intfuncs.c
  src/modules.c
  src/precord.c
  src/vars.c
  tst/testspecial/backtrace.g.out
  tst/testspecial/bad-array-undef-0.g.out
  tst/testspecial/bad-array-undef-1.g.out
Labels: release notes: not needed, topic: kernel

#2993 Add quick nonsolvability test before trying permutation Pcgs
  doc/tut/group.xml
  lib/ctbl.gd
  lib/grp.gd
  lib/grpperm.gi
  lib/morpheus.gd
  lib/teaching.g
Labels: release notes: not needed, topic: performance

#3012 buildsys: fix testlibgap
  Makefile.rules
Labels: libgap, topic: build system

#3013 Fix some errors which didn't trigger a break loop anymore
  src/error.c
Labels: backport-to-4.10, kind: bug, release notes: to be added, topic: kernel

#3018 Fix writing past end of bag in collectors.cc
  src/collectors.cc
  tst/testbugfix/2018-11-16-ConjugacyClasses.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: to be added

#3017 Fix writing past end of bag in objscoll-impl
  src/objscoll-impl.h
  tst/testbugfix/2018-11-16-ConjugacyClasses.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: to be added

#2851 Merge PRINT_OR_APPEND_TO and its ..._STREAM variant
  src/streams.c
Labels: gapdays2018-fall, release notes: not needed, topic: kernel

#3020 Fix `ci-gather-coverage.sh`
  etc/ci-gather-coverage.sh
Labels: release notes: not needed, topic: tests

#3007 Added GAP_ValueMacFloat to libgap-api
  src/libgap-api.c
  src/libgap-api.h
Labels: libgap, release notes: to be added, topic: kernel

#3023 kernel: add MakeImmutableNoRecurse
  src/blister.c
  src/intfuncs.c
  src/objects.h
  src/plist.c
  src/precord.c
  src/range.c
  src/stringobj.c
  src/stringobj.h
  src/trans.c
Labels: release notes: not needed, topic: kernel

#3022 gac: test posobj/combj access in compiled code
  tst/test-compile/basics.g
  tst/test-compile/basics.g.dynamic.c
  tst/test-compile/basics.g.out
  tst/test-compile/basics.g.static.c
Labels: release notes: not needed, topic: gac, topic: tests

#3000 kernel: change argument validation for OBJ_{SET,MAP} to use RequireArgumentCondition
  src/objset.c
  tst/testinstall/objmap.tst
  tst/testinstall/objset.tst
Labels: release notes: not needed, topic: kernel

#3029 Travis: reorder jobs a bit, tweak comments
  .travis.yml
Labels: release notes: not needed, topic: tests

#3031 Add ConjugacyClassesForSolvableGroup
  lib/clas.gd
  lib/clas.gi
  lib/clashom.gi
Labels: topic: library, topic: performance

#3032 Fix marking 'fi;' as executed in profiles
  src/intrprtr.c
Labels: backport-to-4.10, topic: kernel

#3041 Fix rewriteToFile handling with #@if
  lib/test.gi
  tst/testinstall/restrictedperm.tst
Labels: release notes: not needed, topic: kernel

#3042 buildsys: always generate sysinfo.gap
  Makefile.rules
Labels: backport-to-4.10, kind: bug, topic: build system

#3047 kernel: remove some `return`s after ErrorQuit
  src/streams.c
Labels: release notes: not needed

#3051 Revert "test: shorten domain.tst to accommodate Semigroups"
  tst/testinstall/domain.tst
Labels: release notes: not needed, topic: tests

#3053 Preserve more properties in DirectProduct
  lib/gprd.gi
  tst/testinstall/gprd.tst
Labels: kind: request for comments, topic: library

#3059 Decouple funcs.c from internals of stats.c
  src/funcs.c
  src/stats.c
  src/stats.h
Labels: release notes: not needed, topic: kernel

#3064 Remove some obsolete code from compiler.c
  src/compiler.c
Labels: kind: bug, release notes: not needed, topic: gac

#3066 kernel: use RequireArgument some more
  src/c_oper1.c
  src/c_type1.c
  src/compiler.c
  src/hpc/c_oper1.c
  src/hpc/c_type1.c
  src/intrprtr.c
  src/stats.c
  tst/test-compile/and_filter.g.dynamic.c
  tst/test-compile/and_filter.g.static.c
  tst/testinstall/boolean.tst
  tst/testinstall/gprd.tst
  tst/testinstall/interpreter.tst
  tst/testinstall/kernel/intrprtr.tst
  tst/testinstall/kernel/stats.tst
  tst/testspecial/backtrace.g.out
Labels: release notes: not needed, topic: kernel

#3061 Merge hpcgap/tst/ into tst/ using the #@if syntax
  hpcgap/tst/testinstall/atomic_basic.tst
  hpcgap/tst/testinstall/flush.tst
  hpcgap/tst/testinstall/immutable.tst
  tst/testinstall/hpc/atomic_basic.tst
  tst/testinstall/hpc/atomic_compare.tst
  tst/testinstall/hpc/atomic_list.tst
  tst/testinstall/hpc/atomic_list_hpc.tst
  tst/testinstall/hpc/channels.tst
  tst/testinstall/hpc/comprvec.tst
  tst/testinstall/hpc/demo.tst
  tst/testinstall/hpc/fix-coverage.tst
  tst/testinstall/hpc/queue.tst
  tst/testinstall/hpc/serialize.tst
  tst/testinstall/hpc/stdtasks.tst
  tst/teststandard/hpc/alist.tst
Labels: release notes: not needed, topic: HPC-GAP, topic: HPC-GAP unification, topic: tests

#3071 kernel: fix string copying logic
  src/stringobj.c
Labels: kind: bug, topic: kernel

#2628 Syntax Trees
  Makefile.rules
  doc/ref/language.xml
  doc/ref/makedocreldata.g
  lib/read8.g
  lib/syntaxtree.gd
  lib/syntaxtree.gi
  src/modules-builtin.c
  src/syntaxtree.c
  src/syntaxtree.h
  tst/testinstall/syntaxtree.tst
Labels: kind: new feature, release notes: to be added, topic: GAP language, topic: kernel, topic: parser

#3073 ci: fast fail AppVeyor and Travis outdated jobs
  .appveyor.yml
  .travis.yml
  etc/ci-prepare.sh
  etc/travis_fastfail.sh
Labels: release notes: not needed, topic: infrastructure

#3074 Fix two small issues in syntaxtree.c
  src/syntaxtree.c
Labels: kind: bug, release notes: not needed, topic: GAP language, topic: kernel
