Repository gap-system/gap, pull requests merged in 2018-08, with the labels that each got.

#2674 kernel: improve error handling in SaveWorkspace
  src/saveload.c
  tst/testbugfix/2018-08-01-SaveWorkspace.tst
Labels: bug, release notes: to be added

#2092 Alternate GC hooking into Julia GC.
  GNUmakefile.in
  Makefile.rules
  configure.ac
  src/gasman.h
  src/julia_gc.c
  src/weakptr.c
Labels: kernel

#2678 Add back SortingPerm optimisation
  lib/list.gi
Labels: kernel, release notes: not needed

#2680 Balance \> and \< in semigroups ViewString methods
  lib/semigrp.gi
Labels: release notes: not needed

#2686 Improve bicoset code
  lib/csetgrp.gd
  lib/csetgrp.gi
  tst/testbugfix/2018-08-08-bicosets.tst
Labels: enhancement, release notes: not needed, tests

#2689 kernel: fix LogFFE on 32 bit systems
  src/finfield.c
  tst/testbugfix/2011-01-16-t00231.tst
  tst/testinstall/ffe.tst
Labels: bug, bug: wrong result, kernel, release notes: to be added

#2657 Immutable entries of mutable attributes of char. tables
  lib/ctbl.gd
  lib/ctbl.gi
  lib/ctblfuns.gi
  lib/ctblgrp.gi
  lib/ctblmaps.gd
  lib/ctblmaps.gi
  lib/ctblsymm.gi
  tst/testinstall/ctbl.tst
Labels: release notes: to be added

#2670 lib: remove unused CheckAuto()
  lib/grppcaut.gi
Labels: library

#2691 kernel: fix GAP_STATIC_ASSERT fallback code
  src/debug.h
Labels: bug, kernel

#2694 kernel: remove some unused blist/plist code
  src/blister.c
  src/blister.h
  src/debug.c
  src/plist.h
Labels: kernel, release notes: not needed

#2692 Improve rationals code a bit and add tests
  src/rational.c
  src/rational.h
  tst/testinstall/rationals.tst
Labels: kernel, release notes: not needed, tests

#2693 kernel: simplify bool.c and add test cases
  src/bool.c
  tst/testinstall/kernel/bool.tst
Labels: kernel, release notes: not needed, tests

#2690 Improve FFE code a bit and add tests
  hpcgap/lib/ffe.gi
  hpcgap/lib/ffeconway.gi
  lib/ffe.gi
  lib/ffeconway.gi
  src/finfield.c
  tst/testinstall/ffe.tst
Labels: enhancement, release notes: not needed, tests

#2681 addressing issue #2646: Unused functions in ctbl.gi
  doc/ref/ctbl.xml
  lib/ctbl.gd
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: bug, documentation, enhancement, library, release notes: to be added

#2698 buildsys: remove some configure checks
  configure.ac
Labels: build system, release notes: not needed

#2704 buildsys: simplify C compilation build rule
  Makefile.rules
  cnf/gac.in
Labels: build system, release notes: not needed

#2699 Improve docs for PCentralSeries, PRump, PCore
  dev/manualchapters
  lib/ctbl.gi
  lib/grp.gd
  lib/grp.gi
Labels: documentation, release notes: not needed, tests

#2707 Export READ_ALL_COMMANDS via header file
  src/streams.c
  src/streams.h
Labels: kernel, release notes: not needed

#2706 Introduce SetExtraMarkFuncBags
  src/gasman.c
  src/gasman.h
Labels: kernel, release notes: not needed

#2708 Added file dev/TODO_matobj.txt
  dev/TODO_matobj.txt
Labels: release notes: not needed

#2717 Replace manual loops with memcpys
  src/objects.c
  src/stringobj.c
Labels: kernel, release notes: not needed

#2696 kernel: unify forwarding pointer in list copying code
  src/blister.c
  src/objects.c
  src/plist.c
  src/precord.c
  src/range.c
  src/weakptr.c
Labels: kernel, release notes: not needed

#2712 kernel: reduce ALWAYS_INLINE to inline in debug mode
  src/calls.c
  src/opers.c
  src/stats.c
  src/system.h
Labels: release notes: not needed, topic: kernel

#2719 kernel: get rid of STATE(IntrResult), update comments
  src/gap.c
  src/gapstate.h
  src/intrprtr.c
  src/intrprtr.h
  src/read.c
Labels: release notes: not needed, topic: kernel

#2713 kernel: fix `for x in iter do` optimization
  src/stats.c
Labels: release notes: not needed, topic: kernel

#2720 Encode if we have readline in workspaces
  src/saveload.c
Labels: kind: bug, kind: bug: crash, release notes: to be added, topic: kernel

#2718 Improve valgrind support
  src/gasman.c
  src/gasman.h
Labels: release notes: to be added, topic: kernel

#2716 Stop out-of-bounds read, and ensure all bytes are used, in FuncIntRandomMT
  src/intfuncs.c
  tst/testinstall/random.tst
Labels: release notes: to be added, topic: kernel

#2722 kernel: rename TRY_READ -> TRY_IF_NO_ERROR
  src/gap.c
  src/hpc/threadapi.c
  src/read.c
  src/read.h
  src/streams.c
Labels: release notes: not needed, topic: kernel

#2731 kernel: use SET_LEN_BLIST more
  src/blister.c
Labels: release notes: not needed, topic: kernel

#2735 kernel: reduce exports of ariths.{c,h}
  src/ariths.c
  src/ariths.h
  src/opers.c
Labels: release notes: not needed, topic: kernel

#2736 kernel: add two missing CHANGED_BAG calls
  src/objcftl.c
Labels: release notes: to be added, topic: kernel

#2715 kernel: add more tests, cleanup code
  src/calls.h
  src/intrprtr.c
  src/range.c
  src/set.c
  src/stats.c
  tst/testinstall/interpreter.tst
  tst/testinstall/kernel/exprs.tst
  tst/testinstall/kernel/intrprtr.tst
  tst/testinstall/kernel/range.tst
  tst/testinstall/kernel/set.tst
  tst/testinstall/kernel/stats.tst
  tst/testinstall/range.tst
  tst/testspecial/mem-overflow.g
  tst/testspecial/mem-overflow.g.out
Labels: release notes: not needed, topic: kernel, topic: tests

#2742 Fix CanEasilyDetermineCanonicalRepresentativeExternalSet
  lib/oprt.gd
Labels: kind: bug, topic: library

#2740 Replace macros with functions in records.h
  src/records.h
Labels: release notes: not needed, topic: kernel

#2751 kernel: move PrintPrecedence to module state
  src/exprs.c
Labels: kind: bug, topic: HPC-GAP, topic: kernel

#2702 Add GAP kernel API (aka libgap)
  .gitignore
  .travis.yml
  Makefile.rules
  etc/ci.sh
  lib/streams.gi
  src/libgap-api.c
  src/libgap-api.h
  tst/testlibgap/basic.c
  tst/testlibgap/basic.expect
Labels: kind: enhancement, release notes: to be added, topic: build system

#2762 Add missing { } around macro
  src/gap.c
Labels: release notes: not needed, topic: kernel

#2752 kernel: rename IS_MUTABLE_PLIST to IS_PLIST_MUTABLE
  src/debug.c
  src/listfunc.c
  src/permutat.c
  src/plist.c
  src/plist.h
  src/pperm.c
  src/trans.c
  src/vecgf2.c
Labels: release notes: not needed, topic: kernel

#2748 kernel: restrict T_ATOMIC to HPC-GAP
  src/code.h
  src/stats.c
Labels: release notes: not needed, topic: HPC-GAP, topic: kernel

#2763 kernel: add SKIP_IF_{RETURNING,IGNORING} to interpreter
  src/intrprtr.c
Labels: release notes: not needed, topic: kernel

#2764 Remove superflous libgap.so target
  Makefile.rules
Labels: release notes: not needed, topic: build system
