Repository gap-system/gap, pull requests merged in 2018-03, with the labels that each got.

#2214 Rename GET_CHAR to GET_NEXT_CHAR and add a return value to it; some more scanner+io refactoring
  src/io.c
  src/io.h
  src/scanner.c
Labels: kernel, not for release notes

#2207 Refactor ReadCallVarAss and ReadReferenceModifiers
  src/read.c
Labels: kernel, not for release notes

#2227 travis: turn off slack notification for PRs
  .travis.yml
Labels: not for release notes, tests

#2228 Fix crash when parsing an Assert or Info in an ignored else or elif
  src/intrprtr.c
  tst/testbugfix/2018-03-01-if-elif-crash.tst
Labels: bug, bug: crash, not for release notes, regression

#2224 Improve ShowImpliedFilters
  lib/methwhy.g
Labels: enhancement

#2235 Tweak tst/testbugfix/2018-02-21-int-mul-pow.tst
  tst/testbugfix/2018-02-21-int-mul-pow.tst
Labels: not for release notes

#2231 Add basic test for deep thought code
  tst/testinstall/dt.tst
Labels: not for release notes, tests

#2057 Ongoing improvements that do not need to make 4.9
  doc/ref/groups.xml
  doc/ref/grpfp.xml
  lib/claspcgs.gi
  lib/ctbl.gi
  lib/ctblfuns.gi
  lib/ctblmaps.gi
  lib/ctblmono.gi
  lib/ctblpope.gi
  lib/cyclotom.gi
  lib/ffe.gi
  lib/ffeconway.gi
  lib/fldabnum.gi
  lib/ghomfp.gd
  lib/ghomfp.gi
  lib/gpfpiso.gi
  lib/gpprmsya.gi
  lib/grp.gd
  lib/grp.gi
  lib/grpffmat.gi
  lib/grpfp.gd
  lib/grpfp.gi
  lib/grplatt.gd
  lib/grplatt.gi
  lib/grpnice.gi
  lib/grppcfp.gi
  lib/grpperm.gi
  lib/grpprmcs.gi
  lib/integer.gi
  lib/matrix.gi
  lib/morpheus.gd
  lib/morpheus.gi
  lib/numtheor.gi
  lib/oprtperm.gi
  lib/pcgs.gi
  lib/pcgspcg.gi
  lib/pcgsperm.gi
  lib/randiso.gi
  lib/randiso2.gi
  lib/string.gi
  lib/tietze.gi
  tst/testinstall/semigrp.tst
Labels: enhancement, new feature, performance

#2223 Implement PositionsBound.
  doc/ref/lists.xml
  lib/list.gd
  lib/list.gi
Labels: enhancement

#2119 Adding loading packages to testpackages Travis CI test
  etc/ci.sh
Labels: not for release notes, packages, tests

#2250 Add tests for interpreter edge cases and deep thought
  src/intrprtr.c
  src/streams.c
  tst/testinstall/boolean.tst
  tst/testinstall/dt.tst
  tst/testinstall/interpreter.tst
  tst/testinstall/list.tst
  tst/testinstall/perm.tst
Labels: not for release notes, tests

#2225 lib: improve LocationFunc for kernel funcs
  lib/function.g
  tst/testinstall/opers/LocationFunc.tst
Labels: enhancement

#2251 hpcgap: sync various recent changes
  hpcgap/lib/ffe.gi
  hpcgap/lib/ffeconway.gi
  hpcgap/lib/fldabnum.gi
  hpcgap/lib/integer.gi
  hpcgap/lib/pcgsperm.gi
  hpcgap/lib/polyrat.gi
  hpcgap/lib/primality.gi
  hpcgap/lib/ratfun.gi
Labels: HPC-GAP unification, not for release notes

#2202 hpcgap: get rid of backquote alias for MakeImmutable
  hpcgap/lib/cmdleditx.g
  hpcgap/lib/fldabnum.gi
  hpcgap/lib/package.gi
  hpcgap/lib/variable.g
  hpcgap/lib/wordrep.gi
  src/read.c
  src/scanner.c
  src/scanner.h
Labels: HPC-GAP, HPC-GAP unification

#2260 Fix TriangulizedMat([])
  lib/matrix.gi
  tst/testinstall/opers/TriangulizedMat.tst
Labels: backport-to-4.9, enhancement

#2255 Remove special treatment of 'carat' package (backport to 4.9!)
  bin/BuildPackages.sh
  etc/ci.sh
Labels: backport-to-4.9, not for release notes, tests

#2270 Tweak README (backport to stable-4.9)
  README.md
Labels: backport-to-4.9, documentation

#2243 Omit tester filters from `ShowImpliedFilters` output
  lib/methwhy.g
Labels: enhancement

#2268 Handle spaces in filenames of gziped filenames
  src/profile.c
  src/sysfiles.c
Labels: enhancement

#2244 InstallImmediateMethod: make rank optional, tweak docs
  hpcgap/src/c_oper1.c
  lib/oper.g
  lib/oper1.g
  src/c_oper1.c
Labels: enhancement

#2259 Make `break`, `continue`, and `return` interruptible
  src/code.h
Labels: backport-to-4.9, bug

#2275 Fix bug in IsFinitelyGeneratedGroup method
  lib/grp.gi
  tst/testbugfix/2018-03-21-IsFinitelyGeneratedGroup.tst
Labels: bug, bug: wrong result, library

#2278 tests: add more package related tests
  tst/fakepkg/PackageInfo.g
  tst/fakepkg/README.md
  tst/fakepkg/doc/chap0.html
  tst/fakepkg/doc/manual.pdf
  tst/fakepkg/doc/manual.six
  tst/fakepkg/gap/fakepkg.gd
  tst/fakepkg/gap/fakepkg.gi
  tst/fakepkg/init.g
  tst/fakepkg/read.g
  tst/fakepkg/tst/testall.g
  tst/testinstall/package.tst
Labels: not for release notes, tests

#2284 Cleanup lib/compiler.g
  lib/compiler.g
Labels: not for release notes

#2283 Add minimal test for AutomGrpSR
  tst/teststandard/opers/AutomorphismGroup.tst
Labels: not for release notes, tests

#2280 Fix incorrect IsFinitelyGeneratedMonoid method
  lib/monofree.gi
  lib/monoid.gi
Labels: bug, bug: wrong result, library

#2273 Fix TypeOfOperation for setters of and-filters
  lib/type.gi
  tst/testinstall/type.tst
Labels: bug

#2288 Fix tst/testinstall/package.tst when banners are off
  tst/fakepkg/PackageInfo.g
  tst/testinstall/package.tst
Labels: not for release notes, tests

#2279 Tweak CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, not for release notes

#2290 Travis: remove HPC-GAP 32bit build
  .travis.yml
Labels: HPC-GAP, not for release notes, tests

#2291 Fix Gcd(f,g) with f,g multivariate rationals polynomials
  hpcgap/lib/ratfun.gi
  lib/ratfun.gi
  tst/testinstall/ratfun.tst
Labels: bug, not for release notes, regression, tests

#2241 Add HPCGAP and ADDGUARDS2 to sysinfo.gap
  Makefile.rules
Labels: build system, enhancement, not for release notes

#2189 tests: also extract and test tutorial examples on Travis
  tst/extractmanuals.g
Labels: tests

#2302 Avoid loading FactInt in tests
  tst/testinstall/integer.tst
Labels: not for release notes, tests

#2300 Add FileId to function calls in profiling
  src/profile.c
Labels: enhancement, not for release notes

#2304 Travis: reset CFLAGS and LDFLAGS when building packages
  etc/ci-prepare.sh
Labels: not for release notes, tests

#2310 Add tests for compressed mats & vecs
  tst/testinstall/vecmat.tst
Labels: not for release notes, tests

#2315 Prevent creation of groups of floats
  lib/float.gi
  tst/testbugfix/2018-03-27-float-group.tst
Labels: bug

#2313 Avoid GC problem in Cyclotomic
  src/cyclotom.c
Labels: backport-to-4.9, bug: crash, not for release notes

#2320 Avoid GC problem in PowPerm2Int/PowPerm4Int
  src/permutat.c
Labels: backport-to-4.9, bug: crash, not for release notes

#2321 trans: resolve GC bug Issue 2319
  src/trans.c
Labels: backport-to-4.9, bug, bug: crash

#2314 Remove code that was commented out for a looong time
  lib/fldabnum.gi
  lib/gaussian.gi
  lib/numtheor.gi
  lib/rational.gi
Labels: library, not for release notes

#2322 travis: exclude packages from coverage collection
  etc/ci.sh
Labels: not for release notes, tests

#2311 Not all finitely generated magmas are groups (alternative to PR #2276)
  lib/magma.gi
  tst/testbugfix/2018-03-21-MagmaWithInversesByGenerators.tst
Labels: bug, bug: wrong result, library

#2326 SimpleGroup: some fixes; better input validation; tests
  grp/simple.gi
  tst/testinstall/opers/SimpleGroup.tst
  tst/teststandard/simplegrpit.tst
Labels: bug, bug: wrong result, tests

#2328 Fix QuaternionGroup for non-abelian number fields, tests
  grp/basicmat.gi
  tst/testinstall/grp/basic.tst
  tst/testinstall/grp/classic-G.tst
Labels: bug, not for release notes, tests

#2330 Use --enable-large-config for Boehm GC
  Makefile.rules
Labels: HPC-GAP, build system, not for release notes
