Repository gap-system/gap, pull requests merged in 2019-10, with the labels that each got.

#3668 support several package instances with same version
  lib/package.gd
  lib/package.gi
Labels: kind: enhancement, release notes: to be added, topic: packages

#3682 Update Travis settings
  .travis.yml
Labels: release notes: not needed, topic: ci

#3689 Fix BlistList for two ranges
  src/blister.c
  tst/testinstall/kernel/blister.tst
Labels: backport-to-4.11, kind: bug, kind: bug: wrong result, release notes: to be added, topic: kernel

#3688 kernel: remove use of PLAIN_LIST in FuncUNITE_BLIST_LIST
  src/blister.c
  tst/testinstall/kernel/blister.tst
Labels: release notes: not needed, topic: kernel

#3685 kernel: add PLAIN_LIST_COPY helper
  src/error.c
  src/lists.c
  src/lists.h
  src/trans.cc
Labels: release notes: not needed, topic: kernel

#3691 kernel: tweak error messages to say "an object"
  src/error.c
  tst/testbugfix/2013-03-12-t00285.tst
  tst/testinstall/bitfields.tst
  tst/testinstall/listindex.tst
  tst/testinstall/matblock.tst
  tst/testinstall/weakptr-badargs.tst
Labels: release notes: not needed, topic: kernel

#3692 kernel: new TNAMs for {component,positional,data} objects
  src/objects.c
  tst/testbugfix/2013-03-12-t00285.tst
  tst/testinstall/hpc/serialize.tst
  tst/testinstall/kernel/lists.tst
  tst/testinstall/matblock.tst
Labels: release notes: not needed, topic: kernel

#3694 Deprecate undocumented extra arguments for DeclareGlobalFunction and InstallGlobalFunction
  lib/dict.gd
  lib/grp.gd
  lib/grpnames.gd
  lib/grpperm.gd
  lib/lierep.gd
  lib/list.gd
  lib/matobj2.gd
  lib/oper.g
  lib/tuples.gd
Labels: kind: quirk, release notes: to be added, topic: library

#3686 Add descriptive message to declared but not defined global functions
  src/opers.c
  tst/testinstall/declarefunction.tst
Labels: kind: enhancement

#3697 kernel: add GetPositiveListEntry helper
  src/trans.cc
  tst/testinstall/trans.tst
Labels: release notes: not needed, topic: kernel

#3690 Fix NullspaceModQ and renamed it to NullspaceModN
  doc/ref/matrix.xml
  lib/matrix.gd
  lib/matrix.gi
Labels: backport-to-4.11, kind: bug, kind: bug: wrong result, release notes: to be added

#3700 Increment kernel major version
  configure.ac
Labels: release notes: not needed, topic: kernel

#3695 Fix issue with test outputs which do not end with a newline when using the rewriteToFile option of Test
  lib/test.gi
Labels: kind: bug: wrong result, release notes: to be added

#3705 kernel / HPC-GAP: refactor traversal.c
  src/hpc/traverse.c
Labels: release notes: not needed, topic: HPC-GAP, topic: kernel

#3704 Two workarounds for old issues.
  benchmark/grpauto/permiso.tst
  lib/clashom.gi
Labels: regression, release notes: not needed, topic: library

#3706 kernel: change TNAM for weak pointer objects
  src/weakptr.c
Labels: backport-to-4.11, release notes: not needed, topic: kernel

#3683 Add parts for GAP package build systems
  etc/Makefile.gappkg
Labels: backport-to-4.11, kind: discussion, topic: build system, topic: packages

#3710 kernel: include hpc/guards.h in compiled.h
  src/compiled.h
Labels: backport-to-4.11, release notes: not needed, topic: HPC-GAP, topic: kernel

#3711 Adjust TestPackage to return info about test result
  lib/test.gi
Labels: backport-to-4.11, topic: library, topic: tests

#3712 README.md: link Travis build status button to Travis "build history" page
  README.md
Labels: priority: low, release notes: not needed, topic: ci

#3714 buildsys: update config.guess and config.sub to latest
  cnf/config.guess
  cnf/config.sub
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3716 kernel: simplify SET_TYPE_OBJ, remove SetTypeObjFuncs
  src/hpc/aobjects.c
  src/objects.c
  src/objects.h
  src/plist.c
  src/precord.c
Labels: release notes: not needed, topic: kernel

#3717 Revert "buildsys: use the C++ compiler for linking"
  .appveyor.yml
  .travis.yml
  Makefile.rules
Labels: backport-to-4.11, topic: build system, topic: julia
