Repository gap-system/gap, pull requests merged in 2019-01, with the labels that each got.

#3156 Optimize BlistList and UniteBlistList for empty `sub` list
  src/blister.c
Labels: release notes: not needed, topic: kernel, topic: performance

#3125 kernel: simplify code in FuncWITH_(HIDDEN_)IMPS_FLAGS
  src/opers.c
Labels: release notes: not needed, topic: kernel

#3150 Use NrRows, NrCols, {One,Zero}OfBaseDomain in more places
  hpcgap/lib/vecmat.gi
  lib/combinat.gi
  lib/matint.gi
  lib/matrix.gi
  lib/vecmat.gi
Labels: release notes: not needed, topic: library

#3151 kernel: validate {CHANGED_,SET_,}METHODS_OPERATION args
  src/opers.c
  src/opers.h
  tst/testinstall/kernel/opers.tst
Labels: topic: kernel

#3153 Avoid fluctuations in stdtasks tests
  tst/testinstall/hpc/stdtasks.tst
Labels: release notes: not needed, topic: HPC-GAP, topic: tests

#3137 Some more finite field tweaks from from PR #2997
  src/finfield.c
  src/finfield.h
  tst/testbugfix/2016-12-20-t00349.tst
  tst/testbugfix/2017-08-07-FFE-bad-char.tst
  tst/testinstall/ffe.tst
Labels: release notes: not needed, topic: kernel

#3163 travis: use Julia 1.1.0-rc1 for tests
  etc/ci-prepare.sh
Labels: backport-to-4.10, release notes: not needed, topic: tests

#3160 Fix HasAvailableBytes for gzipped files
  src/sysfiles.c
  tst/testinstall/files/testdata.gz
  tst/testinstall/streams.tst
Labels: backport-to-4.10, release notes: not needed, topic: kernel

#3102 prevent infinite recursions in echoandcheck SyWriteandcheck
  src/sysfiles.c
Labels: backport-to-4.10

#3154 FIX: Fitting free data use in clashom
  lib/clashom.gi
  lib/fitfree.gi
  lib/grp.gd
  lib/matrix.gi
  tst/testbugfix/2018-12-30-clashom.tst
Labels: backport-to-4.10, kind: bug: unexpected error

#3162 kernel: add ScanPermCycle helper
  src/exprs.c
  src/intrprtr.c
  src/permutat.cc
  src/permutat.h
Labels: release notes: not needed, topic: kernel

#3080 Add HallSubgroup fallback method
  lib/grp.gi
  tst/testinstall/opers/HallSubgroup.tst
Labels: kind: enhancement, topic: library

#3167 in configure, run Julia without `startup.jl`
  configure.ac
Labels: backport-to-4.10, release notes: not needed, topic: build system

#3161 kernel: add RetypeBagSM, RetypeBagSMIfWritable (step towards getting rid of IMMUTABLE)
  src/bags.c
  src/blister.c
  src/gasman.h
  src/listoper.c
  src/permutat.cc
  src/plist.c
  src/pperm.cc
  src/range.c
  src/set.c
  src/stringobj.c
  src/trans.cc
  src/vec8bit.c
  src/vecffe.c
  src/vecgf2.c
Labels: release notes: not needed, topic: kernel

#3172 ci: 'hide' julia inside extern/
  etc/ci-prepare.sh
Labels: release notes: not needed, topic: tests

#3173 Exclude pkg and extern from codecov coverage gathering script
  .appveyor.yml
  .travis.yml
  etc/ci-run-codecov.sh
Labels: release notes: not needed, topic: tests

#3174 tests: fix an HPC-GAP test which could sometimes fail
  tst/testinstall/hpc/stdtasks.tst
Labels: release notes: not needed, topic: tests

#3175 kernel: add NewFunctionBody() helper
  src/c_oper1.c
  src/c_type1.c
  src/code.c
  src/code.h
  src/compiler.c
  src/hpc/c_oper1.c
  src/hpc/c_type1.c
  src/modules.c
  src/vars.c
  tst/test-compile/and_filter.g.dynamic.c
  tst/test-compile/and_filter.g.static.c
  tst/test-compile/assert.g.dynamic.c
  tst/test-compile/assert.g.static.c
  tst/test-compile/basics.g.dynamic.c
  tst/test-compile/basics.g.static.c
  tst/test-compile/function_types.g.dynamic.c
  tst/test-compile/function_types.g.static.c
  tst/test-compile/info.g.dynamic.c
  tst/test-compile/info.g.static.c
  tst/test-compile/plus.g.dynamic.c
  tst/test-compile/plus.g.static.c
  tst/test-compile/print_various.g.dynamic.c
  tst/test-compile/print_various.g.static.c
  tst/test-compile/ranges.g.dynamic.c
  tst/test-compile/ranges.g.static.c
Labels: release notes: not needed, topic: kernel

#3170 kernel: avoid hack in collector to extract word length
  src/collectors.cc
Labels: release notes: not needed, topic: kernel

#3181 Switch Julia builds to 1.1.0-rc2
  etc/ci-prepare.sh
Labels: release notes: not needed, topic: ci

#3138 Add gcov support for coveralls.io as well
  .appveyor.yml
  .travis.yml
  etc/ci-coveralls-merge.py
  etc/ci-gather-coverage.sh
  etc/ci-gcovr-coverage.py
Labels: release notes: not needed, topic: ci

#3190 buildsys: only use -Wextra-semi for C++ code
  cnf/m4/ax_compiler_flags_cflags.m4
Labels: regression, release notes: not needed, topic: build system

#3191 kernel: fix GC crash in PushValue()
  src/code.c
Labels: kind: bug, kind: bug: crash, regression, release notes: not needed, topic: kernel

#3186 kernel: tweak transformations & partial perms code
  src/listfunc.c
  src/trans.cc
  src/trans.h
Labels: release notes: not needed, topic: kernel

#3185 Make (Un)HideGlobalVariables obsolete
  lib/global.gd
  lib/global.gi
  lib/obsolete.gd
  lib/obsolete.gi
Labels: release notes: to be added, topic: library

#3194 kernel: move most func decls from dt.h to dt.c
  src/dt.c
  src/dt.h
Labels: release notes: not needed, topic: kernel

#3192 Catch some corner cases for trivial group
  lib/gpprmsya.gi
  lib/grplatt.gi
  tst/testbugfix/2019-01-18-grplatt.tst
Labels: kind: bug, kind: bug: unexpected error

#3193 kernel: fix bad prototypes for zero arg funcs
  src/error.h
  src/gapstate.h
  src/objset.h
  src/stats.h
Labels: release notes: not needed, topic: kernel

#3195 kernel: remove some private stuff from header files
  src/collectors.h
  src/hpc/thread.c
  src/hpc/thread.h
  src/hpc/threadapi.c
  src/hpc/threadapi.h
  src/lists.h
  src/opers.c
  src/opers.h
Labels: release notes: not needed, topic: kernel

#3199 Julia GC: fix stack marking
  src/julia_gc.c
Labels: kind: bug: crash, topic: julia, topic: kernel

#3208 Add missing CHANGED_BAG in PushValue
  src/code.c
Labels: kind: bug, kind: bug: crash, regression, release notes: not needed, topic: kernel

#3213 Switch Julia builds to 1.1.0
  etc/ci-prepare.sh
Labels: backport-to-4.10, release notes: not needed, topic: ci, topic: julia

#3201 kernel: move ThreadedInterpreter to threadapi.c
  src/gap.c
  src/hpc/threadapi.c
  src/hpc/threadapi.h
Labels: release notes: not needed, topic: kernel

#3211 kernel: remove unused NewFunctionCT
  doc/dev/kernel.xml
  src/calls.c
  src/calls.h
Labels: release notes: not needed, topic: kernel

#3096 Prototype for GAP_Enter/Leave macros
  src/gasman.c
  src/gasman.h
  src/libgap-api.c
  src/libgap-api.h
  tst/testlibgap/common.c
Labels: topic: kernel, topic: libgap

#3220 kernel: fix wrong result bugs in partial perms code
  src/pperm.cc
  tst/testinstall/pperm.tst
Labels: backport-to-4.10, kind: bug, kind: bug: wrong result, topic: kernel

#3223 kernel: fix another crash caused by function body values
  src/code.c
Labels: kind: bug, kind: bug: crash, regression, release notes: not needed, topic: kernel

#3218 kernel: add IS_CYC helper
  src/cyclotom.c
  src/cyclotom.h
  src/plist.c
  src/set.c
Labels: release notes: not needed, topic: kernel

#3221 Handle stack overflow in Attributes
  src/calls.h
  src/funcs.c
  tst/testspecial/stack-depth-func.g
  tst/testspecial/stack-depth-func.g.out
  tst/testspecial/stack-depth-func2.g
  tst/testspecial/stack-depth-func2.g.out
  tst/testspecial/stack-depth-list.g
  tst/testspecial/stack-depth-list.g.out
  tst/testspecial/stack-depth-operation.g
  tst/testspecial/stack-depth-operation.g.out
  tst/testspecial/stack-depth-rec.g
  tst/testspecial/stack-depth-rec.g.out
Labels: kind: bug: crash, release notes: to be added, topic: kernel

#3227 FIX: Scaling of gcd of polynomials to be standard
  hpcgap/lib/polyrat.gi
  lib/polyrat.gi
  tst/testinstall/ratfun.tst
Labels: backport-to-4.10, kind: bug, kind: bug: wrong result

#3231 Added more specialised function for testing conjugacy of subgroups of Sn
  lib/gpprmsya.gi
  lib/grp.gd
  tst/testinstall/ConjNatSym.tst
Labels: release notes: to be added, topic: library, topic: performance

#3232 Backport GAP_Enter/Leave macros to stable-4.10
  src/gasman.c
  src/gasman.h
  src/libgap-api.c
  src/libgap-api.h
Labels: topic: libgap

#3233 ci: enable coverage for C++ code
  .travis.yml
  etc/ci-prepare.sh
  etc/ci.sh
Labels: topic: ci

#3230 Start using C++ templates for partial perms kernel code
  src/pperm.cc
Labels: release notes: not needed, topic: kernel

#3229 Fix Unbound global variable warning
  src/gapstate.h
  src/read.c
  src/scanner.c
  src/scanner.h
  tst/testbugfix/2018-06-29-CurrLHSGVar.tst
  tst/testinstall/auto.tst
  tst/testinstall/bound.tst
  tst/testinstall/unbound.tst
  tst/testinstall/weakptr-badargs.tst
  tst/testspecial/debug-var.g.out
Labels: kind: bug, release notes: to be added, topic: kernel

#3214 Add helper script for bisecting regressions
  etc/bisect.sh
Labels: release notes: not needed

#3236 Add tests for slow IO
  .travis.yml
  tst/teststandard/processes/slowwrite.sh
  tst/teststandard/processes/streamio.tst
Labels: release notes: not needed, topic: kernel

#3222 kernel: add TrimPerm helper
  src/exprs.c
  src/intrprtr.c
  src/permutat.cc
  src/permutat.h
Labels: release notes: not needed, topic: kernel

#3237 Make compiler aware of hvars, and the lvar bag cache
  src/c_oper1.c
  src/c_type1.c
  src/compiled.h
  src/compiler.c
  src/hpc/c_oper1.c
  src/hpc/c_type1.c
Labels: release notes: not needed, topic: kernel

#3238 Fix usage of InfoObsolete
  lib/obsolete.gi
Labels: kind: bug, regression, release notes: not needed

#3247 `CloseMutableBasis` now returns something
  lib/algrep.gi
  lib/basismut.gd
  lib/basismut.gi
  lib/vspcmat.gi
  lib/vspcrow.gi
  tst/testinstall/vspchom.tst
  tst/testinstall/vspcmali.tst
  tst/testinstall/vspcmat.tst
  tst/testinstall/vspcrow.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3215 Print issue tracker, maintainers and contributors in package banners
  lib/package.gi
  tst/testinstall/package.tst
Labels: release notes: to be added, topic: library, topic: packages

#3252 gac: preserve argument names of compiled functions
  src/c_oper1.c
  src/c_type1.c
  src/compiler.c
  src/hpc/c_oper1.c
  src/hpc/c_type1.c
  tst/test-compile/basics.g.dynamic.c
  tst/test-compile/basics.g.static.c
  tst/test-compile/function_types.g.dynamic.c
  tst/test-compile/function_types.g.static.c
  tst/test-compile/ranges.g.dynamic.c
  tst/test-compile/ranges.g.static.c
  tst/testbugfix/2019-01-29-gac-arg-names.tst
  tst/testinstall/varargs.tst
Labels: topic: gac

#3239 kernel: better error checks in vec8bit.c, vecgf2.c
  src/error.h
  src/vec8bit.c
  src/vecgf2.c
Labels: release notes: not needed, topic: kernel

#3250 kernel: remove some dead code involving NargError
  src/calls.c
  src/calls.h
  src/funcs.c
  tst/testinstall/kernel/calls.tst
Labels: release notes: not needed, topic: kernel

#3253 generalized `CharacterTableIsoclinic`
  lib/ctbl.gd
  lib/ctbl.gi
  tst/teststandard/ctblisoc.tst
Labels: kind: enhancement, release notes: to be added

#3245 kernel/gac: fix CompUnbComObjExpr
  src/compiler.c
  tst/test-compile/basics.g.dynamic.c
  tst/test-compile/basics.g.static.c
Labels: topic: gac, topic: kernel
