Repository gap-system/gap, pull requests merged in 2019-07, with the labels that each got.

#3534 Update kernel version
  configure.ac
Labels: release notes: not needed, topic: kernel

#3528 kernel: clean up NEW_STRING
  src/stringobj.c
Labels: release notes: not needed, topic: kernel

#3536 gac: remove NLOOP_INFO
  src/compiler.c
Labels: release notes: not needed, topic: gac, topic: kernel

#3545 ReductionToFiniteField tries to change an immutable object.
  lib/ctblfuns.gi
Labels: regression, release notes: not needed

#3549 `STRING_LIST_DIR`: `LIST_DIR` may return `fail`
  lib/obsolete.gd
Labels: kind: bug: unexpected error, release notes: not needed

#3543 Add PositionSortedBy
  doc/ref/lists.xml
  lib/list.gd
  lib/list.gi
  src/listfunc.c
  tst/testinstall/list.tst
Labels: kind: enhancement, release notes: to be added

#3546 Ignore Emacs backup and lock files
  .gitignore
Labels: kind: enhancement, release notes: not needed, topic: build system

#3550 kernel: rename ELM2_LIST -> ELM_MAT, etc.
  src/code.c
  src/code.h
  src/intrprtr.c
  src/lists.c
  src/lists.h
  src/syntaxtree.c
  src/vars.c
  tst/testinstall/syntaxtree.tst
Labels: release notes: not needed, topic: kernel

#3553 Provide NrRows/NrCols methods for block matrices
  lib/matblock.gi
  tst/testinstall/matblock.tst
Labels: release notes: not needed, topic: library

#3556 Make more lib/matrix.gi code compatible with MatrixObj
  lib/matrix.gi
Labels: kind: enhancement, release notes: not needed, topic: library

#3557 Avoid use of `IsBound(t[i,j])`
  lib/matrix.gi
Labels: release notes: not needed, topic: library

#3559 Fix IsUpperTriangularMat for non-square matrices
  lib/matrix.gi
  tst/testinstall/matrix.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library

#3558 Remove some redundant methods for IsPlistMatrixRep objects
  lib/matobjplist.gi
Labels: release notes: not needed, topic: library

#3552 Add a MatElm method for matrices with memory
  lib/memory.gi
Labels: kind: enhancement, release notes: not needed, topic: library

#3554 libgap: export some matrix APIs
  src/libgap-api.c
  src/libgap-api.h
  src/libgap_intern.h
  src/modules_builtin.c
  tst/testlibgap/api.c
  tst/testlibgap/api.expect
Labels: release notes: to be added, topic: kernel, topic: libgap

#3565 Allow SyAllocPool to be smaller than SyStorMax
  src/sysmem.h
  src/system.c
Labels: kind: bug, release notes: not needed

#3572 kernel: fix startup warning about undefined NrRows / NrCols
  src/libgap-api.c
Labels: regression, release notes: not needed, topic: kernel

#3573 IsObjWithMemory: prefer IsMatrixObj over IsMatrix
  lib/memory.gi
Labels: kind: enhancement, release notes: not needed, topic: library

#3564 Add WhereWithVars - a more verbose Where
  doc/ref/debug.xml
  doc/ref/mloop.xml
  lib/error.g
  tst/testspecial/backtrace.g
  tst/testspecial/backtrace.g.out
Labels: kind: enhancement, release notes: to be added, topic: library

#3580 Fix potential infinite loop or recursion when computing size of infinite cyclic groups
  lib/grp.gi
  tst/testbugfix/2019-07-17-cyclic-size.tst
Labels: kind: bug, release notes: to be added

#3575 Clear stored inverse when calling TrimPerm
  src/permutat.cc
  src/permutat.h
  tst/testbugfix/2019-07-15-StoredInv.tst
Labels: backport-to-4.10, kind: bug, kind: bug: wrong result, release notes: to be added

#3579 Speed up writing to global variables
  src/gvars.c
Labels: kind: enhancement, release notes: to be added

#3582 Fix warnings that pop up with some GCC versions
  src/baltree.h
  src/dynarray.h
Labels: release notes: not needed, topic: kernel

#3589 Undocument second argument for `DeclareGlobalFunction"
  lib/oper.g
Labels: kind: enhancement, release notes: not needed, topic: documentation

#3590 add more tests for IsDiagonalMat, IsUpperTriangularMat, IsLowerTriangularMat
  tst/testinstall/matrix.tst
Labels: release notes: not needed, topic: tests
