Repository gap-system/gap, pull requests merged in 2019-12, with the labels that each got.

#3763 Fix bug in IrrConlon leading to unexpected errors
  lib/ctblsolv.gi
  tst/testbugfix/2019-11-28-IrrConlon.tst
Labels: backport-to-4.11, kind: bug, kind: bug: unexpected error, release notes: to be added, topic: library

#3769 kernel: avoid using vfork
  src/sysfiles.c
Labels: kind: bug, release notes: not needed, topic: kernel

#3770 Remove tst/testtravis.g
  .travis.yml
  tst/testtravis.g
Labels: release notes: not needed, topic: tests

#3768 Fix some warnings reported by clang static analyzer
  src/bits_intern.h
  src/compiler.c
  src/cyclotom.c
  src/finfield.c
  src/lists.c
  src/modules.c
  src/modules.h
  src/permutat.cc
  src/profile.c
  src/trans.cc
  src/vec8bit.c
Labels: release notes: not needed, topic: kernel

#3773 Add default IsBound on small lists for large integers
  lib/list.gi
  tst/testinstall/hpc/atomic_list.tst
  tst/testinstall/list.tst
Labels: backport-to-4.11, kind: bug, kind: bug: unexpected error, release notes: to be added, topic: library

#2758 Revert "Downrank MatrixObj methods to unbreak Semigroups"
  lib/matobj.gi
Labels: release notes: not needed, topic: library

#3767 Remove resolved TODOs from dev/manualchapters
  dev/manualchapters
Labels: release notes: not needed, topic: documentation

#3778 Tweak README.md and INSTALL.md instructions some more
  INSTALL.md
  README.md
Labels: backport-to-4.11, release notes: not needed, topic: documentation

#3780 Adjust documentation and example of IsPrimitiveCharacter
  lib/ctblmono.gd
Labels: kind: enhancement, release notes: not needed, topic: documentation

#3789 Update Travis Slack notification integration
  .travis.yml
Labels: release notes: not needed, topic: ci

#3777 Fix program cleanup logic
  lib/init.g
  lib/session.g
Labels: backport-to-4.11, kind: bug: unexpected error, release notes: not needed, topic: HPC-GAP, topic: libgap

#3788 Travis: add libcdd-dev to deps for testpackages
  .travis.yml
Labels: backport-to-4.11, release notes: not needed, topic: ci

#3785 missing `Representative` method for abelian number fields
  hpcgap/lib/fldabnum.gi
  lib/fldabnum.gi
  tst/testinstall/fldabnum.tst
Labels: kind: bug: unexpected error, release notes: not needed, topic: library

#3792 Use `Info` not `Print` in `Decomposition`
  lib/zlattice.gi
  tst/testinstall/zlattice.tst
Labels: kind: general proposed change, release notes: to be added, topic: library

#3790 Improvements to simple group generation/iteration
  grp/simple.gi
  tst/testinstall/opers/SimpleGroup.tst
Labels: kind: enhancement, release notes: to be added

#3787 Brauer table of a permuted isoclinic table
  lib/ctbl.gi
  tst/teststandard/ctblisoc.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: not needed, topic: library

#3775 kernel: use posix_spawn_file_actions_addchdir if available
  configure.ac
  src/iostream.c
Labels: release notes: not needed, topic: kernel

#3797 gasman: split CollectBags into several functions
  src/gasman.c
Labels: release notes: not needed, topic: kernel

#3801 Add new contributors to COPYRIGHT
  COPYRIGHT
Labels: backport-to-4.11, release notes: not needed

#3802 Update .mailmap to get nicer 'git shortlog -sne' output
  .mailmap
Labels: release notes: not needed

#3804 kernel: add UpdateTime helper
  src/gap.c
  src/gap.h
  src/streams.c
Labels: release notes: not needed, topic: kernel

#3807 kernel: move IsIdent to sysstr.h
  src/code.c
  src/compiler.c
  src/debug.c
  src/error.c
  src/gap.c
  src/gvars.c
  src/io.c
  src/opers.c
  src/profile.c
  src/read.c
  src/scanner.c
  src/scanner.h
  src/streams.c
  src/sysfiles.c
  src/sysstr.h
Labels: release notes: not needed, topic: kernel

#3810 kernel: remove a bunch of useless comments
  src/blister.c
  src/calls.c
  src/compiler.c
  src/costab.c
  src/cyclotom.c
  src/exprs.c
  src/finfield.c
  src/funcs.c
  src/gap.c
  src/gvars.c
  src/integer.c
  src/listfunc.c
  src/listoper.c
  src/lists.c
  src/modules.c
  src/opers.c
  src/permutat.cc
  src/plist.c
  src/precord.c
  src/range.c
  src/rational.c
  src/sctable.c
  src/set.c
  src/streams.c
  src/stringobj.c
  src/sysfiles.c
  src/tietze.c
  src/vars.c
  src/vec8bit.c
  src/vecffe.c
  src/vecgf2.c
  src/vector.c
Labels: release notes: not needed, topic: kernel

#3813 kernel: add ALL_BITS_UINT; avoid 1UL, 0UL
  src/bits_intern.h
  src/blister.c
  src/collectors.cc
  src/intfuncs.c
  src/intrprtr.c
  src/listfunc.c
  src/objfgelm.cc
  src/objpcgel.cc
  src/read.c
  src/scanner.h
  src/vecgf2.c
Labels: release notes: not needed, topic: kernel

#3809 kernel: tweak sysstr.h, IsIdent()
  src/io.c
  src/scanner.c
  src/sysstr.c
  src/sysstr.h
  src/system.h
Labels: release notes: not needed, topic: kernel

#3806 kernel: cleanup zlib/gzip logic in SyFopen
  src/sysfiles.c
Labels: release notes: not needed, topic: kernel

#3815 kernel: refactor GASMAN globals sorting
  src/gasman.c
  src/gasman_intern.h
  src/saveload.c
Labels: release notes: not needed, topic: kernel
