Repository gap-system/gap, pull requests merged in 2019-08, with the labels that each got.

#3591 Improve documentation of parts of chapter 41 in the reference manual
  lib/oprt.gd
Labels: release notes: to be added, topic: documentation

#3585 tests: use @local some more, avoid Unbind for GC reasons
  tst/testinstall/grpmat.tst
  tst/teststandard/algext.tst
  tst/teststandard/direct_factors.tst
  tst/teststandard/innerfunc.tst
  tst/teststandard/opers/ComplementClassesRepresentatives.tst
  tst/teststandard/permgrp.tst
  tst/teststandard/stabchain.tst
Labels: release notes: not needed, topic: tests

#3592 Don't automatically call attribute setters on mutable objects
  doc/ref/types.xml
  lib/sgpres.gi
  lib/tietze.gi
  src/opers.c
  tst/testinstall/attribute.tst
Labels: kind: enhancement, release notes: to be added, topic: kernel

#3587 kernel: call SyMsgsBags directly from GASMAN
  src/gap.c
  src/gasman.c
  src/gasman.h
  src/sysmem.h
Labels: release notes: not needed, topic: kernel

#3437 Add a RedispatchOnCondition to SubdirectProductOp
  lib/gprd.gi
Labels: kind: bug, kind: bug: unexpected error, release notes: to be added, topic: library

#3602 MatrixObj: Add IsEmptyMatrix property
  doc/ref/matrix.xml
  lib/matobj.gi
  lib/matobj2.gd
Labels: kind: enhancement, release notes: not needed

#2952 Add command line option --bare to start GAP without any packages
  lib/system.g
Labels: kind: new feature, release notes: to be added

#3605 Replace 'for ring' with 'for a ring'
  lib/ring.gi
Labels: gapsingular2019, kind: enhancement, release notes: not needed, topic: library

#3600 Performance improvements to automorphisms/isomorphism
  lib/autsr.gi
  lib/morpheus.gi
  tst/teststandard/opers/AutomorphismGroup.tst
  tst/teststandard/opers/IsomorphismGroups.tst
  tst/teststandard/permgrp.tst
Labels: kind: enhancement, release notes: not needed

#3586 kernel: put GASMAN specific code inside #ifdef USE_GASMAN
  src/stats.c
  src/sysmem.c
  src/sysmem.h
  src/system.c
Labels: release notes: not needed, topic: kernel

#3560 some more fixes and changes for matrix(obj) functions
  lib/matobj2.gd
  lib/matrix.gd
  lib/matrix.gi
Labels: kind: bug: unexpected error, release notes: not needed, topic: documentation

#3613 Update the dev manual a bit
  doc/dev/kernel.xml
Labels: gapsingular2019, kind: enhancement, release notes: not needed, topic: documentation

#3610 Invalid use of / on ZmodnZObjs (e.g. dividing a unit by a zero divisor) produces an error, instead of returning fail
  lib/zmodnz.gi
  tst/testinstall/zmodnz.tst
Labels: gapsingular2019, release notes: to be added, topic: library

#3620 Adds `make html` that does not build the manual as pdf
  Makefile.rules
  doc/make_doc.in
Labels: gapsingular2019, kind: enhancement, release notes: to be added, topic: build system

#3626 support class/character names in char. table Display
  lib/ctbl.gd
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3629 Fix git merge-base command
  .github/pull_request_template.md
Labels: kind: bug, release notes: not needed

#3606 Add BindingsOfClosure helper
  lib/function.gi
  src/vars.c
  tst/testbugfix/2017-05-14-lvars.tst
  tst/testinstall/opers/BindingsOfClosure.tst
Labels: gapsingular2019, kind: enhancement, release notes: to be added

#3612 Clarify, fix and test semantics of Quotient(R,a,b)
  hpcgap/lib/integer.gi
  lib/field.gi
  lib/gaussian.gi
  lib/integer.gi
  lib/ring.gd
  tst/testinstall/opers/Quotient.tst
  tst/testspecial/backtrace.g.out
Labels: gapsingular2019, kind: bug, kind: enhancement, release notes: to be added

#3513 kernel: use posix_spawn in iostreams if available
  configure.ac
  src/iostream.c
Labels: release notes: to be added, topic: kernel
