Repository gap-system/gap, pull requests merged in 2019-03, with the labels that each got.

#3318 Move COUNT_TRUES_BLOCK(S) out of header
  src/blister.c
  src/blister.h
Labels: release notes: not needed, topic: kernel

#3326 Use TmpNameAllArchs instead of TmpName
  tst/testinstall/kernel/streams.tst
Labels: release notes: not needed

#3325 libgap: fix name of GAP_EnterDebugMessage_
  src/libgap-api.c
Labels: backport-to-4.10, topic: kernel, topic: libgap

#3330 buildsys: remove spurious comma in configure.ac
  configure.ac
Labels: release notes: not needed, topic: build system

#3331 Fix finiteness condition in `IsomorphismGroups`
  lib/morpheus.gi
  tst/testbugfix/2019-03-08-IsomorphismGroups.tst
Labels: kind: enhancement, release notes: to be added

#3338 kernel: SyntaxTreeFunc returns args+locals in one list
  src/syntaxtree.c
Labels: release notes: not needed, topic: kernel

#3337 kernel: generalize SyntaxTreeDefaultCompiler
  src/syntaxtree.c
Labels: release notes: not needed, topic: kernel

#3320 Handle \r without a \n in cygwin
  src/sysfiles.c
Labels: os: windows, release notes: to be added, topic: kernel

#3334 Travis: re-enable OS X builds
  .travis.yml
Labels: release notes: not needed, topic: build system, topic: ci

#3358 document the two-argument version of `Set`
  lib/coll.gd
  lib/list.gi
Labels: gapdays2019-spring, release notes: to be added, topic: documentation

#3353 kernel: refactor access to TmpTrans
  src/trans.cc
Labels: gapdays2019-spring, release notes: not needed, topic: kernel

#3350 Change PrintCSV to not use SizeScreen
  lib/string.gi
  tst/testinstall/stringobj.tst
Labels: gapdays2019-spring, release notes: not needed, topic: library

#3348 Add explanation for workaround of #3346
  INSTALL.md
  README.md
Labels: gapdays2019-spring

#3352 kernel/gac: don't hardcode TNUM values in generated C code
  src/compiler.c
  tst/test-compile/basics.g.dynamic.c
  tst/test-compile/basics.g.static.c
Labels: gapdays2019-spring, release notes: not needed, topic: gac, topic: kernel

#3359 Simplify DoNFIM code
  lib/matint.gi
Labels: gapdays2019-spring, release notes: not needed, topic: library

#3362 Separate testextra from teststandard
  Makefile.rules
  tst/testextra.g
  tst/teststandard.g
Labels: topic: tests

#3351 kernel: refactor ON_KERNEL_ANTI_ACTION
  src/trans.cc
Labels: gapdays2019-spring, release notes: not needed, topic: kernel

#3360 Improve discoverability of "rewriteToFile" option in "Test"
  lib/test.gi
  tst/testspecial/broken-test.g.out
Labels: gapdays2019-spring, kind: enhancement, topic: documentation

#3366 Add .github/no-response.yml
  .github/no-response.yml
Labels: release notes: not needed

#3361 buildsys: resolve some issues if path contains spaces
  cnf/build-extern.sh
  cnf/compat/gap.sh.in
  extern/gmp/config.guess
  extern/gmp/config.sub
Labels: gapdays2019-spring, topic: build system

#3377 Fix AppVeyor
  .appveyor.yml
Labels: release notes: not needed, topic: ci

#3378 kernel: avoid using global buffers in FuncExecuteProcess
  src/streams.c
Labels: release notes: not needed, topic: kernel

#3365 Add First(list), Last(list) and Last(list,func)
  lib/list.gd
  lib/list.gi
  tst/testinstall/list.tst
Labels: gapdays2019-spring, kind: enhancement, release notes: to be added, topic: libgap

#3374 Document that InputTextFile should not be used for binary files
  lib/streams.gd
Labels: topic: documentation

#3356 MatrixObj: remove Fold / Unfold
  hpcgap/lib/vec8bit.gi
  hpcgap/lib/vecmat.gi
  lib/matobj.gi
  lib/matobj2.gd
  lib/matobjplist.gi
  lib/vec8bit.gi
  lib/vecmat.gi
Labels: gapdays2019-spring, release notes: not needed, topic: library

#3376 Add SortedList method with function
  lib/coll.gd
  lib/coll.gi
  tst/testinstall/coll.tst
Labels: kind: enhancement

#3372 Make some interpreter / reader errors a bit nicer
  src/read.c
  tst/testbugfix/2012-09-06-t00253.tst
  tst/testinstall/error.tst
  tst/testinstall/help.tst
Labels: gapdays2019-spring, kind: enhancement, topic: kernel

#3382 kernel: Make finite field tables guard-safe for HPC-GAP
  src/finfield.c
  src/finfield.h
Labels: release notes: not needed, topic: HPC-GAP, topic: kernel
