Repository gap-system/gap, pull requests merged in 2019-04, with the labels that each got.

#3390 Fix Bug in 64Bit SetCyclotomicsLimit
  doc/ref/cyclotom.xml
  src/cyclotom.c
  tst/testinstall/cyclotom.tst
Labels: kind: bug, release notes: to be added, topic: kernel

#3391 Add RequireMutable
  src/error.h
  src/listfunc.c
  src/lists.c
  src/vecgf2.c
  tst/testinstall/kernel/listfunc.tst
  tst/testinstall/listindex.tst
  tst/testinstall/matblock.tst
Labels: kind: enhancement, release notes: not needed, topic: error handling, topic: kernel

#3385 Add Flip/SetAll/ClearAllBlist
  doc/ref/blist.xml
  lib/list.g
  src/blister.c
  tst/testinstall/kernel/blister.tst
Labels: kind: enhancement, release notes: to be added, topic: kernel

#3397 FIX: ClosureSubgroup assumes closure is in parent.
  doc/ref/fldabnum.xml
  lib/grp.gi
  lib/grplatt.gi
  tst/testbugfix/2019-04-09-Lattice.tst
Labels: backport-to-4.10, kind: bug: wrong result, topic: library

#3394 Give the plist TNUMS more human-readable names
  src/plist.c
  tst/testbugfix/2018-06-18-empty-OnTuples.tst
  tst/testinstall/bitfields.tst
  tst/testinstall/kbsemi.tst
  tst/testinstall/kernel/stringobj.tst
  tst/testinstall/list.tst
  tst/testinstall/listindex.tst
  tst/testinstall/opers/ListBlist.tst
  tst/testinstall/trans.tst
  tst/testinstall/weakptr-badargs.tst
Labels: kind: enhancement, release notes: to be added

#3401 Do not require SSortedLists are homogeneous
  src/lists.c
  tst/testbugfix/2019-04-10-SSortedList.tst
Labels: kind: bug, kind: bug: unexpected error, topic: kernel

#3370 Added pragmas
  doc/ref/function.xml
  doc/ref/language.xml
  src/code.c
  src/code.h
  src/intrprtr.c
  src/intrprtr.h
  src/io.c
  src/io.h
  src/read.c
  src/scanner.c
  src/scanner.h
  src/stats.c
  src/syntaxtree.c
  tst/testinstall/pragma.tst
Labels: gapdays2019-spring, kind: enhancement, topic: kernel

#3399 Allow floating point values in memory command line options
  src/system.c
Labels: kind: enhancement, release notes: to be added

#3406 Windows: remove RXVT shell support
  INSTALL.md
  cnf/cygwin/gaprxvt.bat.in
  cnf/cygwin/instcygwinterminfo.sh
  configure.ac
  doc/ref/copyright.xml
Labels: os: windows, release notes: to be added

#3410 Do not end pragma scanning at \t (horizontal tab) character
  src/scanner.c
  tst/testinstall/pragma.tst
Labels: release notes: not needed

#3409 Remove BANNER, QUIET; update status of various obsoletes
  lib/obsolete.gd
  lib/obsolete.gi
Labels: release notes: added, topic: library

#3412 Temporary fix for the Julia GC.
  src/julia_gc.c
  src/julia_gc.h
  src/weakptr.c
Labels: kind: bug, kind: bug: crash, release notes: to be added, topic: julia, topic: kernel

#3414 kernel: merge ListExpr{1,2} into EvalList{Tilde,}Expr
  src/exprs.c
Labels: release notes: not needed, topic: kernel

#3429 kernel: fix off-by-one error in FuncREM_SET
  src/set.c
Labels: kind: bug, regression, release notes: not needed, topic: kernel
