Repository gap-system/gap, pull requests merged in 2019-05, with the labels that each got.

#3433 kernel: replace ImmutableEmptyPlist by a function
  src/calls.c
  src/listoper.c
  src/plist.c
  src/plist.h
  src/pperm.cc
  src/trans.cc
Labels: regression, release notes: not needed, topic: kernel

#3435 Workaround for GMP crash on Cygwin (regression introduced by PR #3434)
  src/integer.c
Labels: regression, release notes: not needed, topic: kernel

#3430 Turn NameFunction into an attribute
  lib/function.g
  lib/function.gi
  src/calls.c
  tst/testinstall/callfunc.tst
Labels: kind: enhancement, topic: kernel

#3440 line breaking hints in the `ViewString` method for lists
  lib/list.gi
  src/lists.c
  tst/testinstall/ctblfuns.tst
  tst/testinstall/mapping.tst
  tst/testinstall/strings.tst
  tst/teststandard/reesmat.tst
Labels: kind: bug, release notes: to be added

#3447 kernel: rename T_PRAGMA -> STAT_PRAGMA
  src/code.c
  src/code.h
  src/stats.c
  src/syntaxtree.c
Labels: release notes: not needed, topic: kernel

#3438 LibGAP API: Add `GAP_AssignGlobalVariable` and `GAP_CanAssignGlobalVariable`
  src/libgap-api.c
  src/libgap-api.h
  tst/testlibgap/api.c
Labels: release notes: to be added, topic: kernel, topic: libgap

#3420 Give human-readable names to functions in InstallMethod
  lib/oper1.g
  src/c_oper1.c
  src/hpc/c_oper1.c
  tst/testinstall/method.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3457 Fix QuickUnsolvabilityTestPerm for trivial groups
  lib/grpperm.gi
Labels: regression, release notes: not needed, topic: library

#3449 Clarify and correct documentation of `CompositionMapping`, add an example
  lib/mapping.gd
Labels: kind: bug, release notes: to be added, topic: documentation

#3448 lib: add AsSSortedList method ...
  lib/list.gi
  tst/testinstall/coll.tst
  tst/testinstall/list.tst
Labels: kind: enhancement, release notes: not needed, topic: library

#3458 Improve InstallMethod warnings when using -N
  lib/oper1.g
  src/c_oper1.c
  src/hpc/c_oper1.c
Labels: release notes: not needed

#3461 Add CONFIGFLAGS accidentally deleted in f30c1e4e5
  .travis.yml
Labels: release notes: not needed, topic: tests

#3465 Reduce varnames.tst sensitivity to the list of loaded packages
  tst/teststandard/varnames.tst
Labels: backport-to-4.10, release notes: not needed, topic: tests

#3463 Fix buffer overflow in TransformationListListNC
  src/trans.cc
  tst/testinstall/trans.tst
Labels: backport-to-4.10, kind: bug: crash, release notes: to be added, topic: kernel

#3466 Change http to https for many web links
  .clang-format
  .editorconfig
  CONTRIBUTING.md
  INSTALL.md
  Makefile.rules
  README.buildsys.md
  README.md
  configure.ac
  doc/changes/main.xml
  doc/dev/lib.xml
  doc/dev/updates.xml
  doc/dev/website.xml
  doc/hpc/main.xml
  doc/migratedoc.tex
  doc/ref/copyright.xml
  doc/ref/gappkg.xml
  doc/ref/help.xml
  doc/ref/main.xml
  doc/ref/mloop.xml
  doc/tut/main.xml
  lib/cmdledit.g
  lib/grplatt.gd
  lib/numtheor.gd
  lib/process.gd
  lib/schursym.gi
  src/blister.h
  src/iostream.c
  src/sysfiles.c
Labels: release notes: not needed, topic: documentation

#3459 Add ShowDeclarationsOfOperation helper
  doc/ref/create.xml
  lib/methwhy.g
Labels: kind: enhancement, kind: new feature, release notes: to be added, topic: library

#3099 Show a warning when GroupWithGenerators called on a domain
  lib/grp.gi
Labels: kind: enhancement, release notes: to be added

#3468 Add a `PrintObj` method for general domains which know their `GeneratorsOfDomain`
  lib/domain.gi
  lib/relation.gd
  tst/testinstall/domain.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3478 Fix \< for equal but not identical large integers
  src/integer.c
  tst/testinstall/intarith.tst
Labels: backport-to-4.10, kind: bug, kind: bug: wrong result, release notes: to be added, topic: kernel

#3453 Clarify documentation of GeneratorsOfDomain and add an example
  lib/domain.gd
Labels: kind: enhancement, release notes: to be added, topic: documentation
