Repository gap-system/gap, pull requests merged in 2019-02, with the labels that each got.

#3234 kernel: rewrite SCR_SIFT_HELPER using C++ templates
  src/modules-builtin.c
  src/permutat.cc
Labels: kind: bug, topic: kernel

#3255 kernel: convert more transformation code to C++ templates
  src/trans.cc
Labels: release notes: not needed, topic: kernel

#3249 kernel: update arg validation in objfgelm.cc
  src/objfgelm.cc
  tst/testinstall/kernel/objfgelm.tst
  tst/testinstall/wordrep.tst
Labels: release notes: not needed, topic: kernel

#3228 kernel: split GVAR_FILTER into GVAR_{ATTR,FILT,PROP}
  src/blister.c
  src/bool.c
  src/calls.c
  src/cyclotom.c
  src/finfield.c
  src/integer.c
  src/lists.c
  src/modules.h
  src/objects.c
  src/opers.c
  src/plist.c
  src/pperm.cc
  src/range.c
  src/rational.c
  src/records.c
  src/stringobj.c
  src/trans.cc
  src/weakptr.c
Labels: release notes: not needed, topic: kernel

#3260 kernel: restore compatibility with older GCC versions
  src/modules.h
Labels: regression, release notes: not needed, topic: kernel

#3268 Increase InfoObsolete level for (Un)HideGlobalVariables
  lib/obsolete.gi
Labels: regression, release notes: not needed

#3264 kernel: rename namesOfLocals to namesOfArgsAndLocals
  src/calls.c
  src/calls.h
Labels: release notes: not needed, topic: kernel

#3266 kernel: further improve arg validation
  src/blister.c
  src/error.c
  src/error.h
  src/hpc/threadapi.c
  src/intfuncs.c
  src/intrprtr.c
  src/listfunc.c
  src/listoper.c
  src/lists.c
  src/permutat.cc
  src/pperm.cc
  src/streams.c
  src/trans.cc
  src/vars.c
  src/vecgf2.c
  tst/testinstall/bitfields.tst
  tst/testinstall/kernel/lists.tst
  tst/testinstall/kernel/streams.tst
  tst/testinstall/list.tst
  tst/testinstall/perm.tst
  tst/testinstall/pperm.tst
  tst/testinstall/range.tst
  tst/testinstall/trans.tst
Labels: release notes: not needed, topic: kernel

#3262 kernel: avoid accessing NLOC_FUNC in PrintFunction if possible
  src/calls.c
  tst/testinstall/bitfields.tst
Labels: release notes: not needed, topic: kernel

#3267 Change StructureDescription for infinite cyclic group
  lib/grpnames.gd
  lib/grpnames.gi
  tst/testinstall/opers/StructureDescription.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#2835 Travis: run testinstall with all packages after testpackages
  .travis.yml
  etc/ci-gather-coverage.sh
  tst/testinstall-loadall.g
Labels: gapdays2018-fall, release notes: not needed, topic: ci

#3276 Support custom size function bags in InstallGlobalFunction
  src/opers.c
Labels: backport-to-4.10, release notes: not needed, topic: kernel

#3272 kernel: add / document some options to the Julia GC code
  src/julia_gc.c
Labels: release notes: not needed, topic: julia, topic: kernel

#3269 Make TemporaryGlobalVarName obsolete
  doc/ref/language.xml
  doc/ref/obsolete.xml
  lib/global.gd
  lib/global.gi
  lib/obsolete.gd
  lib/obsolete.gi
Labels: release notes: to be added, topic: library

#3265 kernel: get rid of FEXS_FUNC
  src/calls.c
  src/calls.h
  src/code.c
  src/code.h
  src/compiler.c
  src/funcs.c
  src/syntaxtree.c
Labels: release notes: not needed, topic: kernel

#3283 travis: allow Julia tests to fail
  .travis.yml
Labels: topic: ci, topic: julia

#3286 ValidatePackageInfo: add optional License field
  lib/package.gi
  tst/mockpkg/PackageInfo.g
Labels: kind: enhancement, topic: library, topic: packages

#3124 Add make check-manuals to makemanuals Travis test
  Makefile.rules
  doc/ref/testconsistency.g
  etc/ci.sh
Labels: release notes: not needed, topic: documentation, topic: tests

#3291 kernel: tweak Julia's MARKING_STRESS_TEST
  src/julia_gc.c
Labels: backport-to-4.10, release notes: not needed, topic: julia, topic: kernel

#3288 kernel: tweak some comments
  src/calls.h
  src/intobj.h
  src/lists.h
  src/objects.h
  src/plist.h
  src/precord.h
  src/range.h
  src/system.h
Labels: release notes: not needed, topic: kernel

#3289 kernel: make OnCharReadHook* static
  src/gap.c
  src/sysfiles.c
  src/sysfiles.h
Labels: release notes: not needed, topic: kernel

#3298 Fix a typo in listfunc.h
  src/listfunc.h
Labels: topic: kernel

#3285 buildsys: add `make check`
  Makefile.rules
Labels: backport-to-4.10, release notes: to be added, topic: build system

#3304 kernel: remove redundant break and return statements
  src/calls.c
  src/compiler.c
  src/costab.c
  src/gap.c
  src/iostream.c
  src/listoper.c
  src/objcftl.c
  src/objects.c
  src/pperm.cc
  src/records.c
  src/tietze.c
  src/vecgf2.c
Labels: release notes: not needed, topic: kernel

#3307 ci: explicitly install python27 on AppVeyor
  .appveyor.yml
Labels: os: windows, release notes: not needed, topic: ci

#3311 Fix corner case in modified Todd-Coxeter when relator is trivial
  lib/sgpres.gi
  tst/testbugfix/2019-02-19-cornercase-mtc.tst
Labels: backport-to-4.10, kind: bug, kind: bug: unexpected error, release notes: to be added

#3308 More api tests
  tst/testlibgap/api.c
  tst/testlibgap/api.expect
Labels: topic: libgap

#3315 Overview of changes in the GAP 4.10.1 release
  doc/changes/changes-4.10.xml
Labels: backport-to-4.10, topic: documentation

#3316 Clarify --with-julia help string
  configure.ac
Labels: release notes: not needed
