Repository gap-system/gap, pull requests merged in 2020-03, with the labels that each got.

#3904 Add Ubuntu singular to deps for testpackages
  .travis.yml
Labels: release notes: not needed, topic: packages, topic: tests

#3901 Allow function-call syntax for general mappings.
  lib/mapping.gd
  lib/mapping.gi
  tst/testinstall/mapping.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3903 Fixed bug with Cycles((),[])
  lib/oprt.gi
  tst/testinstall/perm.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: to be added

#3914 Add InnerAutomorphismGroup for groups
  doc/ref/grphomom.xml
  lib/morpheus.gd
  lib/morpheus.gi
  tst/testinstall/morpheus.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#3911 lib: improve PageSource
  lib/methwhy.g
Labels: kind: enhancement, release notes: to be added, topic: library

#3702 Make TmpNameAllArchs obsolete by enhancing TmpName
  lib/files.gd
  lib/obsolete.gi
  lib/process.gd
  lib/process.gi
  src/streams.c
  tst/testinstall/kernel/streams.tst
Labels: os: windows, topic: kernel

#3839 kernel: move InterpreterStartLine from GAPState to `struct IntrState`
  src/gapstate.h
  src/intrprtr.c
  src/intrprtr.h
  src/io.c
  src/read.c
  src/scanner.c
Labels: release notes: not needed, topic: kernel

#3926 Document changes in GAP 4.3 bugfixes
  CHANGES.md
Labels: backport-to-4.11, release notes: not needed, topic: documentation

#3927 Unbreak out-of-tree builds
  Makefile.rules
Labels: kind: bug, release notes: not needed, topic: build system

#3929 Remove GAP bibliography documentation from doc/dev manual
  doc/dev/website.xml
Labels: release notes: not needed, topic: documentation

#3916 Enhancements to creating and using rewriting systems.
  grp/basicpcg.gi
  lib/factgrp.gd
  lib/gpfpiso.gi
  lib/grp.gd
  lib/grpfp.gi
  lib/grplatt.gd
  lib/kbsemi.gi
  lib/twocohom.gd
  lib/twocohom.gi
  tst/testextra/makeperfect.g
  tst/testinstall/pgroups.tst
  tst/teststandard/twocohom.tst
Labels: kind: enhancement, release notes: not needed

#3931 Do not ignore `#@` comments after empty line at start of test file
  lib/test.gi
  tst/testspecial/broken-test.g.out
  tst/testspecial/leading-empty-line.g
  tst/testspecial/leading-empty-line.g.out
  tst/testspecial/leading-empty-line.tst
Labels: kind: bug, release notes: to be added, topic: tests

#3935 FIX for #3934
  lib/autsr.gi
  lib/morpheus.gi
  tst/teststandard/opers/IsomorphismGroups.tst
Labels: kind: bug: unexpected error, kind: enhancement, release notes: not needed
