Repository gap-system/gap, pull requests merged in 2020-04, with the labels that each got.

#3938 Remove sySetjmp / Syjmp_buf (was Enable _POSIX_C_SOURCE)
  configure.ac
  src/error.c
  src/gap.c
  src/gapstate.h
  src/gasman.c
  src/hpc/serialize.c
  src/hpc/thread.c
  src/hpc/threadapi.c
  src/hpc/tls.h
  src/julia_gc.c
  src/libgap-api.c
  src/libgap-api.h
  src/read.c
  src/read.h
  src/streams.c
  src/sysjmp.c
  src/sysjmp.h
Labels: backport-to-4.11, release notes: not needed

#3933 Add libtool versioning to libgap shared library
  GNUmakefile.in
  Makefile.rules
  configure.ac
  src/modules.h
Labels: kind: enhancement, topic: build system

#3881 kernel: simplify OnPosIntSetsPartialPerm
  src/pperm.cc
Labels: release notes: not needed, topic: kernel

#3945 kernel: only #include sysjmp.h where necessary
  src/error.c
  src/gapstate.h
  src/gasman.c
  src/hpc/serialize.c
  src/hpc/thread.c
  src/hpc/threadapi.c
  src/hpc/tls.h
  src/libgap-api.h
  src/read.c
  src/tracing.c
Labels: release notes: not needed, topic: kernel

#3944 Fix error checking in PartialPerm
  lib/pperm.gi
  tst/testinstall/pperm.tst
Labels: backport-to-4.11, release notes: to be added

#3946 kernel: separate SyAllocBags* func into alloc & free parts
  src/sysmem.c
Labels: release notes: not needed, topic: kernel

#3950 Silence `gcc -fsanitize=undefined` warnings
  src/opers.c
Labels: backport-to-4.11, release notes: not needed, topic: kernel

#3954 Travis: add a timeout to curl downloads
  etc/ci-prepare.sh
Labels: backport-to-4.11, release notes: not needed, topic: ci

#3952 kernel: fix two warnings reported by clang 10
  src/gasman.c
  src/plist.c
Labels: release notes: not needed, topic: kernel

#3959 buildsys: 'check' target depends on 'all'; remove leftover GAPMPI reference
  Makefile.rules
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3955 buildsys: add maintainer mode
  GNUmakefile.in
  Makefile.rules
  configure.ac
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3958 Fix test suite to work on big endian systems (for master)
  tst/testinstall/pperm.tst
Labels: release notes: not needed, topic: tests

#3956 Fix test suite to work on big endian systems (for stable-4.11)
  tst/testinstall/pperm.tst
Labels: release notes: not needed, topic: tests

#3964 BuildPackages.sh: add --with-gap option
  bin/BuildPackages.sh
Labels: backport-to-4.11, kind: enhancement, release notes: not needed, topic: build system, topic: packages

#3953 BuildPackages.sh: run prerequisites.sh if present
  bin/BuildPackages.sh
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3744 Add Travis tests on arm64, ppc64le, s390x
  .travis.yml
  etc/ci-coveralls-merge.py
  tst/testinstall/kernel/opers.tst
Labels: backport-to-4.11, release notes: not needed, topic: ci

#3970 Remove obsolete doc/README
  doc/README
Labels: release notes: not needed, topic: documentation

#3968 BuildPackage.sh: prepare for NormalizInterface change
  bin/BuildPackages.sh
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3967 buildsys: fix install-gaproot target for out-of-tree builds
  Makefile.rules
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3972 Fix BuildPackages.sh --parallel option
  bin/BuildPackages.sh
Labels: backport-to-4.11, release notes: not needed, topic: build system

#3963 Implement compression/decompression of filenames ending .gz
  src/sysfiles.c
  tst/example-dir/compress/not-compressed.txt.gz
  tst/example-dir/readme.txt
  tst/testinstall/compressed.tst
  tst/testinstall/read.tst
Labels: backport-to-4.11, kind: bug, kind: enhancement, topic: kernel

#3980 FIX: GCD for rational polynomials
  lib/polyrat.gi
  tst/testbugfix/2020-04-22-Polyratgcd.tst
Labels: backport-to-4.11, kind: bug, kind: bug: unexpected error, release notes: to be added

#3977 Fix line breaks in manual.lab files
  lib/package.gi
Labels: backport-to-4.11, kind: bug, release notes: not needed

#3986 Add some missing methods for machine floats (Sinh, Cosh, Tanh, Asinh, Acosh, Atanh, CubeRoot, Erf, Gamma)
  configure.ac
  lib/float.gd
  lib/ieee754.g
  src/macfloat.c
  tst/testinstall/float.tst
Labels: kind: enhancement, release notes: to be added, topic: kernel

#3978 Use locale variables in accordance with POSIX requirements.
  lib/init.g
Labels: kind: bug, topic: library

#3982 ENHANCE: Rewriting systems for groups
  lib/gpfpiso.gi
  lib/kbsemi.gi
Labels: kind: enhancement, release notes: not needed

#3991 kernel: move keywords related code from scanner to io
  src/io.c
  src/modules_builtin.c
  src/scanner.c
  src/scanner.h
Labels: release notes: not needed, topic: kernel

#3993 gac: *really* try to remove gactmp
  cnf/gac.in
Labels: backport-to-4.11, release notes: not needed, topic: gac

#3990 kernel: restrict STATE(In) access to io.c
  src/io.c
  src/scanner.c
Labels: release notes: not needed, topic: kernel

#3994 julia: avoid potential inlining issue
  src/julia_gc.c
Labels: release notes: not needed, topic: julia, topic: kernel
