Repository gap-system/gap, pull requests merged in 2020-09, with the labels that each got.

#4099 Passing a `.tst` file as argument to `gap` will now invoke `Test` on it, instead of trying to `Read` it (which will fail)
  lib/init.g
Labels: kind: enhancement, release notes: to be added

#4104 Add TaylorSeriesRationalFunction and improve Derivative for univariate rational functions
  doc/ref/ratfun.xml
  lib/ratfun.gd
  lib/ratfunul.gi
Labels: kind: new feature, release notes: to be added, topic: library

#4114 Update Travis CI badge URL (for master)
  README.md
  etc/travis_fastfail.sh
Labels: release notes: not needed, topic: ci, topic: infrastructure

#4113 Update Travis CI badge URL (for stable-4.11)
  README.md
  etc/travis_fastfail.sh
Labels: release notes: not needed, topic: ci, topic: infrastructure

#4118 kernel: move BottomLVars out of TLS
  src/gapstate.h
  src/vars.c
  src/vars.h
Labels: release notes: not needed, topic: kernel
