Repository gap-system/gap, pull requests merged in 2020-12, with the labels that each got.

#4190 kernel: fix syntax error not being reported on REPL
  src/io.c
  tst/testinstall/kernel/scanner.tst
  tst/testspecial/repl-syntax-err.g
  tst/testspecial/repl-syntax-err.g.out
Labels: regression, release notes: not needed

#4186 Improve CoeffientsQadic
  lib/integer.gi
  tst/testinstall/integer.tst
Labels: kind: enhancement, release notes: to be added, topic: performance

#4194 Replace Set(List(l,f)) by Set(l,f)
  benchmark/grpconst/grpconst.g
  benchmark/transgrp/examine4
  benchmark/transgrp/pnormea.g
  hpcgap/lib/fldabnum.gi
  hpcgap/lib/helpbase.gi
  hpcgap/lib/polyrat.gi
  hpcgap/lib/ringpoly.gi
  lib/clashom.gi
  lib/csetperm.gi
  lib/ctbl.gi
  lib/ctblgrp.gi
  lib/ctblmaps.gi
  lib/ctblmono.gi
  lib/ctblperm.gi
  lib/ctblpope.gd
  lib/ctblpope.gi
  lib/cyclotom.gi
  lib/factgrp.gi
  lib/fieldfin.gi
  lib/fldabnum.gi
  lib/galois.gi
  lib/ghom.gi
  lib/ghomfp.gi
  lib/ghomperm.gi
  lib/gpfpiso.gi
  lib/gpprmsya.gi
  lib/grp.gi
  lib/grpffmat.gi
  lib/grpfp.gi
  lib/grplatt.gi
  lib/grppc.gi
  lib/grppcatr.gi
  lib/grppcaut.gi
  lib/grppcint.gi
  lib/grpperm.gi
  lib/helpbase.gi
  lib/ideal.gi
  lib/meataxe.gi
  lib/morpheus.gi
  lib/oprt.gi
  lib/oprtglat.gi
  lib/oprtperm.gi
  lib/package.gi
  lib/polyrat.gi
  lib/randiso.gi
  lib/reesmat.gi
  lib/relation.gi
  lib/ringpoly.gi
  lib/stbcbckt.gi
  lib/wordlett.gi
  tst/testextra/makeperfect.g
  tst/testinstall/trans.tst
  tst/teststandard/helptools.tst
Labels: release notes: not needed, topic: library

#4191 kernel: call ClearError from ReadEval{Command,File}
  src/gap.c
  src/read.c
  src/streams.c
Labels: release notes: not needed, topic: kernel

#4198 Call GAP with `-r` option ...
  bin/BuildPackages.sh
Labels: backport-to-4.11, kind: bug, release notes: not needed, topic: build system

#4200 Disable bracketed paste mode by default
  src/sysfiles.c
Labels: backport-to-4.11, release notes: not needed, topic: kernel
