Repository gap-system/gap, pull requests merged in 2020-10, with the labels that each got.

#4119 kernel: make PrintFunction static
  src/calls.c
  src/calls.h
  src/funcs.c
  src/streams.c
Labels: release notes: not needed, topic: kernel

#4127 Make testspecial more robust against library changes
  tst/testspecial/backtrace.g.out
  tst/testspecial/bad-add.g.out
  tst/testspecial/bad-array-double-1.g.out
  tst/testspecial/bad-array-int-0.g.out
  tst/testspecial/bad-array-string.g.out
  tst/testspecial/bad-minus.g.out
  tst/testspecial/broken-test.g.out
  tst/testspecial/func-and-proc-call-trace.g.out
  tst/testspecial/line-continuation.g.out
  tst/testspecial/method-not-found.g.out
  tst/testspecial/run_gap.sh
  tst/testspecial/stack-depth-rec.g.out
Labels: backport-to-4.11, release notes: not needed, topic: tests

#4126 Add 'gap --version'
  lib/system.g
  src/system.c
Labels: release notes: to be added

#4123 kernel: introduce streq() helper
  src/calls.c
  src/compiler.c
  src/gap.c
  src/gasman.c
  src/io.c
  src/modules.c
  src/profile.c
  src/read.c
  src/saveload.c
  src/scanner.c
  src/streams.c
  src/sysfiles.c
  src/sysstr.h
Labels: release notes: not needed, topic: kernel

#4117 Fix --disable-X for some options in configure
  configure.ac
Labels: kind: bug, release notes: not needed, topic: build system

#4097 kernel: reduce arguments of FuncSHELL
  hpcgap/lib/hpc/consoleui.g
  lib/error.g
  lib/session.g
  src/gap.c
  src/gap.h
  src/streams.c
  tst/testinstall/kernel/gap.tst
Labels: release notes: not needed, topic: kernel

#4129 kernel: merge OpenAppend into OpenOutput
  src/compiler.c
  src/error.c
  src/gap.c
  src/io.c
  src/io.h
  src/streams.c
Labels: release notes: not needed, topic: kernel

#4122 kernel: remove input stream stack
  src/common.h
  src/gap.c
  src/io.c
  src/io.h
  src/read.c
  src/streams.c
  src/streams.h
Labels: release notes: not needed, topic: kernel

#4108 Fix some unexpected error when inverting or computing random elements of algebraic extensions of finite fields of size > 256
  lib/algfld.gi
  tst/teststandard/algext.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: to be added, topic: library

#4137 Fix bug where ? or a pragma comment acted as a semicolon
  src/read.c
  tst/testinstall/kernel/read.tst
  tst/testinstall/kernel/scanner.tst
Labels: kind: bug, release notes: not needed, topic: kernel

#4138 Make ConvertToVectorRepNC more resilient
  hpcgap/lib/vecmat.gi
  lib/vecmat.gi
  tst/testinstall/immutable.tst
Labels: kind: bug, kind: bug: crash, release notes: not needed

#4139 Fix some typos
  CHANGES.md
  CONTRIBUTING.md
  benchmark/transgrp/examine4
  bin/BuildPackages.sh
  dev/NameSpaces.tex
  dev/modules.txt
  doc/dev/main.xml
  etc/ci-gather-coverage.sh
  etc/ci.sh
  grp/perf0.grp
  hpcgap/demo/Echelon.g
  hpcgap/demo/karatsuba.g
  hpcgap/lib/helpbase.gi
  hpcgap/lib/polyrat.gi
  lib/basismut.gd
  lib/csetgrp.gi
  lib/ctblsolv.gd
  lib/factgrp.gi
  lib/function.g
  lib/ghomperm.gi
  lib/grpfp.gi
  lib/grppc.gi
  lib/grpprmcs.gi
  lib/helpbase.gi
  lib/kbsemi.gi
  lib/matrix.gd
  lib/meataxe.gi
  lib/oprt.gi
  lib/permdeco.gd
  lib/polyfinf.gi
  lib/polyrat.gi
  lib/relation.gi
  lib/ringsc.gi
  lib/sgpres.gi
  lib/stbcrand.gi
  lib/tietze.gi
  src/calls.h
  src/compiler.c
  src/cyclotom.c
  src/finfield.c
  src/gasman.c
  src/io.c
  src/io.h
  src/permutat.cc
  src/plist.h
  src/rational.c
  src/scanner.h
  src/streams.c
  src/sysfiles.c
  src/sysfiles.h
  src/system.h
  src/vecffe.c
  src/vecgf2.c
  tst/testspecial/README.md
Labels: release notes: not needed

#4141 buildsys: fix --enable-debug regression
  configure.ac
Labels: regression, release notes: not needed, topic: build system

#4131 kernel: move NrErrLine from GAPState to TypInputFile
  src/gapstate.h
  src/io.c
  src/io.h
  src/scanner.c
  src/scanner.h
  tst/testinstall/kernel/scanner.tst
Labels: release notes: not needed, topic: kernel

#4132 kernel: remove output stream stack
  src/common.h
  src/compiler.c
  src/error.c
  src/error.h
  src/gap.c
  src/io.c
  src/io.h
  src/scanner.c
  src/streams.c
Labels: release notes: to be added, topic: kernel

#4145 Improve errors messages for various set operations
  lib/set.gi
  tst/testinstall/set.tst
Labels: kind: enhancement, release notes: to be added

#4140 Fix compatibility with some old glibc versions
  src/iostream.c
  src/profile.c
Labels: release notes: not needed, topic: kernel

#4152 define GAP_MakeStringWithLen in libgap
  src/libgap-api.c
  src/libgap-api.h
Labels: kind: enhancement, release notes: not needed, topic: libgap

#4149 Better syntax error for an expr when expecting a statement
  src/read.c
  tst/testinstall/error.tst
Labels: kind: enhancement

#4156 Fix compiler warning about nested extern declaration
  src/julia_gc.c
Labels: backport-to-4.11, release notes: not needed, topic: kernel

#4150 buildsys: let 'make clean' do more
  Makefile.rules
Labels: release notes: not needed, topic: build system

#4142 Extend BindConstant, MakeConstantGlobal to all object types
  lib/global.gd
  src/gvars.c
  src/read.c
  tst/testinstall/constant.tst
Labels: release notes: to be added

#4146 Fix encoding of BibEntry(nam) and Cite
  lib/package.gi
Labels: kind: bug: unexpected error, kind: enhancement, release notes: to be added, topic: library

#4162 kernel: fix GetLine2 to correctly check for a stringrep
  src/io.c
Labels: release notes: not needed, topic: kernel
