Repository gap-system/gap, pull requests merged in 2020-08, with the labels that each got.

#4091 kernel: remove STATE(In)
  src/gapstate.h
  src/io.c
  src/io.h
Labels: release notes: not needed, topic: kernel

#4090 buildsys: tweak GAP options for `make check`
  Makefile.rules
Labels: release notes: not needed, topic: build system

#4094 Fix output redirection for firefox other browsers
  lib/helpview.gi
Labels: kind: quirk, release notes: not needed

#4093 Remove references to dev/Updates; update dev manual
  doc/dev/main.xml
  doc/dev/updates.xml
  doc/dev/website.xml
  tst/testutil.g
Labels: release notes: not needed, topic: documentation

#4095 Minor fixes and performance enhancements
  lib/autsr.gi
  lib/gprd.gi
  lib/grp.gi
  lib/matrix.gd
  lib/matrix.gi
  lib/oprtglat.gi
Labels: kind: bug: unexpected error, kind: enhancement, release notes: not needed, topic: library

#4103 Small corrections
  lib/grplatt.gi
  lib/ring.gi
  tst/testbugfix/2020-08-19-Uniz.tst
Labels: kind: bug: unexpected error, kind: bug: wrong result, release notes: not needed, topic: library

#4105 admit an optional third argument in `OrderMod` ...
  lib/numtheor.gd
  lib/numtheor.gi
Labels: kind: enhancement, release notes: to be added, topic: library
