Repository gap-system/gap, pull requests merged in 2020-06, with the labels that each got.

#4047 Install 4ti2 for Travis tests loading 4ti2Interface package
  .travis.yml
Labels: backport-to-4.11, release notes: not needed, topic: tests

#4045 kernel: refactor IntrBegin / IntrEnd and their callers
  src/intrprtr.c
  src/intrprtr.h
  src/read.c
Labels: release notes: not needed, topic: kernel

#4044 Improve sysinfo.gap generation and content
  Makefile.rules
  bin/BuildPackages.sh
  etc/Makefile.gappkg
Labels: kind: enhancement, topic: build system

#4053 Fix the logic for scanning tasks in the Julia GC.
  src/julia_gc.c
Labels: backport-to-4.11, kind: bug, kind: bug: crash, topic: julia

#4059 say explicitly what conjugation is
  doc/ref/language.xml
  lib/oprt.gd
Labels: kind: enhancement, release notes: not needed, topic: documentation

#4060 Fix some sort keys
  doc/ref/language.xml
  doc/ref/string.xml
  lib/ctblfuns.gd
Labels: release notes: not needed

#4063 Update docs for operators on transformations & pperms
  doc/ref/pperm.xml
  doc/ref/trans.xml
Labels: release notes: not needed, topic: documentation

#4058 Refine the logic for scanning Julia stacks.
  src/julia_gc.c
Labels: backport-to-4.11, topic: julia, topic: kernel
