Repository gap-system/gap, pull requests merged in 2020-01, with the labels that each got.

#3811 kernel: replace some uses of Char by char
  src/gapstate.h
  src/io.c
  src/scanner.h
Labels: release notes: not needed, topic: kernel

#3800 Change the use of ", say"
  doc/ref/gappkg.xml
  doc/ref/grphomom.xml
  doc/ref/grplib.xml
  doc/ref/lists.xml
  doc/ref/matrix.xml
  doc/ref/pcgs.xml
  doc/ref/pres.xml
  doc/ref/reesmat.xml
  doc/tut/opers.xml
  grp/imf.gd
  hpcgap/demo/Echelon.g
  hpcgap/lib/basis.gd
  lib/algebra.gd
  lib/algebra.gi
  lib/alghom.gd
  lib/algsc.gd
  lib/algsc.gi
  lib/basis.gd
  lib/basismut.gd
  lib/ctbl.gd
  lib/ctbl.gi
  lib/ctblfuns.gd
  lib/ctblmaps.gd
  lib/ctblmono.gd
  lib/ctblpope.gd
  lib/ctblsymm.gd
  lib/files.gd
  lib/ghom.gd
  lib/grpffmat.gi
  lib/grpfree.gi
  lib/grpmat.gd
  lib/matobj2.gd
  lib/matrix.gd
  lib/mgmfree.gi
  lib/morpheus.gd
  lib/package.gd
  lib/ring.gd
  lib/ringpoly.gd
  lib/ringsc.gi
  lib/sgpres.gd
  lib/sgpres.gi
  lib/straight.gd
  lib/tietze.gd
  lib/tietze.gi
  lib/tom.gd
  lib/upoly.gd
  lib/vspc.gd
  lib/vspchom.gd
  lib/wordass.gd
Labels: release notes: not needed, topic: documentation

#3816 ENHANCE: maintain information about tail indices to relations
  lib/twocohom.gi
Labels: backport-to-4.11, kind: enhancement, release notes: not needed

#3818 kernel: avoid using GAP_PATH_MAX in headers; add sysroots.{c,h}
  Makefile.rules
  src/gap.c
  src/streams.c
  src/sysfiles.c
  src/sysfiles.h
  src/sysopt.h
  src/sysroots.c
  src/sysroots.h
  src/system.c
Labels: release notes: not needed, topic: kernel

#3827 Remove ShortFileNameWindows
  lib/process.gd
  lib/process.gi
Labels: release notes: not needed, topic: kernel

#3824 kernel: only compile workspace support if GASMAN is used
  src/blister.c
  src/bool.c
  src/calls.c
  src/code.c
  src/common.h
  src/cyclotom.c
  src/gap.c
  src/integer.c
  src/macfloat.c
  src/modules.c
  src/objects.c
  src/objects.h
  src/objset.c
  src/opers.c
  src/permutat.cc
  src/plist.c
  src/pperm.cc
  src/precord.c
  src/range.c
  src/rational.c
  src/saveload.c
  src/saveload.h
  src/streams.c
  src/stringobj.c
  src/sysopt.h
  src/system.c
  src/trans.cc
  src/vars.c
  src/weakptr.c
Labels: release notes: not needed, topic: kernel

#3830 kernel: move Start/FinishAndCallFakeFuncExpr to intrprtr.c
  src/intrprtr.c
  src/intrprtr.h
  src/read.c
  src/read.h
Labels: release notes: not needed, topic: kernel

#3829 kernel: add LookupStaticModule helper
  src/modules.c
  src/modules.h
  src/streams.c
Labels: release notes: not needed, topic: kernel

#3837 Fix multiple instances of duplicate words in text
  CONTRIBUTING.md
  doc/changes/changes-4.10.xml
  doc/changes/changes45.xml
  doc/changes/changes47.xml
  doc/dev/lib.xml
  doc/ref/groups.xml
  doc/ref/grphomom.xml
  doc/tut/domain.xml
  grp/perf.grp
  lib/coll.gd
  lib/ctbl.gd
  lib/ctbl.gi
  lib/ctblfuns.gd
  lib/ctblmaps.gd
  lib/ghomfp.gi
  lib/gpfpiso.gi
  lib/grpmat.gd
  lib/grppc.gd
  lib/grppc.gi
  lib/grpramat.gd
  lib/kbsemi.gi
  lib/onecohom.gi
  lib/permutat.g
  lib/ratfun.gd
  lib/ratfun1.gi
  lib/ring.gd
  lib/ring.gi
  lib/ringhom.gi
  lib/tietze.gi
  lib/type.g
  lib/userpref.g
  src/calls.c
  src/dt.c
  src/finfield.h
  src/gasman.h
  src/integer.c
  src/libgap-api.h
  src/objects.h
  src/permutat.cc
  src/plist.c
  src/pperm.cc
  src/scanner.h
  src/systime.c
  src/trans.cc
  tst/testbugfix/2017-06-19-repaction.tst
  tst/testspecial/help.g
  tst/testspecial/help.g.out
Labels: release notes: not needed

#3834 kernel: fix `for` loop regression
  src/read.c
  tst/testinstall/unbound.tst
Labels: regression, release notes: not needed, topic: kernel

#3838 FIX: Made ConfluentMonoidPresentationForGroup an attribute
  lib/twocohom.gd
  lib/twocohom.gi
Labels: release notes: not needed, topic: library

#3833 Request required storage in one allocation in GASMAN
  src/gasman.c
Labels: kind: enhancement, release notes: not needed, topic: kernel

#3840 Move MarkBag* funcs into GCs so they can inline MarkBag
  src/bags.c
  src/bags.inc
  src/boehm_gc.c
  src/gasman.c
  src/julia_gc.c
Labels: backport-to-4.11, kind: enhancement, topic: kernel, topic: performance

#3842 kernel: make MarkAllSubBagsDefault private, use in Julia GC
  src/bags.inc
  src/gasman.c
  src/gasman.h
  src/julia_gc.c
Labels: release notes: not needed, topic: kernel

#3848 kernel: fix OnSets to preserve immutability
  src/listfunc.c
  src/objects.c
  tst/testbugfix/2020-01-13-OnSets-Mutability.tst
Labels: backport-to-4.11, kind: bug, release notes: to be added, topic: kernel

#3847 FIX: Printing of assoc. words if there are iterated powers
  lib/wordrep.gi
  tst/testbugfix/2020-01-13-wordprint.tst
Labels: backport-to-4.10, backport-to-4.11, kind: bug: wrong result, release notes: to be added

#3850 Fix assertion in Factors for polynomials over cyclotomics
  lib/cyclotom.gi
  tst/testinstall/ratfun.tst
Labels: backport-to-4.11, release notes: not needed, topic: library

#3846 etc/bisect.sh: make it work with old build system
  etc/bisect.sh
Labels: kind: enhancement, release notes: not needed

#3843 kernel: don't bother resetting CurrLVars in IntrAbortCoding
  src/intrprtr.c
  src/intrprtr.h
  src/read.c
Labels: release notes: not needed, topic: kernel

#3844 kernel: avoid Intr{Begin,End} calls, remove Exec{Begin,End}
  src/funcs.c
  src/funcs.h
  src/gap.c
  src/gap.h
  src/hpc/threadapi.c
  src/intrprtr.c
  src/intrprtr.h
  src/modules.c
  src/read.c
Labels: release notes: not needed, topic: kernel

#3849 kernel: prevent immutable -> mutable conversion
  src/bags.c
  src/boehm_gc.c
  src/gasman.c
  src/gasman.h
  src/julia_gc.c
Labels: release notes: not needed, topic: kernel

#3796 Remove -B option for overriding the architecture
  doc/ref/run.xml
  lib/system.g
  src/gap.c
  src/sysopt.h
  src/system.c
Labels: release notes: to be added

#3856 ctags: handle BindGlobal, BIND_GLOBAL, DeclareSynonymAttr
  dev/ctags_for_gap
Labels: release notes: not needed

#3859 Travis: use curl instead of wget for bootstrap
  etc/ci-prepare.sh
Labels: release notes: not needed, topic: ci

#3783 Improvements to Automorphism group/Group isomorphism
  doc/ref/groups.xml
  doc/tut/group.xml
  lib/autsr.gi
  lib/claspcgs.gi
  lib/factgrp.gi
  lib/grp.gd
  lib/grp.gi
  lib/grpperm.gd
  lib/grpperm.gi
  lib/morpheus.gd
  lib/morpheus.gi
  lib/oprt.gi
  lib/teaching.g
  tst/testinstall/gprdmat.tst
  tst/teststandard/ctblsymm.tst
  tst/teststandard/opers/AutomorphismGroup.tst
  tst/teststandard/twocohom.tst
Labels: kind: enhancement, release notes: not needed, topic: library

#3861 ENHANCE: Extended range of simple groups
  grp/simple.gd
  grp/simple.gi
  grp/simple2.g
  lib/grp.gi
  tst/teststandard/simplegrpit.tst
Labels: kind: enhancement, kind: new feature, release notes: to be added

#3865 FIX: Induced fitting free setup requires own pcisom
  lib/clashom.gi
  lib/fitfree.gi
  tst/testbugfix/2020-01-22-SubgroupByFittingFreeData.tst
Labels: backport-to-4.11, kind: bug, kind: bug: unexpected error, release notes: to be added

#3867 julia: remove the need for GAPTypes.jl
  configure.ac
  src/julia_gc.c
Labels: backport-to-4.11, topic: julia, topic: kernel

#3870 kernel: simplify FuncIS_SUBSET_SET
  src/set.c
Labels: release notes: not needed, topic: kernel

#3857 Replace some uses of DeclareGlobalVariable/InstallValue
  hpcgap/lib/helpbase.gi
  hpcgap/lib/primality.gi
  hpcgap/lib/tuples.gi
  hpcgap/lib/vec8bit.gi
  hpcgap/lib/vecmat.gi
  lib/grpfp.gi
  lib/helpbase.gd
  lib/helpbase.gi
  lib/helpview.gd
  lib/helpview.gi
  lib/listcoef.gd
  lib/listcoef.gi
  lib/mat8bit.gd
  lib/mat8bit.gi
  lib/padics.gd
  lib/padics.gi
  lib/primality.gd
  lib/primality.gi
  lib/stbcbckt.gd
  lib/stbcbckt.gi
  lib/streams.gd
  lib/streams.gi
  lib/tuples.gd
  lib/tuples.gi
  lib/vec8bit.gd
  lib/vec8bit.gi
  lib/vecmat.gd
  lib/vecmat.gi
  src/costab.c
  src/vec8bit.c
  src/vecgf2.c
Labels: release notes: not needed

#3872 Three fixes for accidental breakages in recent changes
  grp/simple.gi
  lib/fitfree.gi
  lib/morpheus.gi
  tst/testinstall/opers/SimpleGroup.tst
Labels: backport-to-4.11, kind: bug, regression, release notes: not needed

#3877 Remove kernel operation Elm0List; revise Elm0ListObject
  hpcgap/lib/vec8bit.gi
  hpcgap/lib/vecmat.gi
  lib/list.gd
  lib/list.gi
  lib/mat8bit.gi
  lib/vec8bit.gi
  lib/vecmat.gi
  src/blister.c
  src/lists.c
  src/plist.c
  tst/testinstall/kernel/lists.tst
Labels: release notes: not needed

#3875 kernel: avoid PLAIN_PLIST in PermList
  src/permutat.cc
  tst/testinstall/perm.tst
Labels: release notes: not needed, topic: kernel

#3873 kernel: don't use PLAIN_LIST in OnTuples, OnSets
  src/listfunc.c
  src/permutat.cc
  src/pperm.cc
  src/trans.cc
  tst/testinstall/kernel/lists.tst
  tst/testinstall/perm.tst
  tst/testinstall/trans.tst
Labels: release notes: not needed, topic: kernel
