Repository gap-system/gap, pull requests merged in 2021-11, with the labels that each got.

#4683 Faster Wreath Product `Embedding`
  lib/gprdperm.gi
Labels: topic: performance, topic: library, release notes: use title

#4692 Test Julia integration with Julia 1.6.3
  dev/ci-configure-gap.sh
Labels: release notes: not needed, topic: ci, topic: julia

#4702 CI: cancel redundant PR builds
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci

#4703 fixed `Coefficients` for large finite fields created via a polynomial
  lib/fieldfin.gi
  tst/testinstall/ffe.tst
Labels: kind: bug, kind: bug: wrong result, topic: library, release notes: use title

#4711 CI: limit concurrency for PR builds but not for master
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci
