Repository gap-system/gap, pull requests merged in 2021-08, with the labels that each got.

#4621 Add `GAP_NewRange`, `GAP_NewObjIntFromInt`, `GAP_ValueInt` to the libgap API
  src/exprs.c
  src/intrprtr.c
  src/libgap-api.c
  src/libgap-api.h
  src/range.c
  src/range.h
  tst/testlibgap/api.c
  tst/testlibgap/api.expect
Labels: release notes: use title, topic: julia, topic: kernel, topic: libgap

#4618 kernel: simplify FuncREAD_COMMAND_REAL implementation
  src/streams.c
  tst/testinstall/kernel/streams.tst
Labels: release notes: not needed, topic: kernel

#4612 Make `MappedWord` handle inverses better
  lib/word.gd
  lib/wordass.gi
  lib/wordlett.gi
  tst/testinstall/wordrep.tst
Labels: kind: enhancement, do not merge, topic: library, release notes: not needed

#4626 Performance improvements for words and a small bugfix
  lib/autsr.gi
  lib/sgpres.gi
  lib/wordrep.gi
  tst/testbugfix/2021-08-05-Automorphisms.tst
Labels: kind: enhancement, kind: bug: unexpected error, release notes: not needed, priority: high

#4633 kernel: better panic messages in echoandcheck
  src/sysfiles.c
Labels: topic: kernel, release notes: not needed

#4634 FIX: subgroup conjugacy for cyclic permutation groups
  lib/stbcbckt.gi
Labels: kind: bug: wrong result, backport-to-4.11

#4628 Cleanup some GAP library code related to iostreams
  lib/streams.gi
Labels: topic: library, release notes: not needed

#4602 Improve documentation and argument checks for `StabChainBaseStrongGenerators`
  lib/stbc.gd
  lib/stbc.gi
  tst/testinstall/stbc.tst
Labels: topic: documentation, topic: library, release notes: not needed, priority: low

#4544 Forbid installing an operation as method for itself
  lib/oper1.g
  tst/testbugfix/2021-03-25-InstallMethod.tst
Labels: kind: bug, kind: bug: crash, release notes: use title

#4547 Improve chapter 4 "The Programming Language" of the reference manual
  doc/ref/language.xml
Labels: topic: documentation

#4638 Relax correctness check of Test pragmas
  lib/test.gi
  tst/testspecial/broken-test-1.tst
Labels: kind: enhancement, topic: tests
