Repository gap-system/gap, pull requests merged in 2021-04, with the labels that each got.

#4359 Fix ctags_for_gap file
  etc/ctags_for_gap
Labels: release notes: not needed

#4358 Minor optimizations related to AsPlist
  hpcgap/lib/vec8bit.gi
  hpcgap/lib/vecmat.gi
  lib/list.gi
  lib/vec8bit.gi
  lib/vecmat.gi
Labels: release notes: not needed, topic: library

#4363 Improve ctags_for_gap
  etc/ctags_for_gap
Labels: release notes: not needed

#4346 CI: fix coverage reporting
  dev/ci-upload-coverage.sh
Labels: release notes: not needed, topic: ci, topic: infrastructure

#4360 Update ctags.readme.txt
  etc/ctags.readme.md
  etc/ctags.readme.txt
Labels: kind: enhancement, release notes: not needed

#4361 added an `\in` method for `GO(e,d,q)` and `SO(e,d,q)` that is based on the stored invariant quadratic form
  lib/grpmat.gi
  tst/testinstall/grp/classic-G.tst
  tst/testinstall/grp/classic-forms.tst
Labels: kind: enhancement, release notes: use title, topic: library

#4365 Merge the Cygwin workflow with the main CI file
  .github/workflows/CI.yml
  .github/workflows/cygwin-windows.yml
Labels: release notes: not needed, topic: ci, topic: workflow

#4369 Move tst/test-matobj/MultVector.tst so that it is actually used
  tst/testinstall/MatrixObj/MultVector.tst
Labels: release notes: not needed, topic: tests

#4371 Increase robustness of a test relying on timing
  tst/testbugfix/2006-08-28-t00151.tst
Labels: release notes: not needed, topic: tests

#4385 write matrices of orth. groups over smallest fields
  grp/classic.gi
Labels: kind: enhancement, release notes: not needed, topic: library

#4378 CI: Do not install readline for macOS job
  .github/workflows/CI.yml
Labels: kind: discussion, os: macos, release notes: not needed, topic: ci

#4381 Update config.guess and config.sub
  cnf/config.guess
  cnf/config.sub
  cnf/install-sh
Labels: release notes: not needed, topic: build system

#4392 CI: remove AppVeyor integration
  .appveyor.yml
  README.md
  dev/ci-gather-coverage.sh
  dev/ci.sh
  dev/releases/make_archives.py
Labels: release notes: not needed, topic: ci

#4397 Import CopyToVectorRep(NC) from HPC-GAP
  hpcgap/lib/vecmat.gi
  lib/vecmat.gi
Labels: release notes: not needed, topic: HPC-GAP unification, topic: library

#4396 FIX: Storage of partial maximal subgroup lists
  lib/csetgrp.gi
  lib/gpprmsya.gi
  lib/grp.gd
  lib/grp.gi
  lib/grplatt.gi
  lib/grpnice.gi
  lib/grppcatr.gi
  lib/maxsub.gi
  lib/pcgsperm.gi
  tst/testbugfix/2021-04-13-TryMaximals.tst
Labels: kind: bug: wrong result, priority: high, release notes: to be added

#4401 Remove MakeVector
  lib/matobj.gi
  lib/matobj2.gd
Labels: release notes: not needed, topic: library

#4402 Reduce HPC-GAP diffs
  hpcgap/lib/basis.gd
  hpcgap/lib/basis.gi
  hpcgap/lib/cmdleditx.g
  hpcgap/lib/integer.gi
  hpcgap/lib/polyrat.gi
  hpcgap/lib/userpref.g
  hpcgap/lib/vec8bit.gi
  hpcgap/lib/vecmat.gi
  lib/cmdleditx.g
  lib/vecmat.gi
Labels: release notes: not needed, topic: HPC-GAP unification, topic: library

#4393 Slack notifications for GH Actions
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: infrastructure

#4407 Fix crashes when accessing `mat[i,j]` and `mat[i]` is unbound
  src/lists.c
  tst/testinstall/listindex.tst
Labels: kind: bug, kind: bug: crash

#4405 Update ax_pthread.m4 to latest upstream version
  cnf/m4/ax_pthread.m4
Labels: release notes: not needed, topic: build system

#4386 Restore some functionality of the `--strict` option to the `bin/BuildPackages.sh` script
  bin/BuildPackages.sh
Labels: kind: bug, release notes: to be added

#4394 buildsys: improve cross compilation support
  Makefile.rules
  cnf/build-extern.sh
Labels: release notes: not needed, topic: build system, topic: julia

#4400 Add safety checks for objects with memory
  lib/memory.gi
  tst/testinstall/memory.tst
Labels: kind: enhancement, release notes: not needed, topic: library

#4411 Collection of small fixes and improvements that do not merit an own PR each
  grp/simple.gi
  lib/autsr.gi
  lib/combinat.gd
  lib/combinat.gi
  lib/csetgrp.gi
  lib/ghomfp.gi
  lib/oprt.gi
  lib/sgpres.gi
  lib/twocohom.gi
  tst/testextra/grplatt.tst
Labels: kind: bug: unexpected error, kind: enhancement, kind: performance, release notes: to be added

#4413 remove an irritating `if` statement in `MethodsOperation`
  lib/methsel.g
  lib/oper.g
  lib/oper1.g
  src/c_oper1.c
  src/hpc/c_oper1.c
  tst/testinstall/varargs.tst
Labels: kind: general proposed change, release notes: not needed, topic: library

#4418 Fix warning produced by autoconf >= 2.70
  configure.ac
Labels: release notes: not needed, topic: build system

#4419 Slack Notifications: send current status, not previous
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#4421 CI: detect failure to run `make docomp` nicely again
  bin/BuildPackages.sh
Labels: release notes: not needed, topic: ci

#4372 Check arguments to `FreeSemigroup` more thoroughly
  lib/semigrp.gd
  lib/smgrpfre.gi
  tst/testbugfix/2021-04-08-empty-FreeSemigroup.tst
  tst/testinstall/smgrpfre.tst
Labels: kind: bug, kind: bug: unexpected error, kind: bug: wrong result, release notes: to be added, topic: library

#4425 Refactor some of the release scripts
  dev/releases/make_archives.py
  dev/releases/make_github_release.py
  dev/releases/utils.py
Labels: release notes: not needed, topic: infrastructure, topic: workflow

#4420 buildsys: don't attempt to recreate missing *.d files
  Makefile.rules
  dev/ci.sh
Labels: kind: bug, regression, release notes: not needed, topic: build system

#4426 Remove an unstable test
  tst/testbugfix/2006-08-28-t00151.tst
Labels: release notes: not needed, topic: tests

#4428 docs: mention FirstOp, LastOp, ForAllOp, etc.
  lib/coll.gd
  lib/list.gd
Labels: topic: documentation

#4427 Fix `QuaternionAlgebra` bug that caused `QuaternionAlgebra( [1], 2, 5 ).1` to error the second time it was invoked
  lib/algsc.gi
Labels: kind: bug, kind: bug: unexpected error, release notes: to be added, release notes: use title, topic: HPC-GAP unification, topic: library

#4433 CI: split and refactor CI scripts
  .github/workflows/CI.yml
  .github/workflows/release.yml
  dev/ci-build-gap.sh
  dev/ci-configure-gap.sh
  dev/ci-download-pkgs.sh
  dev/ci-download.sh
  dev/ci-gather-coverage.sh
  dev/ci-prepare.sh
  dev/ci.sh
Labels: release notes: not needed, topic: ci

#4389 Automate creating Windows installers for GAP releases with GitHub Actions
  .github/workflows/release.yml
  dev/releases/download_release_archive.py
  dev/releases/upload_files_to_github_release.py
Labels: os: windows, release notes: not needed, topic: infrastructure, topic: workflow

#4435 CI: remove coveralls integration
  .github/workflows/CI.yml
  README.md
  dev/ci-coveralls-merge.py
  dev/ci-gather-coverage.sh
  dev/ci-upload-coverage.sh
Labels: release notes: not needed, topic: ci, topic: infrastructure

#4434 Add scheduled and manual triggers for the CI GitHub Actions workflow
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#4436 CI: revise coverage gathering and uploading
  .github/workflows/CI.yml
  dev/ci-gather-coverage.sh
  dev/ci-upload-coverage.sh
Labels: release notes: not needed, topic: ci, topic: infrastructure

#4429 Remove src/c_*.c files from repository
  .github/workflows/CI.yml
  Makefile.rules
  README.hpcgap.md
  cnf/gap-c-gen.sh
  dev/ci.sh
  src/c_oper1.c
  src/c_type1.c
  src/compstat_empty.c
  src/hpc/c_oper1.c
  src/hpc/c_type1.c
Labels: topic: build system

#4440 fixed a family relation in a method installation
  lib/rwsgrp.gi
Labels: kind: bug, release notes: not needed, topic: library

#4439 fixed `ExamplesReportDiff`
  tst/testmanuals.g
Labels: kind: bug, kind: bug: unexpected error, release notes: not needed, topic: documentation, topic: tests

#4437 Don't hardcode `lib/oper1.g` line numbers in tests
  src/streams.c
  tst/testinstall/opers/LocationFunc.tst
  tst/testinstall/varargs.tst
  tst/testspecial/print-compiled-func.g
  tst/testspecial/print-compiled-func.g.out
Labels: release notes: not needed, topic: tests

#4450 Remove race condition in memory-checking
  src/sysmem.c
Labels: release notes: not needed, topic: kernel

#4442 Fix crash when incorrectly accessing a compressed vector `v` via `v{...}[...]` or `v{...}{...}` as if it was a matrix
  src/lists.c
  tst/testbugfix/2013-03-12-t00285.tst
Labels: kind: bug, kind: bug: crash, release notes: use title, topic: kernel

#4444 Document an optional argument of `NewFilter`
  lib/filter.g
Labels: kind: enhancement, release notes: not needed, topic: documentation, topic: library

#4447 Correct relations `QuaternionAlgebra` documentation
  lib/algebra.gd
Labels: release notes: not needed, topic: documentation
