Repository gap-system/gap, pull requests merged in 2021-07, with the labels that each got.

#4595 Consolidate GaussianIntegers/Rationals code
  doc/ref/makedocreldata.g
  hpcgap/lib/integer.gi
  lib/cyclotom.gd
  lib/cyclotom.gi
  lib/fldabnum.gd
  lib/fldabnum.gi
  lib/gaussian.gd
  lib/gaussian.gi
  lib/integer.gd
  lib/integer.gi
  lib/rational.gi
  lib/read3.g
Labels: release notes: not needed, topic: library

#4600 kernel: replace `SyWriteandcheck` by `echoandcheck`
  src/sysfiles.c
Labels: release notes: not needed, topic: kernel

#4599 ENHANCE: `PositionSublist` uses `Position` to search for first entry
  lib/list.gi
  tst/testinstall/list.tst
Labels: kind: enhancement, priority: high

#4597 Improvements around the MTC (and two ad-hoc fixes)
  lib/grpfp.gi
  lib/grplatt.gd
  lib/sgpres.gi
  lib/tietze.gd
  lib/tietze.gi
  lib/twocohom.gd
  lib/twocohom.gi
  tst/teststandard/twocohom.tst
Labels: kind: enhancement

#4590 Expand the manual entry for `RecNames`
  lib/record.gd
Labels: release notes: not needed, topic: documentation

#4605 Remove duplicate entry in `COPYRIGHT` file
  COPYRIGHT
Labels: release notes: not needed

#4604 Add Bray/Holt/Roney-Dougal 2013 to the GAP bibliography
  doc/manualbib.xml
  grp/simple.gi
Labels: release notes: not needed, topic: documentation

#4608 kernel: move serializer state from GAPState to stack
  src/hpc/serialize.c
  src/hpc/serialize.h
Labels: release notes: not needed, topic: HPC-GAP, topic: kernel

#4607 kernel: adapt Julia GC code for Julia 1.7
  src/julia_gc.c
Labels: release notes: not needed, topic: julia, topic: kernel

#4601 kernel: fix `echoandcheck` error messages
  src/sysfiles.c
Labels: release notes: not needed, topic: kernel

#4615 kernel: get rid of CATCH_ERROR macro
  src/read.c
Labels: release notes: not needed, topic: kernel

#4619 kernel: reduce calls to `SetRecursionDepth(0)`
  src/error.c
  src/gap.c
  src/streams.c
Labels: release notes: not needed, topic: kernel

#4617 kernel: track try/catch nesting depth
  Makefile.rules
  src/error.h
  src/gapstate.h
  src/profile.c
  src/sysjmp.h
  src/trycatch.c
  src/trycatch.h
Labels: topic: julia, topic: kernel, topic: libgap

#4620 buildsys: generate cnf/GAP-VERSION-FILE in builddir, not srcdir
  Makefile.rules
Labels: release notes: not needed, topic: build system

#4623 Fix DescribesInvariantQuadraticForm, etc
  grp/classic.gd
Labels: release notes: not needed, topic: library

#4622 Speedup precomputation in AlgebraicExtension
  lib/algfld.gi
Labels: topic: library, topic: performance
