Repository gap-system/gap, pull requests merged in 2021-09, with the labels that each got.

#4651 Improvements to rewriting systems and 2-cohomology
  doc/ref/grppc.xml
  grp/simplerew.grp
  lib/gpfpiso.gi
  lib/grppcext.gd
  lib/grppcext.gi
  lib/twocohom.gd
  lib/twocohom.gi
Labels: kind: enhancement, release notes: not needed

#4658 CI: wrap releases workflow: install Latex more robustly
  .github/workflows/release.yml
Labels: kind: bug, release notes: not needed, topic: ci

#4648 Add special cases to `Transitivity` for a permgroup with known size: natural An and Sn
  lib/oprtperm.gi
  tst/testinstall/oprtperm.tst
Labels: kind: enhancement, topic: performance, topic: library, release notes: not needed

#4653 added `IsQuasisimpleGroup`, `IsQuasisimpleCharacterTable`
  doc/ref/groups.xml
  lib/ctbl.gd
  lib/ctbl.gi
  lib/grp.gd
  lib/grp.gi
  lib/overload.g
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, kind: bug: wrong result, topic: library, release notes: use title

#4654 adjusted a statement about `InfoObsolete`
  lib/obsolete.gd
Labels: topic: documentation, release notes: not needed

#4665 Let `RootSystem` use the correct field for determining eigenvectors
  lib/alglie.gi
  tst/testbugfix/2021-09-25-RootSystem.tst
Labels: kind: bug, kind: bug: wrong result, release notes: to be added

#4664 FIX: wrong Generators of Matrix Wreath Product with Intransitive Top Group.
  lib/gprdmat.gi
  tst/testbugfix/2021-09-22-MatWreathProduct.tst
Labels: kind: bug, kind: bug: wrong result, release notes: use title

#4611 Improve docs of StabChain
  doc/ref/grpperm.xml
Labels: kind: enhancement, topic: documentation, release notes: not needed
