Repository gap-system/gap, pull requests merged in 2021-02, with the labels that each got.

#4237 Revert accidentally-reintroduced downranking of a MatrixObj method
  lib/matobj.gi
Labels: release notes: not needed, topic: library

#4233 kernel: silence compiler warnings in readline headers
  src/sysfiles.c
  src/system.c
Labels: release notes: not needed, topic: kernel

#4234 kernel: use RTLD_LOCAL to dlopen kernel extensions
  src/modules.c
Labels: release notes: not needed, topic: kernel

#4242 another change for `PAGER_BUILTIN`
  lib/pager.gi
Labels: kind: bug, kind: bug: unexpected error, release notes: not needed, topic: library

#4219 Performance additions to generic 2-cohomology and Automorphism group/Isomorphism test
  lib/autsr.gi
  lib/csetgrp.gi
  lib/gpfpiso.gi
  lib/grp.gd
  lib/grp.gi
  lib/grplatt.gd
  lib/grplatt.gi
  lib/morpheus.gi
  lib/twocohom.gi
  tst/testbugfix/2021-02-07-IntermediateGroup.tst
  tst/teststandard/grpprmcs.tst
Labels: kind: bug, kind: enhancement, kind: performance, release notes: to be added

#4201 Add optional transformFunction to Test()
  lib/test.gi
Labels: kind: enhancement, release notes: to be added

#4250 coverage: ignore grp/*.grp
  .codecov.yml
Labels: release notes: not needed, topic: ci

#4255 Fix some "lost" entries in the CHANGES.md
  CHANGES.md
Labels: backport-to-4.11, release notes: not needed

#4254 buildsys: rename a few helper scripts
  Makefile.rules
  cnf/gap-c-gen.sh
  cnf/gap-version-gen.sh
  cnf/regen-symlink.sh
  configure.ac
Labels: backport-to-4.11, release notes: not needed, topic: build system

#4252 Add .gitattributes with `* text=auto`
  .gitattributes
Labels: backport-to-4.11, release notes: not needed

#4253 buildsys: overhaul `make distclean`
  Makefile.rules
Labels: backport-to-4.11, release notes: not needed, topic: build system

#4263 Remove leftovers from Travis integration
  .travis.yml
  README.md
  etc/travis_fastfail.sh
Labels: backport-to-4.11, release notes: not needed, topic: infrastructure

#4259 fixed an incomplete sentence in the manual
  lib/mapping.gd
Labels: gapdays2021-spring, kind: enhancement, release notes: not needed, topic: documentation

#4261 buildsys: simplify make clean/distclean code
  Makefile.rules
Labels: release notes: not needed, topic: build system

#4265 Codecov: disable PR comments, enable informational statuses
  .codecov.yml
Labels: release notes: not needed, topic: infrastructure

#4267 buildsys: fix Makefile build order for GMP, zlib
  Makefile.rules
Labels: gapdays2021-spring, regression, topic: build system

#4269 Remove obsolete rsync code
  dev/DistributionUpdate/rsyncserv/CHANGES
  dev/DistributionUpdate/rsyncserv/README
  dev/DistributionUpdate/rsyncserv/gapsync/CollectDistribution
  dev/DistributionUpdate/rsyncserv/gapsync/CreateWorkspace.sh
  dev/DistributionUpdate/rsyncserv/gapsync/FinishInstallCarat
  dev/DistributionUpdate/rsyncserv/gapsync/InstForRsync32
  dev/DistributionUpdate/rsyncserv/gapsync/InstForRsync64
  dev/DistributionUpdate/rsyncserv/gapsync/README
  dev/DistributionUpdate/rsyncserv/gapsync/gap.sh
  dev/DistributionUpdate/rsyncserv/gapsync/gap64.sh
  dev/DistributionUpdate/rsyncserv/gapsync/gap64L
  dev/DistributionUpdate/rsyncserv/gapsync/gapL
  dev/DistributionUpdate/rsyncserv/gapsync/gapsync
  dev/DistributionUpdate/rsyncserv/gapsync/gapsync.issyncdir
  dev/DistributionUpdate/rsyncserv/gapsync/pargap.sh
  dev/DistributionUpdate/rsyncserv/gapsync/pargap64.sh
  dev/DistributionUpdate/rsyncserv/gapsync/patchelf
  dev/DistributionUpdate/rsyncserv/gapsync/patchelf.README
  dev/DistributionUpdate/rsyncserv/gapsync/postgapsynchook.g
  dev/DistributionUpdate/rsyncserv/gapsync/postsync
  dev/DistributionUpdate/rsyncserv/gapsync/read4tail.g
  dev/DistributionUpdate/rsyncserv/gapsync/remove
  dev/DistributionUpdate/rsyncserv/gapsync/xgap.sh
  dev/DistributionUpdate/rsyncserv/index.html
  dev/DistributionUpdate/rsyncserv/motd
  dev/DistributionUpdate/rsyncserv/rsyncd.conf
  dev/DistributionUpdate/rsyncserv/rsyncserv.css
  dev/DistributionUpdate/rsyncserv/startrsyncserver
  dev/DistributionUpdate/rsyncserv/swapwithXXX
Labels: gapdays2021-spring, release notes: not needed

#4264 Sort the content of `dev` and `etc` directories
  .appveyor.yml
  .ctags
  .github/workflows/CI.yml
  Makefile.rules
  cnf/download.sh
  dev/bisect.sh
  dev/ci-coveralls-merge.py
  dev/ci-download.sh
  dev/ci-gather-coverage.sh
  dev/ci-prepare.sh
  dev/ci-run-codecov.sh
  dev/ci.sh
  dev/getlabels
  etc/README.md
  etc/ctags.readme.txt
  etc/ctags_for_gap
Labels: backport-to-4.11, gapdays2021-spring, release notes: not needed

#4270 buildsys: more make (dist)clean tweaks
  Makefile.rules
Labels: backport-to-4.11-DONE, gapdays2021-spring, release notes: not needed, topic: build system

#4274 Enable color prompt by default
  lib/colorprompt.g
Labels: gapdays2021-spring, release notes: to be added

#4275 Enable SaveAndRestoreHistory by default
  lib/cmdledit.g
Labels: release notes: to be added

#4251 Initial Cygwin github action
  .github/workflows/cygwin-windows.yml
Labels: gapdays2021-spring, release notes: not needed, topic: ci

#3355 Allow packages to use ISO 8601 dates in their PackageInfo.g
  lib/package.gi
  tst/testinstall/package.tst
Labels: gapdays2019-spring, gapsingular2019, kind: enhancement, release notes: to be added

#4278 adjust the documentation of `ColorPrompt`
  lib/colorprompt.g
Labels: release notes: not needed, topic: documentation

#4280 Don't freak out if a package has an empty or short Date
  lib/package.gi
Labels: regression, release notes: not needed, topic: packages

#4258 libgap: save/restore recursion depth
  src/libgap-api.c
Labels: backport-to-4.11, release notes: to be added, topic: kernel, topic: libgap

#4284 Minor changes to dev/releases/README.md
  dev/releases/README.md
Labels: gapdays2021-spring, release notes: not needed, topic: infrastructure

#4287 GH Actions: some tweaks
  dev/releases/README.md
  dev/releases/make_archives.py
  dev/releases/make_github_release.py
Labels: release notes: not needed, topic: infrastructure

#4288 buildsys: change bootstrap targets to fetch from GitHub
  Makefile.rules
Labels: backport-to-4.11, release notes: not needed, topic: build system, topic: infrastructure

#4291 Enable wider compatibility for `bin/BuildPackages.sh --parallel`
  bin/BuildPackages.sh
Labels: backport-to-4.11, release notes: not needed, topic: build system

#4290 dev/releases: PackageInfos to JSON script
  dev/releases/PackageInfos-to-JSON.g
  dev/releases/make_archives.py
Labels: release notes: not needed, topic: infrastructure

#4293 Tweak package-infos.json format
  dev/releases/PackageInfos-to-JSON.g
Labels: release notes: not needed, topic: infrastructure
