Repository gap-system/gap, pull requests merged in 2021-03, with the labels that each got.

#4299 PackageInfos-to-JSON.g: add InstallationPath back
  dev/releases/PackageInfos-to-JSON.g
Labels: backport-to-4.11, release notes: not needed

#4301 Fix make distclean
  Makefile.rules
Labels: release notes: not needed, topic: build system

#4300 Add GitHub Action for automatic release generation
  .github/workflows/release.yml
Labels: backport-to-4.11, release notes: not needed, topic: infrastructure

#4309 update_website.py: remove superfluous quotes
  dev/releases/update_website.py
Labels: backport-to-4.11, release notes: not needed

#4310 CHANGES.md: list of package updates now is a Markdown list
  CHANGES.md
Labels: backport-to-4.11, release notes: not needed

#4312 release month is March not February
  CHANGES.md
Labels: backport-to-4.11, release notes: not needed

#4170 Use colors in output of `Test`
  dev/ci.sh
  lib/test.gi
  tst/testmanuals.g
  tst/testspecial/run_gap.sh
Labels: kind: enhancement, release notes: to be added, topic: tests

#4307 Upload some artifacts for "nightly releases"
  .github/workflows/release.yml
Labels: release notes: not needed

#4315 Make CI action upload manuals
  .github/workflows/CI.yml
Labels: backport-to-4.11, release notes: not needed, topic: ci

#4317 fixed `Cite()`; it had used the number of the day, not the year
  lib/package.gi
Labels: backport-to-4.11, kind: bug, kind: bug: wrong result, release notes: use title

#4296 Allow function-call syntax for evaluating univariate polynomials
  hpcgap/lib/ratfun.gi
  lib/ratfun.gd
  lib/ratfun.gi
  tst/testinstall/ratfun.tst
  tst/testinstall/ratfun_gf5.tst
Labels: kind: enhancement, release notes: use title

#4322 Test LowLayerSubgroups only with TomLib package
  tst/testextra/grpperm.tst
Labels: release notes: not needed, topic: tests

#4320 FIX: Outer automorphisms of certain Chevalley groups.
  grp/simple.gi
  tst/testbugfix/2006-08-28-t00151.tst
  tst/testbugfix/2021-03-15-chevallaut.tst
Labels: backport-to-4.11, kind: bug: wrong result, priority: high, release notes: to be added

#4319 Small performance additions and functionality improvements
  lib/ctbl.gd
  lib/factgrp.gd
  lib/factgrp.gi
  lib/gpfpiso.gi
  lib/grpfp.gi
  lib/grppcext.gi
  lib/oprt.gi
Labels: kind: enhancement, kind: new feature, kind: performance, release notes: not needed

#4324 Improve DataAboutSimpleGroup
  grp/simple.gi
Labels: kind: enhancement, release notes: not needed, topic: library

#4329 Change some declarations IsGroup → IsSemigroup
  lib/gprd.gd
  lib/grp.gd
Labels: release notes: not needed, topic: library

#4327 Fix InvariantQuadraticForm for Omega(-1, 2*d, 2^n)
  grp/classic.gi
  tst/testinstall/grp/classic-forms.tst
Labels: kind: bug, kind: bug: wrong result, release notes: to be added

#4335 kernel: fix error for missing } in multi arg lambda
  src/read.c
  tst/testinstall/kernel/read.tst
Labels: kind: quirk, release notes: not needed, topic: kernel

#4333 added `GO(1,q)`, `SO(1,q)`, `Omega(1,q)`, `Omega(-1,2,q)`
  grp/classic.gd
  grp/classic.gi
  tst/testinstall/grp/classic-G.tst
  tst/testinstall/grp/classic-S.tst
  tst/testinstall/grp/classic-forms.tst
Labels: kind: enhancement, release notes: use title, topic: library

#4334 added the group constructors `PGO` and `PSO`
  doc/ref/grplib.xml
  grp/classic.gd
  tst/testinstall/grp/classic-PG.tst
  tst/testinstall/grp/classic-PS.tst
Labels: kind: enhancement, release notes: use title, topic: library

#4337 Partially prepare grp/classic.gi for MatrixObj
  grp/classic.gi
Labels: release notes: not needed, topic: library

#4295 Add OpenExternal, a function for opening files in the OS
  doc/ref/streams.xml
  lib/streams.gd
  lib/streams.gi
Labels: kind: new feature, release notes: use title, topic: library

#4332 Use internal PLAIN_LIST_COPY to implement PlainListCopy, and document
  doc/ref/lists.xml
  hpcgap/lib/vec8bit.gi
  hpcgap/lib/vecmat.gi
  lib/list.gd
  lib/list.gi
  lib/mat8bit.gi
  lib/sparselistgen.gi
  lib/vec8bit.gi
  lib/vecmat.gi
  src/lists.c
  tst/testinstall/list.tst
Labels: release notes: to be added

#4342 Refactor PutLine2
  src/io.c
Labels: release notes: not needed, topic: kernel

#4350 Fix ZeroVector for an integer and a plist vector
  lib/matobjplist.gi
  tst/testinstall/MatrixObj/ZeroVector.tst
Labels: kind: bug, release notes: not needed, topic: library

#4354 CI: rename a script, tweak phrasing
  .appveyor.yml
  .github/workflows/CI.yml
  dev/ci-gather-coverage.sh
  dev/ci-run-codecov.sh
  dev/ci-upload-coverage.sh
Labels: release notes: not needed, topic: ci, topic: infrastructure

#4347 Restore CopySubVector argument order to it original state
  lib/matobj.gi
  lib/matobj2.gd
  tst/testinstall/MatrixObj/CopySubVector.tst
Labels: release notes: not needed, topic: library

#4331 Speed up building stabchain from base and strong generators
  lib/stbc.gi
  tst/testinstall/stabchain.tst
Labels: kind: performance, release notes: to be added, topic: library, topic: performance

#4348 Use PositionNonZero in Meataxe code
  lib/meatauto.gi
Labels: release notes: not needed, topic: library

#4353 consider implied filters in `ApplicableMethodTypes`
  lib/methwhy.g
Labels: kind: bug, release notes: not needed, topic: library

#4352 Add basic tests for SMTX_NewEqns, SMTX_NullspaceEqns
  tst/testinstall/meatauto.tst
Labels: release notes: not needed, topic: tests
