Repository gap-system/gap, pull requests merged in 2021-01, with the labels that each got.

#4207 add the groups PGammaL, PSigmaL
  doc/ref/grplib.xml
  grp/classic.gd
  tst/testinstall/grp/classic-PG.tst
  tst/testinstall/grp/classic-PS.tst
Labels: kind: enhancement, release notes: to be added, topic: library

#4206 fix DirectoriesPackageLibrary/Programs
  lib/package.gi
Labels: kind: bug, kind: bug: wrong result, release notes: to be added, topic: packages

#4213 fixed `HELP_SEARCH_ALTERNATIVES`
  hpcgap/lib/helpbase.gi
  lib/helpbase.gi
Labels: kind: bug, kind: bug: wrong result, release notes: not needed, topic: documentation

#4212 inside `HELP`, give access to the original search string
  hpcgap/lib/helpbase.gi
  lib/helpbase.gi
Labels: backport-to-4.11, kind: enhancement, release notes: not needed, topic: documentation, topic: julia

#4210 Update Julia integration
  src/julia_gc.c
Labels: backport-to-4.11, topic: julia, topic: kernel

#4214 Add a tiny optimisation to Intersection2 for perm groups
  lib/stbcbckt.gi
  tst/testinstall/stbcbckt.tst
Labels: kind: performance, release notes: not needed, topic: library

#4216 Backport some Julia changes to 4.11
  src/julia_gc.c
Labels: topic: julia, topic: kernel

#4218 Julia: fix usage in libgap mode; more GC safety
  src/julia_gc.c
Labels: backport-to-4.11, release notes: not needed, topic: julia, topic: kernel

#4222 Always define DeclareObsoleteSynonym{Attr,}
  lib/init.g
  lib/obsolete.g
  lib/obsolete.gd
Labels: backport-to-4.11, release notes: not needed, topic: library

#4220 Performance improvements motivated by hybrid quotient
  lib/grppclat.gd
  lib/grppclat.gi
  lib/kbsemi.gi
  lib/pcgsind.gi
Labels: kind: enhancement, kind: performance, release notes: not needed

#4227 fixed some typos
  hpcgap/lib/helpbase.gi
  lib/ctbl.gd
  lib/error.g
  lib/gpprmsya.gi
  lib/helpbase.gi
  lib/meataxe.gi
  lib/numtheor.gi
  lib/package.gd
  lib/record.gi
  src/cyclotom.c
  src/dt.c
  src/gap.c
  src/streams.c
  src/sysroots.c
Labels: release notes: not needed, topic: documentation

#4224 Do not name functions with automatically generated names
  src/gvars.c
  tst/testinstall/kernel/streams.tst
Labels: kind: enhancement, topic: kernel

#4230 fixed `HELP_SEARCH_ALTERNATIVES` again
  hpcgap/lib/helpbase.gi
  lib/helpbase.gi
  tst/teststandard/helptools.tst
Labels: kind: bug, kind: bug: wrong result, release notes: not needed, topic: documentation

#4215 libgap API: expose minimal interface to garbage collector
  src/libgap-api.c
  src/libgap-api.h
Labels: topic: kernel, topic: libgap

#4221 kernel: drop stackAlign argument from InitBags
  src/boehm_gc.c
  src/gap.c
  src/gasman.c
  src/gasman.h
  src/julia_gc.c
Labels: release notes: not needed, topic: kernel

#4236 Sync hpcgap/lib/ringpoly.gi
  hpcgap/lib/ringpoly.gi
  lib/ringpoly.gi
Labels: release notes: not needed, topic: HPC-GAP, topic: HPC-GAP unification
