Repository gap-system/gap, pull requests merged in 2022-03, with the labels that each got.

#4807 improve `GroupHomomorphismByFunction`
  lib/ghom.gi
  tst/testinstall/mapphomo.tst
Labels: kind: bug, kind: enhancement, kind: bug: unexpected error, topic: library, release notes: not needed

#4811 fp groups with more gens than rels are infinite
  lib/grpfp.gi
Labels: topic: library, release notes: not needed

#4810 Let `SimplifiedFpGroup` and `IsomorphismSimplifiedFpGroup` transfer attributes (such as size, being abelian etc.) to the simplified group
  lib/ghomfp.gi
  tst/testinstall/grpfp.tst
Labels: kind: enhancement, topic: library, release notes: use title

#4731 buildsys: progress towards `make install`
  Makefile.rules
Labels: topic: build system, release notes: not needed

#4800 buildsys: complete 'make install-headers'
  Makefile.rules
Labels: topic: build system, release notes: not needed

#4804 kernel: add #define to disable subprocess code
  src/iostream.c
  src/sysfiles.c
Labels: topic: kernel, release notes: not needed, topic: libgap, topic: julia

#4803 kernel: better early error messages
  src/error.c
Labels: topic: kernel, release notes: not needed

#4812 More 'make install' progress
  Makefile.rules
Labels: topic: build system, release notes: not needed

#4813 BuildPackage.sh: when run in GH Action, use grouping feature
  bin/BuildPackages.sh
Labels: release notes: not needed, topic: ci

#4818 BuildPackages.sh: fix GitHub CI grouping code
  bin/BuildPackages.sh
Labels: release notes: not needed, topic: ci

#4816 FIX: Centralizer bug made active in #4787
  lib/clashom.gi
  tst/testbugfix/2022-03-05-Centralizer.tst
Labels: kind: bug: wrong result, release notes: not needed, priority: high

#4823 BugFix: Fix crash when QuitGap is called while reading from an InputTextString
  src/io.c
  tst/testspecial/error-in-InputTextString.g
  tst/testspecial/error-in-InputTextString.g.out
  tst/testspecial/exit-in-InputTextString.g
  tst/testspecial/exit-in-InputTextString.g.out
Labels: kind: bug, kind: bug: crash, topic: kernel

#4822 FIX: Canonical class representative for pc groups
  lib/claspcgs.gi
Labels: kind: bug: wrong result, release notes: to be added, priority: high

#4794 Remove incorrect line breaks in the output of `StringFormatted`
  lib/string.gi
  tst/testinstall/format.tst
Labels: kind: bug, topic: library, release notes: use title, gapdays2022-winter

#4825 CI: error if there aren't artifacts to upload
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci

#4831 CI: use ccache to speed up compilation, esp. of packages
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#4829 Fix BuildPackages.sh
  bin/BuildPackages.sh
Labels: regression, topic: packages, release notes: not needed

#4837 CI: improve ccache integration
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#4830 Fix infinite recursion in `AlternatingDegree` and `SymmetricDegree` when the given
  lib/grpnames.gi
  tst/testbugfix/2022-03-20-AlternatingDegree.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: not needed

#4839 Fix example demonstrating how to create an object
  doc/ref/intrfc.xml
Labels: topic: documentation, release notes: not needed

#4840 Make sure to reset C pointers after possible garbage collection
  src/permutat.cc
Labels: kind: bug: crash, release notes: not needed

#4824 CI: install fewer texlive packages
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: topic: documentation, release notes: not needed, topic: ci

#4828 buildsys: switch to new package distribution
  Makefile.rules
Labels: topic: build system, topic: packages, release notes: not needed

#4842 fixed a bug in character table `Display`
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: kind: bug, topic: library, release notes: not needed

#4846 enhance `Indicator`
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, topic: library, release notes: not needed
