Repository gap-system/gap, pull requests merged in 2022-02, with the labels that each got.

#4750 CI: use `windows-2019` in Cygwin test job
  .github/workflows/CI.yml
Labels: os: windows, release notes: not needed, topic: ci

#4757 Fix regression in the tab completion code
  lib/cmdledit.g
Labels: regression, topic: library, release notes: not needed

#4765 fixed a few typos and GAPDoc markup
  lib/cmdledit.g
  lib/coll.gd
  lib/files.gd
  lib/files.gi
  lib/ghomfp.gd
  lib/list.gd
  lib/listcoef.gd
  lib/ratfun.gd
  lib/streams.gd
  lib/string.g
Labels: kind: enhancement, topic: documentation, release notes: not needed

#4753 CI: Upload code coverage for Windows build
  .github/workflows/CI.yml
Labels: os: windows, topic: ci

#4777 CI: tweak expect test to make it a bit more robust
  dev/ci.sh
  dev/gaptest.expect
Labels: release notes: not needed, topic: ci

#4776 CI: add a test kernel extension to mockpkg
  .github/workflows/CI.yml
  .gitignore
  dev/ci.sh
  tst/mockpkg/.gitignore
  tst/mockpkg/Makefile.gappkg
  tst/mockpkg/Makefile.in
  tst/mockpkg/PackageInfo.g
  tst/mockpkg/configure
  tst/mockpkg/init.g
  tst/mockpkg/src/mockpkg.c
  tst/mockpkg/tst/kext.tst
Labels: release notes: not needed, topic: ci

#4767 workaround for a `One` method
  lib/arith.gi
  tst/testinstall/ctblfuns.tst
Labels: kind: bug, kind: bug: wrong result, topic: library, release notes: not needed

#4779 Makefile.gappkg: fix distclean; make QUIET_GAC more quiet
  etc/Makefile.gappkg
Labels: topic: build system, topic: packages, release notes: not needed

#4778 gac: remove support for static linking
  Makefile.rules
  cnf/gac.in
  tst/test-compile/README.md
  tst/test-compile/and_filter.g.static.c
  tst/test-compile/assert.g.static.c
  tst/test-compile/basics.g.static.c
  tst/test-compile/callfunc.g.static.c
  tst/test-compile/function_types.g.static.c
  tst/test-compile/info.g.static.c
  tst/test-compile/plus.g.static.c
  tst/test-compile/print_various.g.static.c
  tst/test-compile/ranges.g.static.c
  tst/test-compile/run_all.sh
  tst/test-compile/run_compiled_static.sh
Labels: topic: build system, topic: gac, release notes: use title

#4789 Allow Cygwin binaries to be stored in /usr/bin or /bin
  lib/system.g
Labels: os: windows, topic: library, release notes: not needed

#4783 etc/ffgen.c: don't include common.h
  etc/ffgen.c
Labels: topic: kernel, release notes: not needed

#4790 kernel: use SELF_NAME some more
  src/collectors.cc
  src/costab.c
  src/cyclotom.c
  src/gap.c
  src/gaptime.c
  src/hpc/aobjects.c
  src/hpc/threadapi.c
  src/intfuncs.c
  src/objects.c
  src/opers.cc
  src/permutat.cc
  src/pperm.cc
  src/streams.c
  src/stringobj.c
  src/trans.cc
  src/vec8bit.c
  src/vecgf2.c
  src/weakptr.c
Labels: topic: kernel, release notes: not needed

#4792 TestPackage: packages without tests 'pass' their tests
  lib/test.gi
Labels: topic: packages, topic: library, release notes: not needed, kind: general proposed change, gapdays2022-winter

#4791 kernel: get rid of `name` field in `struct TypInputFile`
  src/io.c
  src/io.h
  src/scanner.c
Labels: topic: kernel, release notes: not needed

#4796 DOC: Note on `IsFpGroup(FreeGroup(infinity))`
  lib/grpfp.gd
Labels: release notes: not needed, kind: quirk

#4798 Fixed the error handling of `AllHomomorphisms` and `AllHomomorphismClasses`
  lib/teaching.g
  tst/testinstall/teaching.tst
Labels: topic: library, topic: error handling, release notes: use title
