Repository gap-system/gap, pull requests merged in 2022-01, with the labels that each got.

#4725 FIX: Structure of Out(G) for F4(2^e) and G2(3^e) is cyclic.
  grp/simple.gi
Labels: kind: bug: wrong result, release notes: not needed

#4722 Julia: rename MPtr to GapObj
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia

#4646 CI: update to codecov/codecov-action@v2
  .github/workflows/CI.yml
  dev/ci-gather-coverage.sh
Labels: release notes: not needed, topic: ci

#4726 kernel: add some function pointer typedefs
  src/common.h
  src/exprs.c
  src/exprs.h
  src/gapstate.h
  src/hookintrprtr.c
  src/hookintrprtr.h
  src/stats.c
  src/stats.h
Labels: topic: kernel, release notes: not needed

#4728 Fix wrong Projection for Perm Wreath Product constructed with hom
  lib/gprdperm.gi
  tst/testbugfix/2022-01-05-WreathProduct-With-Hom-Projection.tst
Labels: release notes: not needed

#4732 gac: remove -r and last traces of -fFEATURE
  cnf/gac.in
Labels: release notes: not needed, topic: gac

#4736 Adds primitivity check for SocleTypePrimitiveGroup
  lib/grpperm.gi
Labels: topic: library, kind: quirk

#4739 Adjust documentation of SocleTypePrimitiveGroup
  lib/grpperm.gd
Labels: topic: documentation

#4740 kernel: correct outdated comments
  src/code.c
  src/code.h
  src/intrprtr.c
  src/vars.c
Labels: topic: kernel, release notes: not needed

#4741 minor improvement for `?Undocumented;`
  lib/helpbase.gi
Labels: kind: enhancement, release notes: not needed, topic: help system

#4231 LoadKernelExtension, IsKernelExtensionAvailable
  doc/ref/gappkg.xml
  lib/files.gd
  src/modules.c
  tst/testinstall/kernel/gap.tst
  tst/testinstall/kernel/modules.tst
Labels: topic: packages, topic: kernel, kind: discussion, release notes: to be added

#4742 Fix IsKernelExtensionAvailable usage example
  doc/ref/gappkg.xml
Labels: topic: documentation, release notes: not needed
