Repository gap-system/gap, pull requests merged in 2022-10, with the labels that each got.

#5077 kernel: if no GC is selected, default to GASMAN
  src/common.h
Labels: topic: kernel, release notes: not needed, backport-to-4.12

#5076 kernel: remove USE_GMP
  src/common.h
Labels: topic: kernel, release notes: not needed

#5078 kernel: move voidfunc typedef to only place using it
  src/common.h
  src/tracing.c
Labels: topic: kernel, release notes: not needed

#5079 Improve buildsystem by exporting `GMP_PREFIX` in `sysinfo.gap` for package build systems
  GNUmakefile.in
  Makefile.rules
  configure.ac
Labels: topic: build system, release notes: use title, backport-to-4.12

#5085 buildsys: fix broken `__builtin_mul_overflow` check
  configure.ac
Labels: topic: build system, topic: performance, release notes: not needed, backport-to-4.12

#5082 Fix broken shebang
  tst/testspecial/run_gap.sh
Labels: release notes: not needed, backport-to-4.12

#5083 Makefile.rules: use LTINSTALL to install gap executable
  Makefile.rules
Labels: topic: build system, release notes: not needed, backport-to-4.12

#5087 improved the description of `DirectoryContents`
  lib/files.gd
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5093 Fix typo: polycylic -> polycyclic
  lib/grppcatr.gi
  lib/grppcint.gi
  lib/grppcnrm.gd
  lib/grppcnrm.gi
  lib/grppcprp.gi
  lib/pcgs.gd
  lib/pcgs.gi
  lib/pcgscomp.gi
  lib/pcgsind.gd
  lib/pcgsind.gi
  lib/pcgsmodu.gd
  lib/pcgsmodu.gi
  lib/pcgspcg.gd
  lib/pcgspcg.gi
  lib/quotsys.gd
  lib/rwspcclt.gi
Labels: topic: library, release notes: not needed

#5089 kernel: don't include `stdio.h` in `compiled.h`
  src/compiled.h
Labels: topic: packages, topic: kernel, release notes: not needed

#5091 Don't attempt to install the 'dev' manual...
  Makefile.rules
Labels: topic: build system, release notes: not needed, backport-to-4.12

#5090 Fix permissions for convert.pl when installing
  Makefile.rules
Labels: topic: build system, release notes: not needed, backport-to-4.12

#5026 CI: switch from ubuntu-18.04 to ubuntu-latest
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#5100 kernel: rename gap95w.c to main.c and always use it
  Makefile.rules
  src/gap.c
  src/main.c
Labels: topic: kernel, release notes: not needed

#5106 buildsys: remove unused stuff from GNUmakefile.in
  GNUmakefile.in
Labels: topic: build system, release notes: not needed

#5115 Fix regression caused by GNUMakefile.in plus libgap.pc changes
  Makefile.rules
  doc/versiondata.in
Labels: regression, release notes: not needed

#5114 Make documentation of nested sublist extractions more visible
  doc/ref/lists.xml
Labels: topic: documentation, release notes: not needed

#5118 fixed image of trivial space under matrix action
  lib/vspcrow.gi
  tst/testinstall/vspcrow.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: not needed

#5104 buildsys: remove a bunch of obsolete test targets
  Makefile.rules
  doc/dev/testing.xml
  tst/testutil.g
Labels: topic: build system, release notes: not needed

#5120 kernel: refactor Tietze code
  src/tietze.c
Labels: topic: kernel, release notes: not needed

#5124 kernel: avoid superfluous newlines in Error messages
  src/permutat.cc
  src/saveload.c
  src/vec8bit.c
Labels: topic: kernel, release notes: not needed

#5116 Fix printing of GAP functions containing sublist extractions
  src/vars.c
  tst/testinstall/function.tst
Labels: kind: bug, topic: kernel, release notes: use title, backport-to-4.12

#5127 Make sure owner and group in tarballs are set uniformly to 0
  dev/releases/make_archives.py
Labels: release notes: not needed, topic: infrastructure, backport-to-4.12

#5126 Fix crashes in `ConvertToVectorRep` and `CopyToVectorRep`
  src/vec8bit.c
  tst/testbugfix/2022-10-18-RewriteVec8Bit.tst
Labels: kind: bug, kind: bug: crash, release notes: use title, backport-to-4.12, gapdays2022-summer

#5132 Unifying the references for matrix and vector
  lib/matobj2.gd
Labels: topic: documentation, release notes: not needed, gapdays2022-summer

#5147 CI: replace obsolete set-output
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci, backport-to-4.12, gapdays2022-summer

#5151 Release notes for GAP 4.12.1
  CHANGES.md
Labels: topic: documentation, release notes: not needed, backport-to-4.12, gapdays2022-summer

#5139 Enhance `Display` for functions to print where the function was defined, if possible
  lib/function.gi
  tst/testinstall/grpreps.tst
  tst/testinstall/opers/BindingsOfClosure.tst
  tst/testinstall/varargs.tst
  tst/testspecial/print-compiled-func.g.out
Labels: kind: enhancement, topic: library, release notes: use title, gapdays2022-summer

#5149 Enable `Eigenvalues` for MatrixObj
  lib/matrix.gd
  lib/matrix.gi
  tst/testinstall/MatrixObj/Eigenvalues.tst
Labels: kind: enhancement, release notes: not needed, gapdays2022-summer

#5154 CI: consistently use Python 3.9
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci, backport-to-4.12, gapdays2022-summer

#5156 Switch (Set)MatElm with `[,]` resp. `[,]:=`
  lib/matobj2.gd
  tst/testinstall/listindex.tst
  tst/testspecial/bad-array-double-1.g.out
Labels: topic: library, release notes: not needed, gapdays2022-summer

#5150 call `FreeGeneratorsOfWholeGroup` not `FreeGeneratorsOfFpGroup`
  lib/ghom.gi
  tst/testinstall/grpfree.tst
Labels: kind: bug: unexpected error, topic: library, release notes: not needed, gapdays2022-summer

#5148 Small fix for issue 5134
  lib/matrix.gi
  tst/testbugfix/2022-21-10-InfinityLoopFloatMatrices.tst
Labels: gapdays2022-summer

#5167 Fix indentation when printing EXPR_ELM_MAT or EXPR_ELM_LIST_LEVEL
  src/vars.c
  tst/testinstall/listindex.tst
Labels: kind: bug, topic: kernel, release notes: not needed

#5146 Signal an error when internal file descriptor limit is reached (at most 256 files can be open at the same time)
  lib/streams.gd
  src/sysfiles.c
  tst/testinstall/streams.tst
Labels: topic: documentation, topic: kernel, release notes: use title

#5158 Change `DecomposeTensorProduct` to ensure it produces a *sorted* list of highest weights, and document this
  lib/lierep.gd
  lib/lierep.gi
  tst/testinstall/algsc.tst
Labels: kind: enhancement, topic: library, release notes: use title, gapdays2022-summer

#5170 kernel: fix compiler warning on some systems
  src/gaptime.c
Labels: topic: kernel, release notes: not needed, backport-to-4.12

#5169 buildsys: better solution for src/compiled.h
  Makefile.rules
Labels: release notes: not needed, backport-to-4.12

#5171 buildsys: fix out-of-tree cross compiling
  Makefile.rules
Labels: topic: build system, backport-to-4.12
