Repository gap-system/gap, pull requests merged in 2022-08, with the labels that each got.

#4963 kernel: fix compilation of HPC-GAP on macOS
  src/hpc/cpu.c
Labels: topic: HPC-GAP, regression, topic: kernel, release notes: not needed

#4965 CI: build manual & deploy to gh-pages
  .github/workflows/update-gh-pages.yml
  dev/index.html
Labels: topic: documentation, release notes: not needed, topic: ci

#4967 kernel: add NEW_LOWINDEX_DATA helper
  lib/grpfp.gi
  src/costab.c
Labels: topic: kernel, release notes: not needed

#4625 Ranges: improve printing and conversion to strings
  lib/list.gi
  tst/testinstall/range.tst
Labels: topic: library, release notes: not needed

#4339 Document `TensorProduct`, `ExteriorPower` and `SymmetricPower` (they existed since at least GAP 4.4)
  doc/ref/vspc.xml
  lib/algrep.gd
Labels: topic: documentation, release notes: use title

#4971 Suppress test output for compatibility with Semigroups
  tst/teststandard/reesmat.tst
Labels: release notes: not needed

#4966 Fix definition of a few representations
  lib/ctbl.gd
  lib/grpfp.gd
  lib/wordass.gd
Labels: topic: library, release notes: not needed

#4968 Merge the two RightCoset methods
  lib/csetgrp.gi
Labels: topic: library, release notes: not needed

#4973 Import MappedVector changes from polycyclic
  lib/grppcrep.gi
Labels: topic: library, release notes: not needed

#4969 kernel: some minor cleanup
  src/iostream.c
  src/sysfiles.h
  src/sysroots.c
Labels: topic: kernel, release notes: not needed

#4471 Document RootFFE
  doc/ref/fieldfin.xml
  lib/ffe.gd
Labels: topic: documentation, release notes: not needed

#4978 Fix GASMAN register marking
  src/gasman.c
Labels: regression, topic: kernel

#4980 Re-enable all cygwin features, remove non-functional tests
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: infrastructure, topic: ci

#4985 Handle --bare in AutoloadPackages instead of modifying GAPInfo.
  lib/package.gi
  lib/system.g
Labels: topic: packages, release notes: not needed

#4981 Fix GasmanLimits / GASMAN_LIMITS regression
  src/gap.c
  tst/testinstall/kernel/gap.tst
Labels: regression, topic: kernel, release notes: not needed

#4461 Add custom SetIsSSortListProp for internal lists
  src/lists.c
  src/modules.c
  src/modules.h
  src/opers.cc
  src/opers.h
  tst/testinstall/list.tst
Labels: topic: kernel, release notes: not needed

#4986 Don't clobbber 'i' in method-not-found break loops
  lib/methsel2.g
Labels: topic: library, release notes: not needed

#4991 Document the `-c` command line option
  doc/ref/run.xml
Labels: topic: documentation, release notes: not needed

#4997 CI: NormalizInterface doesn't need libboost anymore
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#4998 INSTALL.md: list some GAP package prerequisites
  .github/workflows/CI.yml
  INSTALL.md
Labels: topic: documentation, release notes: not needed

#5000 Adjust tests for GAPDoc 1.6.6
  tst/testinstall/package.tst
Labels: topic: tests, release notes: not needed

#5008 Tweak `create_stable_branch.py`
  dev/releases/create_stable_branch.py
Labels: release notes: not needed, topic: infrastructure
