Repository gap-system/gap, pull requests merged in 2022-04, with the labels that each got.

#4843 Fix MagmaWithInversesByGenerators with family and empty gens
  lib/magma.gi
  tst/testbugfix/2022-03-29-MagmaWithInversesByGenerators.tst
Labels: kind: bug, release notes: not needed

#4848 Correct doc for (Exact)SizeConsiderFunction
  lib/grppclat.gd
Labels: topic: documentation, release notes: not needed

#4849 CI: workaround ccache crash by avoiding -march=native
  dev/ci.sh
Labels: release notes: not needed, topic: ci

#4847 kernel: revert how READ_COMMAND_REAL treats "quit;"
  src/streams.c
  tst/testinstall/kernel/streams.tst
Labels: regression, topic: kernel, release notes: not needed

#4850 CI: enable debug messages for package loading
  dev/ci.sh
Labels: release notes: not needed, topic: ci

#4853 Remove a test for data in the small groups library
  tst/testinstall/small_groups.tst
Labels: topic: tests, release notes: not needed

#4852 doc: minor corrections for the perfect groups library
  doc/ref/grplib.xml
  grp/perf.gd
Labels: topic: documentation, release notes: not needed

#4862 Fix CI on Windows
  .github/workflows/CI.yml
Labels: os: windows, topic: ci

#4856 Improve `Intersection` for permutation groups
  doc/ref/debug.xml
  lib/stbcbckt.gi
  tst/testextra/grpperm.tst
Labels: kind: enhancement, topic: library, release notes: not needed

#4869 Set MAXSIZE_GF_INTERNAL from the kernel
  lib/ffe.g
  src/finfield.c
Labels: topic: kernel, release notes: not needed

#4867 Remove etc/emacs/README
  etc/emacs/README
Labels: release notes: not needed

#4857 MatrixObj: matrix manipulation ops for `IsMatrix`
  lib/matobj.gi
  lib/matobj2.gd
  tst/testinstall/MatrixObj/ElementaryMatrices.tst
  tst/testinstall/MatrixObj/testmatobj.g
Labels: kind: enhancement, topic: library, release notes: not needed

#4870 kernel: use ffdata.h constants in finite field code
  etc/ffgen.c
  hpcgap/lib/ffeconway.gi
  lib/ffeconway.gi
  src/finfield.c
  src/finfield.h
  tst/testinstall/ffe.tst
Labels: topic: kernel, release notes: not needed

#4872 buildsys: strip gap and libgap when installing them
  Makefile.rules
Labels: topic: build system, release notes: not needed

#4873 Drop support for Julia < 1.6
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia

#4871 buildsys: install some more files
  Makefile.rules
Labels: topic: build system, release notes: not needed

#4863 kernel: don't waitpid(-1)
  src/iostream.c
Labels: topic: kernel, release notes: not needed, topic: libgap

#4882 kernel: tweak Julia integration
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia

#4889 Update README.md
  etc/README.md
Labels: release notes: not needed
