Repository gap-system/gap, pull requests merged in 2022-12, with the labels that each got.

#5236 Remove obsolete code from `BuildPackages.sh`, add comments
  bin/BuildPackages.sh
Labels: topic: packages, release notes: not needed

#5244 CI: update act10ns/slack to v2 instead of v1.2.2
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci, backport-to-4.12

#5252 Avoid double-slash in `TestDirectory` output
  lib/package.gi
Labels: release notes: not needed, kind: quirk

#5246 Make sure that syntax error messages during `EvalString` are displayed correctly
  lib/string.gi
  tst/testbugfix/2022-12-06-EvalString-syntax-error.tst
Labels: kind: bug, topic: library, release notes: use title

#5253 minor fixes in the documentation
  doc/ref/alglie.xml
  doc/ref/methsel.xml
  grp/classic.gd
  lib/files.gd
  lib/ghomfp.gd
  lib/grp.gd
Labels: kind: bug, topic: documentation, release notes: not needed

#5248 better documentation for user preferences
  doc/ref/run.xml
  doc/ref/user_pref_list.xml
  hpcgap/lib/integer.gi
  hpcgap/lib/userpref.g
  lib/cmdledit.g
  lib/colorprompt.g
  lib/files.gi
  lib/helpview.gi
  lib/init.g
  lib/integer.gi
  lib/package.gi
  lib/pager.gi
  lib/userpref.g
  tst/testinstall/userpref.tst
Labels: kind: enhancement, topic: documentation, release notes: to be added

#5250 Fix an unexpected error during tab completion for input like `a.b.` when `a` is not a record
  dev/gaptest.expect
  lib/cmdledit.g
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: use title

#5258 Fix spelling: homogenous -> homogeneous
  dev/listarith.tex
  lib/arith.gd
  lib/list.g
  lib/pcgsspec.gi
  lib/sparselist.gd
  lib/sparselistsorted.gi
  src/blister.c
  src/lists.h
  src/plist.c
  src/set.c
Labels: release notes: not needed

#5243 Add some implications for permutation groups
  lib/oprt.gd
Labels: topic: performance, topic: library, release notes: not needed

#5245 Fix `AsSet` and other methods for `GL(1,Integers)` and also SL
  lib/grpramat.gi
  tst/testinstall/grp/classic-G.tst
  tst/testinstall/grp/classic-S.tst
Labels: topic: library, release notes: use title

#5267 improve a `SemidirectProduct` method
  lib/gprd.gi
Labels: kind: enhancement, topic: library, release notes: not needed

#5263 Mark as obsolete: `ZeroSM`/`ZeroAttr`, `AdditiveInverseSM`/`AdditiveInverseAttr` `OneSM`/`OneAttr`, `InverseSM`/`InverseAttr`, `TransposedMatAttr`
  doc/ref/lists.xml
  doc/ref/objects.xml
  doc/ref/obsolete.xml
  hpcgap/lib/ffeconway.gi
  hpcgap/lib/vecmat.gi
  lib/arith.gd
  lib/arith.gi
  lib/ffeconway.gi
  lib/list.gi
  lib/matrix.gd
  lib/obsolete.gd
  lib/vecmat.gi
  lib/zmodnz.gi
  src/integer.c
  tst/testbugfix/2012-12-06-t00266.tst
  tst/testinstall/zmodnz.tst
  tst/testspecial/bad-minus.g.out
  tst/teststandard/arithlst.g
Labels: topic: library, release notes: use title

#5270 Fix whitespace in a few documentation examples
  doc/ref/create.xml
  doc/ref/mloop.xml
  doc/ref/options.xml
  doc/ref/xtndxmpl.xml
  doc/tut/introduc.xml
Labels: release notes: not needed

#5269 Remove tabs in files starting with "a"
  lib/addgphom.gi
  lib/adjoin.gi
  lib/algebra.gi
  lib/algfld.gi
  lib/alghom.gi
  lib/alglie.gi
  lib/algliess.gi
  lib/algmat.gi
  lib/algsc.gi
  lib/arith.gd
  lib/autsr.gi
Labels: release notes: not needed

#5279 Avoid references to `gap.sh`
  Makefile.rules
  dev/bisect.sh
  dev/ci-gather-coverage.sh
  dev/ci.sh
  dev/releases/make_archives.py
  doc/make_doc.in
  doc/ref/runexamples.g
  doc/tut/runexamples.g
  hpcgap/demo/intersection.g
  src/gap.c
Labels: release notes: not needed

#5278 dev: change make_archives.py to use more PackageDistro data
  dev/releases/PackageInfos-to-JSON.g
  dev/releases/make_archives.py
  dev/releases/utils.py
Labels: release notes: not needed, topic: infrastructure, backport-to-4.12

#5276 ci: add gaplint job (trailing whitespace only)
  .gaplint.yml
  .github/workflows/lint.yml
Labels: release notes: not needed, topic: ci

#5280 Add debug assertions to Blists
  src/blister.c
  src/blister.h
Labels: topic: kernel, release notes: not needed

#5282 CI: don't invoke ci-download-pkgs.sh in release job
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci

#5254 matrixobj: deal with mutability questions
  doc/ref/makedocreldata.g
  doc/ref/matobj.xml
  lib/list.gd
  lib/mat8bit.gd
  lib/matobj.gi
  lib/matobj1.gd
  lib/matobj2.gd
  lib/matobjnz.gd
  lib/matobjplist.gd
  lib/type.g
  lib/vec8bit.gd
  lib/vecmat.gd
Labels: kind: enhancement, topic: library, release notes: not needed

#5287 Improve dev/releases/README.md
  dev/releases/README.md
Labels: release notes: not needed, topic: infrastructure, backport-to-4.12

#5293 BuildPackages.sh: tweak how GAP is invoked
  bin/BuildPackages.sh
Labels: topic: infrastructure
