Repository gap-system/gap, pull requests merged in 2022-09, with the labels that each got.

#4999 Update .mailmap file
  .mailmap
Labels: release notes: not needed

#5013 added a new criterion to compute indicators of 2-modular Brauer characters
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, topic: library, release notes: use title

#5028 Fix a typo
  dev/releases/README.md
Labels: release notes: not needed

#5027 Do not define unused functions with SYS_DEFAULT_PATHS
  src/system.c
Labels: topic: kernel, release notes: not needed

#5022 Fix claims about emacs support in the reference manual
  doc/ref/mloop.xml
Labels: topic: documentation, release notes: not needed, backport-to-4.12

#5034 INSTALL.md: remove "Expert Windows Installation"
  INSTALL.md
Labels: topic: documentation, os: windows, release notes: not needed, backport-to-4.12

#5033 Fix unexpected error in `ConjugacyClassesSubgroups`
  lib/grplatt.gi
  tst/testbugfix/2022-09-06-ConjugacyClassesSubgroups.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: use title, backport-to-4.12

#5032 Fix performance regression in `AllHomomorphismClasses` and possibly other code searching isomorphisms
  lib/morpheus.gi
  lib/teaching.g
Labels: regression, topic: performance, release notes: use title, backport-to-4.12

#5036 Fix `Centre` for pc groups giving wrong results, e.g. `Size(Center(SmallGroup(2^9,261648)))` gave 4 instead of 8
  lib/grppcatr.gi
  tst/testbugfix/2022-09-07-Centre.tst
Labels: kind: bug, kind: bug: wrong result, release notes: use title, backport-to-4.12

#5038 Support `TensorProduct`, `ExteriorPower` and `SymmetricPower` for characters
  doc/ref/ctblfuns.xml
  lib/ctblfuns.gd
  lib/ctblfuns.gi
Labels: kind: enhancement, topic: library, release notes: use title

#5041 Fix unexpected error in `MinimalGeneratingSet` for solvable non-pc groups
  lib/grp.gi
  tst/testbugfix/2022-09-09-MinimalGeneratingSet.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: use title, backport-to-4.12

#5043 Fix `SaveOnExitFile` in restored workspaces
  lib/session.g
Labels: kind: bug, release notes: use title, backport-to-4.12

#5044 doc: add heading to `Centralizer` entry
  lib/magma.gd
Labels: topic: documentation, release notes: not needed, backport-to-4.12

#5048 Makefile: signal error via exit code
  Makefile
Labels: topic: build system, release notes: not needed, backport-to-4.12

#5053 Makefile.gappkg: ensure `make doc` terminates
  etc/Makefile.gappkg
Labels: topic: packages, release notes: not needed, backport-to-4.12

#5054 README.md: add links to the latest manual snapshots
  README.md
Labels: topic: documentation, release notes: not needed

#5047 `Display` for a character table optionally shows the degrees of the character fields
  lib/ctbl.gd
  lib/ctbl.gi
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, topic: library, release notes: use title, backport-to-4.12

#5057 Fix `Orbits` when called with a range as seeds
  lib/oprt.gi
  tst/testbugfix/2022-09-15-Orbits.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: use title, backport-to-4.12

#5059 Fix `AllHomomorphisms` regression
  lib/morpheus.gi
  lib/teaching.g
  tst/testbugfix/2022-09-17-AllHomomorphisms.tst
Labels: kind: bug, kind: bug: unexpected error, regression, release notes: not needed, backport-to-4.12

#5051 update Test documentation: local identifier list
  lib/test.gi
Labels: topic: documentation, release notes: not needed

#5065 Fix HASH_FLAGS on big endian
  src/opers.cc
Labels: topic: kernel, release notes: not needed, backport-to-4.12

#5069 CI: remove outdated TODO comments
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci, backport-to-4.12

#5067 fixed `AbsolutelyIrreducibleModules` for a pc group and a finite prime field
  lib/grppcrep.gi
  lib/grpreps.gd
  tst/testinstall/grpreps.tst
Labels: kind: bug, kind: bug: wrong result, release notes: use title, backport-to-4.12

#5066 fix multiplication of `IsFFE` and `Is8BitMatrixRep`
  lib/mat8bit.gi
  tst/testinstall/mat8bit.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: not needed, backport-to-4.12

#5071 Fix clang 15 warning
  src/permutat.cc
Labels: topic: kernel, release notes: not needed, backport-to-4.12

#5070 Makefile.gappkg: move pkgconfig.h.in from gen to src
  etc/Makefile.gappkg
Labels: topic: packages, release notes: not needed, backport-to-4.12

#5064 Don't mention Tuple in the manual
  lib/grppcext.gi
  lib/relation.gd
Labels: topic: documentation, release notes: not needed, backport-to-4.12
