Repository gap-system/gap, pull requests merged in 2023-02, with the labels that each got.

#5357 Remove undocumented & unused AgemoAbove
  lib/grp.gd
  lib/grp.gi
Labels: topic: library, release notes: not needed

#5359 Add new property `IsRegularPGroup`
  doc/manualbib.xml
  doc/ref/groups.xml
  lib/grp.gd
  lib/grp.gi
  tst/testinstall/pgroups.tst
Labels: kind: enhancement, kind: new feature, topic: library, release notes: use title

#5358 Document that attribute methods better make their results immutable
  doc/ref/types.xml
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5368 Fix hang in objset/objmap when filled up with dirty objects
  src/objset.c
Labels: topic: kernel, release notes: not needed

#5367 kernel: some objmap/objset cleanup
  src/objset.c
  src/objset.h
Labels: topic: kernel, release notes: not needed

#5369 kernel: more ObjMap/ObjSet refactoring
  src/objset.c
Labels: topic: kernel, release notes: not needed

#5352 Remove obsolete (?) MutableCopyMat method
  lib/matrix.gi
Labels: release notes: not needed

#5356 Add tests for matrices in `Is8BitMatrixRep` and fix some inconsistent behaviour
  lib/mat8bit.gi
  tst/testinstall/mat8bit.tst
Labels: topic: library, release notes: not needed

#5376 document the supported components of `PackageInfo.g`
  doc/ref/gappkg.xml
Labels: kind: enhancement, topic: documentation, topic: packages, release notes: not needed

#5380 Remove `SmallGroupsInformation(512)` test
  tst/testbugfix/2005-05-03-t00061.tst
Labels: topic: tests, topic: packages, release notes: not needed

#5377 kernel: move SyExecuteProcess to iostream.c
  src/iostream.c
  src/streams.c
  src/sysfiles.c
  src/sysfiles.h
Labels: topic: kernel, release notes: not needed

#5378 extend `ProfileFunctionsInGlobalVariables` ...
  lib/profile.g
Labels: kind: enhancement, topic: library, release notes: not needed

#5370 Remove SMTX_* aliases for SMTX.* functions
  lib/meataxe.gi
Labels: topic: library, release notes: not needed
