Repository gap-system/gap, pull requests merged in 2023-09, with the labels that each got.

#5500 Fix HPC-GAP crash when calling `IntFFE` repeatedly
  src/finfield.c
Labels: kind: bug, topic: HPC-GAP, kind: bug: crash, topic: kernel, release notes: use title

#5503 Rank down MatrixObj emulation methods
  lib/matrix.gi
Labels: topic: library, release notes: not needed

#5510 ENHANCE: FittingFreeLiftSetup
  lib/fitfree.gi
  lib/ghomperm.gi
  lib/grp.gd
  lib/maxsub.gi
  lib/permdeco.gi
Labels: kind: enhancement, release notes: not needed

#5512 Use NormalizerViaRadical for suitable permutation groups
  doc/tut/group.xml
  lib/stbcbckt.gi
Labels: kind: enhancement, release notes: to be added, kind: performance improvement

#5513 `SubgroupProperty` works only for perm. groups
  lib/stbcbckt.gd
Labels: kind: enhancement, topic: documentation, release notes: not needed
