Repository gap-system/gap, pull requests merged in 2023-08, with the labels that each got.

#5488 changed the documentation of `FamilyPcgs`
  lib/grppc.gd
Labels: kind: bug, topic: documentation, release notes: not needed

#5487 fixed `ConsiderStructureConstants`
  lib/ctblmaps.gd
  lib/ctblmaps.gi
  tst/testinstall/ctblmaps.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: not needed

#5491 Add `AlgebraWithOneByStructureConstants`
  doc/ref/algebra.xml
  lib/algebra.gd
  lib/algsc.gi
  tst/testinstall/algsc.tst
Labels: kind: enhancement, topic: library, release notes: use title

#5494 Fix `Agemo(G,p)` for trivial group `G`
  lib/grp.gi
  tst/testbugfix/2023-08-25-Agemo.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: use title

#5490 Add example for package extensions
  doc/ref/gappkg.xml
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5485 MaximalSubgroupClassReps uses AtlasRep if available
  lib/grplatt.gi
  tst/teststandard/permgrp.tst
Labels: release notes: not needed, kind: performance improvement
