Repository gap-system/gap, pull requests merged in 2023-11, with the labels that each got.

#5526 kernel: add missing `#include`
  src/iostream.c
Labels: topic: kernel, release notes: not needed

#5529 Improve definitions of vector spaces and algebras in the GAP Tutorial as discussed in #4112
  doc/tut/algvspc.xml
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5531 Fix IsCheapConwayPolynomial( p, 1 ) for p < 1000
  lib/polyconw.gi
  tst/testinstall/ffeconway.tst
Labels: kind: bug, kind: bug: wrong result, release notes: not needed

#5519 Avoid calling STAT_HEADER on inapproriate types
  src/code.c
Labels: topic: kernel, release notes: not needed

#5521 Fix unexpected error when doing certain calculations in a fitting-free group acting intransitively on its socle factors
  lib/clashom.gi
  tst/testbugfix/2023-11-09-ConjugacyClasses.tst
Labels: kind: bug, kind: enhancement, kind: bug: unexpected error, release notes: to be added

#5530 document more standard math functions as discussed in #1778
  lib/float.gd
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5522 Remove compatibility mode from the GAP build system for old GAP packages (all currently distributed packages do not need it anymore)
  GNUmakefile.in
  Makefile.rules
  README.buildsys.md
  cnf/compat/gap.sh.in
  cnf/compat/gmp.h.in
  configure.ac
Labels: topic: build system, release notes: use title
