Repository gap-system/gap, pull requests merged in 2023-05, with the labels that each got.

#5446 added a redispatch for `IsomorphismFpGroup`
  lib/grpramat.gi
  tst/testinstall/grpmat.tst
Labels: kind: bug: unexpected error, topic: library, release notes: not needed

#5445 added some missing functionality for domains of cyclotomics
  lib/cyclotom.gi
  lib/fldabnum.gi
  tst/testinstall/fldabnum.tst
Labels: kind: bug: unexpected error, topic: library, release notes: not needed

#5435 Stop installing headers into `${includedir}/gap/src`
  Makefile.rules
  README.buildsys.md
  configure.ac
  dev/ci.sh
Labels: topic: build system, release notes: use title

#5452 Fix CI for 32bit mode ABI
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: infrastructure

#5450 Ensure all lists of lists are marked as rectangular tables when approriate
  src/plist.c
  tst/testinstall/table.tst
Labels: kind: bug, topic: kernel, release notes: use title

#5453 Fix printing of expressions including non-zero list levels
  src/vars.c
  tst/testinstall/function.tst
Labels: kind: bug, topic: kernel, release notes: use title
