Repository gap-system/gap, pull requests merged in 2024-01, with the labels that each got.

#5558 Slightly better error messages during GAP startup
  lib/init.g
Labels: kind: enhancement, topic: library, release notes: not needed, topic: error handling

#5553 fix a regression in `Test`
  lib/test.gi
Labels: topic: tests, release notes: not needed

#5557 Avoid passing immutable objects to Objectify
  lib/rvecempt.gi
  lib/rwsgrp.gi
  lib/streams.gi
Labels: topic: library, release notes: not needed

#5546 Fixed printing of GAP strings containing null characters (skip them instead of truncating the string)
  src/io.c
  tst/testinstall/strings.tst
Labels: kind: bug, topic: kernel, release notes: use title

#5560 Avoid trivial function wrappers
  benchmark/transgrp/examine4
  lib/alglie.gi
  lib/algrep.gi
  lib/ctblgrp.gi
  lib/dicthf.gi
  lib/fitfree.gi
  lib/ghomfp.gi
  lib/gpfpiso.gi
  lib/gpprmsya.gi
  lib/gprd.gi
  lib/groebner.gi
  lib/grpfp.gi
  lib/grplatt.gi
  lib/grppcaut.gi
  lib/grppclat.gi
  lib/grppcrep.gi
  lib/grpperm.gi
  lib/maxsub.gi
  lib/mgmadj.gi
  lib/mgmcong.gi
  lib/morpheus.gi
  lib/pcgsperm.gi
  lib/polyrat.gi
  lib/relation.gi
  lib/semirel.gi
  lib/semitran.gi
  lib/wordrep.gi
  tst/testinstall/opers/MaximalNormalSubgroups.tst
  tst/testinstall/semirel.tst
Labels: topic: library, release notes: not needed

#5559 Replace uses of `x->IsBound(x)`
  benchmark/transgrp/examine4
  lib/alglie.gi
  lib/algrep.gi
  lib/clashom.gi
  lib/galois.gi
  lib/grplatt.gi
  lib/lierep.gi
  lib/matrix.gi
  lib/sgpres.gi
Labels: topic: library, release notes: not needed

#5562 gac: allow compiling functions with "strange" arg names
  src/compiler.c
  src/intfuncs.c
  tst/test-compile/basics.g.dynamic.c
  tst/test-compile/callfunc.g.dynamic.c
  tst/test-compile/function_types.g
  tst/test-compile/function_types.g.dynamic.c
  tst/test-compile/function_types.g.out
  tst/test-compile/ranges.g.dynamic.c
Labels: release notes: not needed, topic: gac

#5555 Use Remove instead of Unbind+Length
  dev/gapmacro2gapdoc.g
  doc/ref/language.xml
  hpcgap/lib/cmdleditx.g
  lib/cmdleditx.g
  lib/csetgrp.gi
  lib/ctbl.gi
  lib/files.gi
  lib/ghomperm.gi
  lib/gpfpiso.gi
  lib/groebner.gi
  lib/grpfp.gi
  lib/grplatt.gi
  lib/grppcatr.gi
  lib/kbsemi.gi
  lib/listcoef.gi
  lib/meatauto.gi
  lib/mgmcong.gi
  lib/numtheor.gi
  lib/oprt.gi
  lib/options.gi
  lib/package.gi
  lib/relation.gi
  lib/sgpres.gi
  lib/sparselistsorted.gi
  lib/stbc.gi
  lib/stbcrand.gi
  lib/straight.gi
  lib/teaching.g
  src/listfunc.c
Labels: topic: library, release notes: not needed

#5565 Don't fail testsuite if FinInG is unavailable
  tst/testbugfix/2023-10-18-SetDimension.tst
Labels: topic: tests, release notes: not needed

#5569 Move slow tests to teststandard
  tst/testinstall/function.tst
  tst/teststandard/function.tst
Labels: topic: tests, release notes: not needed

#5571 Cleanup in `tst`
  lib/profile.g
  tst/delegation.g
  tst/test32bit/perm.tst
  tst/test64bit/perm.tst
  tst/testbugfix/2005-05-05-t00072.tst
  tst/testinstall/coll.tst
  tst/testinstall/perm.tst
  tst/testinstall/random.tst
  tst/testinstall/restrictedperm.tst
  tst/testinstall/testenumerator.g
  tst/testinstall/testrandom.g
Labels: topic: tests, release notes: not needed

#5570 Fix dev/audit-config-h.sh and how we use it
  dev/audit-config-h.sh
  dev/ci.sh
  src/hpc/cpu.c
Labels: release notes: not needed, topic: ci

#5566 Add argument validation to `ListPerm`, and turn it into a kernel function to make it faster
  lib/permutat.g
  src/listfunc.c
  src/permutat.cc
  tst/testinstall/perm.tst
Labels: kind: enhancement, topic: kernel, topic: library

#5567 Improve the `dev/ci.sh` script, make it usable interactive, and some related CI tweaks
  .github/workflows/CI.yml
  .github/workflows/release.yml
  .gitignore
  GNUmakefile.in
  Makefile.rules
  dev/ci.sh
Labels: topic: tests, release notes: not needed, topic: ci

#5399 Add some contributor/developer guidelines
  CONTRIBUTING.md
  DEVELOPING.md
Labels: topic: documentation, release notes: not needed, topic: workflow

#5568 tst: fix file descriptor leaks
  tst/testbugfix/2006-10-23-t00163.tst
  tst/testinstall/compressed.tst
  tst/testinstall/read.tst
  tst/testinstall/streams.tst
Labels: topic: tests, release notes: not needed

#5572 Make `License` field for GAP packages mandatory
  doc/ref/gappkg.xml
  lib/package.gi
  tst/testinstall/package.tst
Labels: topic: packages, release notes: use title

#5554 Make `Objectify` and `ObjectifyWithAttributes` reject input objects which are not plain lists or records
  doc/ref/create.xml
  lib/type1.g
  src/objects.c
Labels: topic: kernel, release notes: use title

#5578 Use dependabot to keep GH Actions up-to-date
  .github/dependabot.yml
Labels: release notes: not needed, topic: infrastructure, topic: ci

#5584 Fix RemoveDirectoryRecursively for immutable argument
  lib/files.gi
  tst/testinstall/kernel/streams.tst
Labels: regression, release notes: not needed

#5593 CI: allow tags named v1.2.3-beta
  .github/workflows/release.yml
  dev/releases/make_github_release.py
  dev/releases/utils.py
Labels: release notes: not needed, topic: infrastructure, topic: ci

#5594 Don't require tput for gac or dev/ci.sh
  cnf/gac.in
  dev/ci.sh
Labels: release notes: not needed

#5595 Improve and update windows text in INSTALL.md
  INSTALL.md
Labels: topic: documentation, release notes: not needed

#5597 README.md: add or fix some links, typo
  README.md
Labels: topic: documentation

#5306 Stop using GNU libtool for linking GAP and libgap
  .gitignore
  GNUmakefile.in
  INSTALL.md
  Makefile.rules
  README.buildsys.md
  README.md
  aclocal.m4
  cnf/gac.in
  cnf/ltmain.sh
  cnf/m4/libtool.m4
  cnf/m4/ltoptions.m4
  cnf/m4/ltsugar.m4
  cnf/m4/ltversion.m4
  cnf/m4/lt~obsolete.m4
  configure.ac
  dev/ci.sh
Labels: topic: build system, release notes: use title

#5596 change the generic `PermutationOp` method
  lib/oprt.gi
Labels: kind: enhancement, topic: library, release notes: not needed

#5598 Update INSTALL.md
  INSTALL.md
Labels: topic: documentation, release notes: not needed

#5587 This is a continuation of #5577 removing more unused function arguments
  grp/glzmodmz.gi
  lib/clashom.gi
  lib/coll.gi
  lib/combinat.gi
  lib/ctblgrp.gi
  lib/ctblperm.gi
  lib/custom_streams.gi
  lib/dt.g
  lib/factgrp.gi
  lib/fitfree.gd
  lib/fitfree.gi
  lib/gpfpiso.gi
  lib/gprd.gi
  lib/grp.gd
  lib/grp.gi
  lib/grpfp.gd
  lib/grplatt.gi
  lib/maxsub.gi
Labels: release notes: not needed

#5605 Fix typo in Makefile.gappkg
  etc/Makefile.gappkg
  etc/Makefile.gappkg.simple
Labels: release notes: not needed

#5603 dev/ci.sh: use GH Action grouping
  dev/ci.sh
Labels: release notes: not needed, topic: ci

#5602 buildsys: add some comments
  aclocal.m4
  autogen.sh
  configure.ac
Labels: topic: build system, release notes: not needed

#5604 buildsys: rename SPARC -> SYS_IS_SPARC, drop SYS_IS_CYGWIN32
  GNUmakefile.in
  Makefile.rules
  configure.ac
  dev/audit-config-h.sh
  src/gasman.c
Labels: topic: build system, release notes: not needed

#5611 Replace redundant ifs
  lib/dict.gi
  lib/grp.gi
  lib/kernel.g
  lib/orders.gi
  lib/ratfun1.gi
  lib/straight.gi
Labels: release notes: not needed

#5613 New script generating release notes
  dev/releases/.gitignore
  dev/releases/README.release_notes.md
  dev/releases/create_stable_branch.py
  dev/releases/generate_release_notes.py
  dev/releases/make_github_release.py
  dev/releases/release_notes.py
  dev/releases/update_website.py
  dev/releases/utils.py
  dev/releases/utils_github.py
Labels: release notes: not needed, topic: infrastructure

#5614 buildsys: detect 'check-manuals' exit code
  Makefile.rules
  lib/algebra.gd
  lib/ctbl.gd
  lib/matrix.gd
Labels: release notes: not needed
