Repository gap-system/gap, pull requests merged in 2024-06, with the labels that each got.

#5737 julia_gc: compensate for Julia guard pages
  src/julia_gc.c
Labels: topic: kernel, topic: julia, backport-to-4.13

#5738 Backport: Add CI job that tests with GAP.jl
  .github/workflows/gapjl.yml
Labels: release notes: not needed, topic: ci

#5739 Backport all recent Julia GC changes
  src/julia_gc.c
Labels: topic: kernel, topic: julia

#5741 Prepare for GAP 4.13.1
  CHANGES.md
  dev/releases/README.release_notes.md
  dev/releases/release_notes.py
Labels: release notes: not needed, backport-to-4.13

#5743 dev/releases/README.md: update & expand
  dev/releases/README.md
Labels: release notes: not needed, backport-to-4.13

#5747 Fix handling of order 2 generators in MTC
  lib/sgpres.gi
  tst/testbugfix/2024-06-17-MTC.tst
Labels: kind: bug, kind: bug: wrong result, release notes: to be added, backport-to-4.13

#5746 dev/bisect.sh: fix typo; restore compat with older GAP versions
  dev/bisect.sh
Labels: release notes: not needed, topic: infrastructure

#5756 Fix year for GAP release in output of `Cite()`
  lib/package.gi
Labels: topic: library, release notes: use title

#5753 Add CHARS_ALPHA and _StripEscapeSequences
  dev/releases/HelpLinks-to-JSON.g
  hpcgap/lib/helpbase.gi
  lib/files.gd
  lib/helpbase.gi
  lib/package.gi
  lib/profile.g
  lib/string.g
  lib/string.gi
  src/julia_gc.c
  tst/delegation.g
  tst/teststandard/varnames.tst
Labels: release notes: not needed

#5754 Add `PathSystemProgram`, the now recommended function to fetch the filename of a system program
  doc/ref/files.xml
  lib/debug.g
  lib/files.gd
  lib/files.gi
  lib/helpview.gi
  lib/pager.gi
  lib/polyconw.gi
  lib/process.gd
  lib/process.gi
  lib/streams.gd
  tst/testinstall/testunix/streams.tst
Labels: kind: enhancement, topic: library, release notes: use title

#5759 Fix typo in TestDirectory doc
  lib/test.gi
Labels: topic: documentation, release notes: not needed, backport-to-4.13

#5758 Fix `Testing` section in dev guidelines
  DEVELOPING.md
Labels: topic: documentation, release notes: not needed
