Repository gap-system/gap, pull requests merged in 2024-08, with the labels that each got.

#5770 Enhance coset enumeration to make it work in more cases
  doc/ref/grpfp.xml
  lib/grp.gd
  lib/grp.gi
  lib/grpfp.gi
  lib/sgpres.gi
  lib/tietze.gi
Labels: kind: enhancement, release notes: use title

#5774 kernel: add NEW_BLIST
  src/blister.c
  src/blister.h
  src/listfunc.c
Labels: topic: kernel, release notes: not needed

#5777 Don't call TzPrintStatus if printLevel = 0
  grp/glzmodmz.gi
  lib/tietze.gi
Labels: topic: library, release notes: not needed

#5776 Deprecate `Dependencies.OtherPackagesLoadedInAdvance` in `PackageInfo.g`
  doc/ref/gappkg.xml
  lib/package.gd
Labels: topic: packages, release notes: use title, kind: removal or deprecation

#5775 Add a few more IsRegularPGroup tests
  lib/grp.gd
  tst/testinstall/pgroups.tst
Labels: topic: tests, release notes: not needed

#5769 BUILD: set install_name for libgap on macOS
  Makefile.rules
Labels: topic: build system, backport-to-4.13

#5784 fix the documentation of `IsPGroup`
  grp/simple.gd
  lib/grp.gd
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5779 buildsys: regen build/main.c when config.status changes
  Makefile.rules
Labels: topic: build system, release notes: not needed

#5778 Add new function `MeetBlist`
  doc/ref/blist.xml
  lib/list.g
  tst/testinstall/kernel/blister.tst
Labels: kind: enhancement, kind: new feature, topic: library

#5783 Speed up orbit computations on integer sets and tuples by providing a better hash function for lists of small integers
  lib/dicthf.gi
  tst/teststandard/hash2.tst
Labels: kind: enhancement, topic: performance, topic: library, release notes: use title
