Repository gap-system/gap, pull requests merged in 2024-03, with the labels that each got.

#5660 Enhance `IsomorphismFpGroup(G)` to transfer in more cases information about `G` to its image
  lib/ghomfp.gi
  tst/testinstall/grpperm.tst
Labels: kind: enhancement, topic: library, release notes: use title

#5662 kernel: add 'void * ref' to all GC mark functions
  src/bags.inc
  src/calls.c
  src/cyclotom.c
  src/gasman.c
  src/gasman.h
  src/hpc/aobjects.c
  src/julia_gc.c
  src/julia_gc.h
  src/libgap-api.c
  src/objects.c
  src/objset.c
  src/precord.c
  src/precord.h
  src/weakptr.c
Labels: topic: kernel, release notes: not needed

#5670 Update COPYRIGHT file
  COPYRIGHT
Labels: release notes: not needed

#5673 fix a `<Log>` example in the Reference Manual
  lib/streams.gd
Labels: kind: bug, topic: documentation, release notes: not needed

#5366 Add user preference `HistoryBackwardSearchSkipIdenticalEntries`
  doc/ref/user_pref_list.xml
  lib/cmdledit.g
Labels: topic: library

#5674 Update CHANGES.md, preparing 4.13.0
  CHANGES.md
  dev/releases/release_notes.py
Labels: release notes: not needed

#5681 create/update `doc/ref/user_pref_list.xml` automatically
  .gitignore
  doc/make_doc.in
  doc/ref/user_pref_list.xml
  lib/userpref.g
  tst/extractmanuals.g
  tst/testinstall/userpref.tst
Labels: kind: bug, topic: documentation, topic: tests, release notes: not needed

#5679 dev/releases/README.md: update based on release experience
  dev/releases/README.md
  dev/releases/create_stable_branch.py
Labels: topic: documentation, release notes: not needed, topic: infrastructure

#5682 Reject invalid arguments for `SolvableQuotient` and `EpimorphismSolvableQuotient`
  lib/grppcfp.gi
  tst/testinstall/opers/SolvableQuotient.tst
Labels: kind: enhancement, release notes: use title, backport-to-4.13

#5686 Fix bug in `Test` with `rewriteToFile` parameter set when applied to mixed input and output test case.
  lib/test.gi
  tst/testbugfix/2024-03-20-Test-rewriteToFile-option.tst
Labels: kind: bug, topic: library, release notes: use title, backport-to-4.13

#5688 Fix a bug where multiplying a compressed matrix by a finite field element could produce a corrupt result leading to subsequent unexpected errors or even wrong results
  src/vec8bit.c
  tst/testbugfix/2024-03-25-compressed-mat-scalar.tst
Labels: kind: bug, kind: bug: wrong result, kind: bug: unexpected error, release notes: use title, backport-to-4.13
