Repository gap-system/gap, pull requests merged in 2024-12, with the labels that each got.

#5855 CI: use consistent python version
  .github/workflows/CI.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: release notes: not needed, topic: ci

#5848 kernel: simplify LtPRec code
  src/precord.c
Labels: topic: kernel, release notes: not needed

#5849 kernel: remove redundant 2nd arg to SortPRecRNam
  src/compiler.c
  src/exprs.c
  src/hpc/serialize.c
  src/hpc/threadapi.c
  src/intfuncs.c
  src/opers.cc
  src/precord.c
  src/precord.h
  src/vec8bit.c
  src/vecgf2.c
  tst/test-compile/basics.g.dynamic.c
Labels: topic: kernel, release notes: not needed

#5850 kernel: simplify 'print path' handling
  src/lists.c
  src/objects.c
  src/objects.h
  src/precord.c
Labels: topic: kernel, release notes: not needed

#5859 Increase GAP kernel version to 10.0 to indicate there were breaking kernel changes
  configure.ac
Labels: topic: kernel, release notes: use title

#5836 meataxe spring cleaning
  lib/meataxe.gi
Labels: topic: library, release notes: not needed

#5858 dev/releases: add download_release.sh, update README.md
  dev/releases/README.md
  dev/releases/download_release.sh
Labels: release notes: not needed, topic: infrastructure

#5865 meataxe: fix SMTX.SubQuotActions regressions
  lib/meataxe.gi
Labels: regression, release notes: not needed

#5864 Fix 'gap --version' to send its output to stdout and include a trailing newline
  dev/ci.sh
  src/gasman.c
  src/system.c
Labels: topic: kernel, release notes: use title, backport-to-4.14

#5863 Fix copy&paste mistake in comments
  src/io.c
  src/io.h
Labels: topic: kernel, release notes: not needed

#5867 No wrong cxx warning
  cnf/m4/ax_compiler_flags_cflags.m4
Labels: topic: build system

#5874 Fix `ImmutableMatrix` to not strip memory from matrices in the `IsObjWithMemory` filter
  lib/memory.gi
  tst/testinstall/memory.tst
Labels: kind: bug, kind: bug: wrong result, topic: library, release notes: use title, backport-to-4.14

#5875 simplify the code for `IsObjWithMemory`
  lib/memory.gd
  lib/memory.gi
Labels: kind: enhancement, topic: library, release notes: not needed

#5879 Document `TrivialGModule`
  doc/ref/meataxe.xml
  tst/testinstall/meataxe.tst
Labels: topic: documentation, topic: library, release notes: not needed
