Repository gap-system/gap, pull requests merged in 2024-11, with the labels that each got.

#5831 Fix `IsomorphismFpGroup` for perm groups to avoid unexpected errors when e.g. computing preimages
  lib/gpfpiso.gi
  tst/testbugfix/2024-Halloween-IsomorphismFp.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: use title

#4336 Remove unused sparselist code
  dev/MAINTAINERS
  lib/readsl.g
  lib/sparselist.gd
  lib/sparselistgen.gi
  lib/sparselistsorted.gi
  lib/sparsevectorsorted.gi
Labels: topic: library, release notes: not needed

#5832 Make AvailabilityTest for packages optional
  doc/ref/gappkg.xml
  lib/package.gi
  tst/testinstall/package.tst
Labels: topic: packages

#4951 Make `SwapMatrixColumns` and `SwapMatrixRows` faster for classic matrices (lists-of-lists)
  lib/matobj.gi
  lib/matobj2.gd
  src/lists.c
Labels: kind: enhancement, topic: performance, topic: kernel, release notes: use title

#5837 Fast SwapMatrixRows/columns for GF matrices
  lib/vecmat.gi
  src/vecgf2.c
Labels: topic: performance, topic: kernel, release notes: use title

#5838 Faster `SwapMatrixRows` and `SwapMatrixColumns` for 8bit matrices
  lib/mat8bit.gi
  src/vec8bit.c
Labels: topic: performance, topic: kernel, release notes: added

#5842 Update CHANGES.md, prepare for GAP 4.14.0-beta1
  CHANGES.md
Labels: release notes: not needed

#5841 fix indentation when printing double cosets
  lib/csetgrp.gi
Labels: release notes: not needed

#5835 set an exit code in `make_doc`
  doc/make_doc.in
Labels: kind: enhancement, release notes: not needed, topic: workflow

#5851 Change GAP kernel version to 9.1 (also changes the shared library version)
  configure.ac
Labels: topic: build system, topic: kernel, release notes: use title
