Repository gap-system/gap, pull requests merged in 2024-09, with the labels that each got.

#5785 Update for recent gaplint
  .gaplint.yml
  .github/workflows/lint.yml
  lib/grpfp.gi
  lib/kbsemi.gi
Labels: release notes: not needed

#5772 let `LoadPackage` collect data
  lib/package.gd
  lib/package.gi
  tst/testinstall/package.tst
Labels: kind: enhancement, topic: packages, release notes: not needed

#5791 Extend `Permuted` to also support non-dense lists
  lib/list.gd
  lib/list.gi
Labels: kind: enhancement, topic: library, release notes: use title

#5789 Improve linker flags for kernel extensions on macOS
  Makefile.rules
Labels: topic: build system, release notes: use title, backport-to-4.13

#5788 buildsys: unify the three 'gap' executable linker rules
  Makefile.rules
Labels: topic: build system, release notes: not needed

#5793 rewrite dev/releases/update_website.py, cleanup devtools
  dev/releases/make_archives.py
  dev/releases/make_github_release.py
  dev/releases/release_notes.py
  dev/releases/update_website.py
  dev/releases/utils.py
  dev/releases/utils_github.py
Labels: release notes: not needed, topic: infrastructure, backport-to-4.13

#5794 Avoid computing determinants for testing Killing forms for non-degeneracy
  lib/alglie.gi
Labels: kind: enhancement, topic: performance, topic: library

#5799 Some trivial cleanup for our meataxe
  lib/meataxe.gi
Labels: topic: library, release notes: not needed

#5801 Fix `WreathProductElementList` to not modify its list argument
  lib/gprd.gi
  tst/testinstall/opers/ListWreathProductElement.tst
Labels: kind: bug, topic: library, release notes: use title, backport-to-4.13

#5795 be more restrictive in the default method of `SmallGeneratingSet`, in order to avoid error messages
  lib/grp.gi
Labels: kind: bug: unexpected error, topic: library, release notes: use title

#5805 ExtRepOfObj for IsLetterAssocWordRep: return mutable list
  lib/wordlett.gi
  tst/testinstall/wordrep.tst
Labels: topic: library, release notes: not needed
