Repository gap-system/gap, pull requests merged in 2024-05, with the labels that each got.

#5707 Speed up `CyclotomicPolynomial` substantially
  lib/upoly.gi
Labels: kind: enhancement, topic: performance, release notes: use title

#5709 Fix regression in `IsomorphismPermGroupOrFailFpGroup` that caused it to fail in situations that worked in GAP 4.12.2
  lib/grpfp.gi
  tst/testbugfix/2024-05-06-IsomorphismPermGroupOrFailFpGroup.tst
Labels: kind: bug, release notes: use title

#5711 Fix regression in `IsomorphismGroups` leading to unexpected break loops
  lib/morpheus.gi
  tst/testbugfix/2024-05-06-Isom.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: use title

#5698 Improve construction of permutation actions and by this e.g. make `FactorCosetAction` faster by several magnitudes in certain examples
  lib/csetgrp.gd
  lib/csetgrp.gi
  lib/csetperm.gi
  lib/factgrp.gd
  lib/oprt.gi
  tst/teststandard/permgrp.tst
Labels: kind: enhancement, topic: performance, release notes: use title

#5712 Backports 4.13
  .github/workflows/CI.yml
  .github/workflows/update-gh-pages.yml
  .gitignore
  CONTRIBUTING.md
  dev/releases/README.md
  dev/releases/create_stable_branch.py
  doc/make_doc.in
  doc/ref/user_pref_list.xml
  lib/gpfpiso.gi
  lib/grpfp.gd
  lib/grpfp.gi
  lib/grppcfp.gi
  lib/morpheus.gi
  lib/test.gi
  lib/userpref.g
  src/vec8bit.c
  tst/extractmanuals.g
  tst/testbugfix/2024-03-16-FpGroups.tst
  tst/testbugfix/2024-03-20-Test-rewriteToFile-option.tst
  tst/testbugfix/2024-03-25-compressed-mat-scalar.tst
  tst/testbugfix/2024-05-06-Isom.tst
  tst/testbugfix/2024-05-06-IsomorphismPermGroupOrFailFpGroup.tst
  tst/testinstall/grpfp.tst
  tst/testinstall/opers/SolvableQuotient.tst
  tst/testinstall/userpref.tst
Labels: release notes: not needed

#5713 Fix typo in INSTALL.md
  INSTALL.md
Labels: release notes: not needed

#5719 kernel: reorder, cleanup & document code in julia_gc.c
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia, backport-to-4.13

#5723 Fix an error message when computing subgroup lattices of certain insolvable groups
  lib/oprtglat.gi
  lib/pcgsind.gd
  lib/pcgsind.gi
  tst/testbugfix/2024-05-24-Cluster.tst
Labels: kind: bug: unexpected error, priority: high, release notes: use title, backport-to-4.13

#5722 Improve compatibility of the Julia GC integration with multi threaded Julia
  src/julia_gc.c
Labels: topic: kernel, topic: julia, release notes: use title, backport-to-4.13

#5724 julia_gc: replace jl_task_stack_buffer by jl_active_task_stack
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia, backport-to-4.13

#5728 Fix CyclotomicPol(501) and others
  lib/upoly.gi
  tst/testinstall/upoly.tst
Labels: regression, release notes: not needed

#5727 julia_gc: remove SKIP_GUARD_PAGES mode
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia, backport-to-4.13

#5726 julia_gc: fix detection of already canned root task
  src/julia_gc.c
Labels: topic: kernel, release notes: not needed, topic: julia, backport-to-4.13

#5730 Fix an error in `MinimalFaithfulPermutationDegree`, for the case of abelian direct factors
  lib/grplatt.gi
  tst/testbugfix/2024-05-28-Mindeg.tst
Labels: kind: bug: wrong result, release notes: use title, backport-to-4.13
