Repository gap-system/gap, pull requests merged in 2024-10, with the labels that each got.

#5804 kernel: wait for child process to die before closing pty
  src/iostream.c
Labels: kind: bug, topic: kernel

#5797 Speed up `IsRegularPGroup`
  lib/grp.gi
Labels: topic: performance, topic: library, release notes: use title

#5807 Fix hashing for integer plists
  lib/dicthf.gi
  tst/testbugfix/2024-10-11-orbit-hash.tst
Labels: regression, topic: library, release notes: not needed

#5814 CI: fix OpenBSD CI test
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: infrastructure

#5812 CI: update codecov/codecov-action from 3 to 4
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: infrastructure

#5813 Better input validation for GModuleByMats
  lib/meataxe.gi
  tst/testinstall/meataxe.tst
Labels: topic: library, release notes: not needed

#5815 Reorder sections in release notes
  dev/releases/release_notes.py
Labels: release notes: not needed, topic: infrastructure

#5811 Fix stabilizer computation in alternating groups which could sometimes return a wrong result
  lib/gpprmsya.gi
  tst/testbugfix/2024-10-11-alt-stab.tst
Labels: kind: bug, kind: bug: wrong result, release notes: use title

#5820 minor improvements of the Reference Manual
  grp/classic.gd
  lib/cache.gd
  lib/ctbllatt.gd
  lib/grp.gd
  lib/matrix.gd
  lib/permutat.g
  lib/streams.gd
Labels: kind: enhancement, topic: documentation, release notes: not needed

#5731 avoid an attribute value after leaving a break loop
  lib/grpfp.gi
Labels: release notes: not needed, kind: discussion

#5817 Fix `IsIntegralRing` to return `false` for rings that are euclidean but not integral by changing `IsUniqueFactorizationRing` and `IsEuclideanRing` to not imply `IsIntegralRing` anymore
  lib/ring.gd
  lib/ring.gi
  tst/testinstall/ring.tst
Labels: kind: bug, kind: bug: wrong result, release notes: use title

#5825 fix GAPDoc syntax for the manual in `doc/dev`
  doc/dev/kernel.xml
Labels: kind: bug, topic: documentation, release notes: not needed

#5821 kernel: cleanup vararg argument names
  src/gvars.c
  src/hpc/threadapi.c
  src/streams.c
  src/tietze.c
Labels: topic: kernel, release notes: not needed

#5827 CI: don't disable -Werror for Julia builds
  .github/workflows/CI.yml
  .github/workflows/gapjl.yml
  src/julia_gc.c
Labels: release notes: not needed, topic: ci

#5822 Make `FirstNames` optional in `Persons` records in package metadata
  doc/ref/gappkg.xml
  lib/package.gi
  tst/testinstall/package.tst
Labels: kind: bug, topic: library, release notes: use title

#5830 buildsys: allow overriding Julia config via env vars
  GNUmakefile.in
  configure.ac
Labels: topic: build system, release notes: not needed, topic: julia
