Repository gap-system/gap, pull requests merged in 2024-04, with the labels that each got.

#5677 Ensure fp groups for which Size successfully computed the order can also be enumerated (previously this could run out of memory)
  lib/grpfp.gd
  lib/grpfp.gi
  tst/testbugfix/2024-03-16-FpGroups.tst
Labels: kind: enhancement, topic: performance, release notes: use title

#5690 Update links to manuals
  CONTRIBUTING.md
Labels: topic: documentation, release notes: not needed, backport-to-4.13

#5683 support initial search in `PAGER_BUILTIN`
  lib/methwhy.g
  lib/pager.gd
  lib/pager.gi
Labels: kind: enhancement, topic: library, release notes: not needed

#5705 fix `PreImagesRepresentative` for `IsToPcGroupHomomorphismByImages`
  lib/ghompcgs.gi
  tst/testinstall/grppc.tst
Labels: kind: bug, kind: bug: wrong result, release notes: not needed
