Repository gap-system/gap, pull requests merged in 2025-08, with the labels that each got.

#6050 Add reference [Lan70] (used for `ER`)
  doc/manualbib.xml
  lib/cyclotom.gd
Labels: kind: enhancement, topic: documentation, release notes: not needed

#6049 Remove the `HACKUSERPREF` code from files in `lib`
  lib/init.g
  lib/obsolete.gd
  lib/pager.gi
  lib/permdeco.gi
  lib/userpref.g
Labels: kind: enhancement, topic: library, release notes: not needed

#6056 Add <unistd.h> so we can get the pagesize
  src/sysmem.c
  src/system.c
Labels: regression, topic: kernel, release notes: not needed

#6043 kernel: some cleanup allowed due to changed julia compat
  src/julia_gc.c
Labels: release notes: not needed, topic: julia

#6058 kernel: further cleanup to gap-with-julia
  src/julia_gc.c
Labels: topic: kernel, topic: julia

#6066 Fix IsOne for rational functions
  hpcgap/lib/ratfun.gi
  lib/ratfun.gi
  tst/testinstall/ratfun.tst
  tst/testinstall/ratfun_gf5.tst
  tst/testinstall/ringpoly.tst
Labels: regression, release notes: not needed

#6075 Speed up `CharacterDegrees`
  lib/ctbl.gd
  lib/ctbl.gi
  lib/ctblsolv.gd
  lib/ctblsolv.gi
  tst/testbugfix/2005-08-23-t00094.tst
  tst/testinstall/ctblsolv.tst
Labels: kind: enhancement, topic: performance, topic: library, release notes: use title, gapdays2025-summer

#6076 Fix `AntiSymmetricParts`
  lib/ctblfuns.gi
  tst/testinstall/ctblfuns.tst
Labels: kind: bug, kind: bug: wrong result, topic: library, release notes: not needed, gapdays2025-summer

#6067 Deprecate `InstallValue` for anything but plain objects (i.e., plain GAP lists, records or strings) and warn if it is done anyway
  lib/variable.g
  tst/testbugfix/00000.tst
Labels: topic: library, release notes: use title, gapdays2025-summer
