Repository gap-system/gap, pull requests merged in 2025-02, with the labels that each got.

#5901 CI: switch ubuntu-20.04 to ubuntu-22.04
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: ci

#5925 fix delegations among `IrreducibleModules` methods
  lib/grpreps.gi
  tst/testinstall/grpreps.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: not needed

#5936 Fix `--quiet` in the command line interface to be identical to `-q`
  src/system.c
Labels: kind: bug, release notes: use title, backport-to-4.14

#5935 Fix an unexpected error in `IsomorphismGroups`
  lib/autsr.gi
  lib/fitfree.gi
  tst/testbugfix/2025-02-10-Isomorphism.tst
Labels: kind: bug: unexpected error, release notes: use title, backport-to-4.14

#5918 Improve printing of nested expressions
  src/exprs.c
  tst/testinstall/kernel/exprs.tst
Labels: topic: kernel, release notes: not needed

#5896 kernel: close streams after internal exception
  src/streams.c
Labels: kind: bug, kind: bug: crash, topic: kernel, release notes: not needed

#5942 set the irreducibility flag in group characters
  lib/ctbl.gi
  lib/ctblfuns.gi
  lib/ctblsolv.gi
  tst/testinstall/ctbl.tst
Labels: kind: enhancement, topic: library, release notes: not needed

#5938 Allow loading of extraperfect files from all root dirs
  grp/perf.grp
Labels: kind: enhancement, topic: library, backport-to-4.14
