Repository gap-system/gap, pull requests merged in 2025-05, with the labels that each got.

#5958 Add benchmarks for `ExtractSubMatrix` + `CopySubMatrix`
  benchmark/matobj/bench-matelm-access.g
  benchmark/matobj/bench-submat.g
Labels: release notes: not needed

#5988 Fix wrong return value in `CoefficientsOfUnivariateRationalFunction` which occurs in rare circumstances
  hpcgap/lib/ratfun.gi
  lib/ratfun.gi
  tst/testbugfix/2025-05-09-ratfun-coeff.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: not needed, backport-to-4.14

#5956 Make `ArithmeticElementCreator` understand re-read mode
  lib/proto.gi
Labels: kind: enhancement, topic: library, release notes: not needed, backport-to-4.14

#5990 kernel: fix typos / language
  src/read.c
Labels: topic: kernel, release notes: not needed

#5995 Fix typo in `TryGcdCancelExtRepPolynomials`
  lib/ratfun1.gi
  tst/testinstall/ratfun.tst
Labels: release notes: not needed

#5992 Fix a potential linker issue during `make install` on macOS
  Makefile.rules
Labels: kind: bug, os: macos, topic: build system, backport-to-4.14
