Repository gap-system/gap, pull requests merged in 2025-03, with the labels that each got.

#5947 fix a bug in `AlgebraHomomorphismByImages`
  lib/alghom.gi
  tst/testinstall/alghom.tst
Labels: kind: bug, kind: bug: wrong result, topic: library, release notes: to be added

#5951 Trivial tweaks
  lib/meatauto.gi
  src/ariths.c
Labels: release notes: not needed

#5955 Fix errors for algebra homomorphisms (infinite recursions and "no method found" errors), in particular concerning homomorphisms that are constructed as inverse mappings
  lib/alghom.gi
  lib/mapprep.gi
  tst/testinstall/alghom.tst
Labels: kind: bug, kind: bug: unexpected error, topic: library, release notes: use title

#5954 kernel: restore (De)ActivateHooks return value
  src/hookintrprtr.c
  src/hookintrprtr.h
Labels: topic: kernel, release notes: not needed

#5961 fix problems with `IsBlockMatrixRep`
  lib/matblock.gi
  lib/matobj.gi
  tst/testinstall/matblock.tst
Labels: kind: bug: unexpected error, topic: library, release notes: not needed

#5959 meataxe: make endomorphism ring computation faster
  lib/meatauto.gi
Labels: kind: enhancement, topic: performance, topic: library

#5960 Add support for `#@elif` clauses in `Test` files
  lib/test.gi
  tst/testinstall/testing.tst
  tst/testspecial/broken-test-7.tst
  tst/testspecial/broken-test-8.tst
  tst/testspecial/broken-test-9.tst
  tst/testspecial/broken-test.g
  tst/testspecial/broken-test.g.out
Labels: release notes: use title

#5957 Various minor meataxe improvements
  lib/meatauto.gi
  lib/meataxe.gi
  tst/testinstall/meatauto.tst
Labels: kind: enhancement, topic: library, release notes: not needed

#5965 Remove a duplicate `AutomorphismGroup` method
  lib/morpheus.gi
Labels: topic: library, release notes: not needed

#5964 Fix a bug in the code computing automorphisms of modules, which e.g. affects computing automorphism groups and could lead to outer automorphisms being missed
  lib/meatauto.gi
  tst/testbugfix/2025-03-28-ModuleAutomorphisms.tst
Labels: kind: bug, kind: bug: wrong result, topic: library, release notes: use title, backport-to-4.14

#5966 add `IsDicyclicGroup` and `DicyclicGenerators`
  lib/grpnames.gd
  lib/grpnames.gi
  tst/testinstall/grp/basic.tst
Labels: kind: enhancement, topic: library, release notes: use title, backport-to-4.14
