Repository gap-system/gap, pull requests merged in 2025-06, with the labels that each got.

#5970 introduce `MayBeHandledByNiceMonomorphism`, in order to detect early whether a group shall be handled by nice monomorphisms
  lib/grpnice.gd
  lib/grpnice.gi
  lib/grpramat.gi
  lib/morpheus.gd
  lib/pcgsnice.gi
  tst/testinstall/mapping.tst
  tst/testinstall/matblock.tst
Labels: kind: enhancement, topic: library, release notes: use title

#6002 Fix bug in `SpecialPcgs` that could corrupt group objects and cause nonsense outputs
  lib/pcgsspec.gi
  tst/testbugfix/2025-06-04-SpecialPcgs.tst
Labels: kind: bug, kind: bug: wrong result, release notes: use title, backport-to-4.14

#5987 Fix ExtRepOfPolynomial_String for zero polynomial
  hpcgap/lib/ratfun.gi
  lib/ratfun.gi
  tst/testbugfix/2025-05-09-ratfun-zero-string.tst
Labels: kind: bug, kind: bug: unexpected error, release notes: not needed, backport-to-4.14

#6016 Clean up non-portable long family types
  etc/ffgen.c
  src/blister.c
  src/finfield_conway.h
  src/integer.c
  src/macfloat.h
  src/scanner.h
Labels: topic: kernel, release notes: not needed

#6017 CI: drop another ABI=32 test; earlier 'apt-get update'
  .github/workflows/CI.yml
Labels: release notes: not needed, topic: infrastructure, topic: ci

#5826 Fix wreath product with trivial group to not contain redundant trivial generators
  lib/gprdmat.gi
  lib/gprdperm.gi
  tst/testbugfix/2024_10_24_WreathProductWIthTrivialGroups.tst
Labels: kind: quirk

#6019 Fix regression in `WreathProduct`
  lib/gprdperm.gi
Labels: regression, release notes: not needed

#6011 Add an `Irr` method for natural alternating groups, using the generic character table
  lib/ctblfuns.gd
  lib/ctblmono.gd
  lib/ctblsymm.gi
  lib/gpprmsya.gi
  tst/testinstall/ctblmono.tst
  tst/teststandard/ctblsymm.tst
Labels: kind: enhancement, kind: bug: wrong result, topic: library, release notes: use title

#6021 kernel: rewrite OneMatrix/InvMatrix to not use IMMUTABLE
  src/listoper.c
Labels: topic: kernel, release notes: not needed
